import { beforeEach, describe, expect, it, vi } from "vitest";

const { prismaMock } = vi.hoisted(() => ({
  prismaMock: {
    $transaction: vi.fn(),
    paper: {
      findFirst: vi.fn(),
      update: vi.fn(),
    },
    paperRelation: {
      findMany: vi.fn(),
      findUnique: vi.fn(),
      deleteMany: vi.fn(),
    },
    relationAssertion: {
      deleteMany: vi.fn(),
    },
    paperEntity: {},
    paperIdentifier: {},
    paperEntityCandidateLink: {},
  },
}));

vi.mock("../../prisma", () => ({
  prisma: prismaMock,
}));

vi.mock("../../canonical/entity-service", () => ({
  collectIdentifiers: vi.fn(),
  resolveOrCreateEntity: vi.fn(),
}));

vi.mock("../relation-assertion-service", () => ({
  createRelationAssertion: vi.fn(),
}));

vi.mock("../relation-aggregate", () => ({
  getAggregatedRelationsForPaper: vi.fn(),
}));

vi.mock("../legacy-projection", () => ({
  projectLegacyRelation: vi.fn(),
}));

import {
  GraphRelationError,
  buildLegacyOverlayRows,
  clearAutoGeneratedRelationsForPaper,
  createManualRelation,
  ensurePaperEntityForGraph,
  listRelationsForPaper,
} from "../graph-relations";
import { collectIdentifiers, resolveOrCreateEntity } from "../../canonical/entity-service";
import { createRelationAssertion } from "../relation-assertion-service";
import { getAggregatedRelationsForPaper } from "../relation-aggregate";
import { projectLegacyRelation } from "../legacy-projection";

describe("ensurePaperEntityForGraph", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns already-linked papers without attempting hydration", async () => {
    const paper = {
      id: "paper-1",
      userId: "user-1",
      entityId: "entity-1",
      title: "Linked paper",
      authors: null,
      year: null,
      venue: null,
      abstract: null,
      doi: null,
      arxivId: null,
      semanticScholarId: null,
    };

    const result = await ensurePaperEntityForGraph(paper);

    expect(result).toEqual(paper);
    expect(collectIdentifiers).not.toHaveBeenCalled();
    expect(resolveOrCreateEntity).not.toHaveBeenCalled();
  });

  it("hydrates papers with stable identifiers and updates the paper row", async () => {
    vi.mocked(collectIdentifiers).mockReturnValue([
      { type: "doi", value: "10.1234/example", source: "graph_auto_heal" },
    ]);
    vi.mocked(resolveOrCreateEntity).mockResolvedValue({
      entityId: "entity-2",
      created: false,
    });
    prismaMock.paper.findFirst.mockResolvedValueOnce(null);
    prismaMock.paper.update.mockResolvedValueOnce({
      id: "paper-2",
      userId: "user-1",
      entityId: "entity-2",
      title: "Needs hydration",
      authors: "[]",
      year: 2024,
      venue: null,
      abstract: null,
      doi: "10.1234/example",
      arxivId: null,
      semanticScholarId: null,
    });

    const result = await ensurePaperEntityForGraph({
      id: "paper-2",
      userId: "user-1",
      entityId: null,
      title: "Needs hydration",
      authors: "[]",
      year: 2024,
      venue: null,
      abstract: null,
      doi: "10.1234/example",
      arxivId: null,
      semanticScholarId: null,
    });

    expect(resolveOrCreateEntity).toHaveBeenCalled();
    expect(prismaMock.paper.update).toHaveBeenCalledWith({
      where: { id: "paper-2" },
      data: { entityId: "entity-2" },
      select: expect.any(Object),
    });
    expect(result.entityId).toBe("entity-2");
  });

  it("fails closed with 409 when identifiers are missing", async () => {
    vi.mocked(collectIdentifiers).mockReturnValue([]);

    await expect(
      ensurePaperEntityForGraph({
        id: "paper-3",
        userId: "user-1",
        entityId: null,
        title: "No ids",
        authors: null,
        year: null,
        venue: null,
        abstract: null,
        doi: null,
        arxivId: null,
        semanticScholarId: null,
      })
    ).rejects.toMatchObject<Partial<GraphRelationError>>({
      status: 409,
      code: "missing_identifiers",
    });
  });
});

describe("buildLegacyOverlayRows", () => {
  it("suppresses legacy rows already represented by aggregate rows", () => {
    const aggregateRows = [
      {
        id: "agg::entity-2::cites",
        relatedPaper: {
          id: "paper-2",
          entityId: "entity-2",
          title: "Peer",
          year: 2024,
          authors: null,
        },
        relationType: "cites",
        description: null,
        confidence: 0.9,
        isAutoGenerated: true,
      },
    ];

    const legacyRows = [
      {
        id: "rel-1",
        relatedPaper: {
          id: "paper-2",
          entityId: "entity-2",
          title: "Peer",
          year: 2024,
          authors: null,
        },
        relationType: "cites",
        description: null,
        confidence: 0.8,
        isAutoGenerated: true,
      },
      {
        id: "rel-2",
        relatedPaper: {
          id: "paper-3",
          entityId: null,
          title: "Unresolved peer",
          year: 2023,
          authors: null,
        },
        relationType: "cites",
        description: null,
        confidence: 0.7,
        isAutoGenerated: true,
      },
    ];

    expect(buildLegacyOverlayRows(aggregateRows, legacyRows)).toEqual([legacyRows[1]]);
  });
});

describe("listRelationsForPaper", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns legacy fallback rows when the paper is unlinked", async () => {
    prismaMock.paper.findFirst.mockResolvedValueOnce({
      id: "paper-1",
      entityId: null,
    });
    prismaMock.paperRelation.findMany
      .mockResolvedValueOnce([
        {
          id: "rel-1",
          relationType: "cites",
          description: "legacy",
          confidence: 0.7,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-2",
            entityId: null,
            title: "Target",
            year: 2024,
            authors: null,
          },
        },
      ])
      .mockResolvedValueOnce([]);

    const result = await listRelationsForPaper("paper-1", "user-1");

    expect(result.mode).toBe("legacy_fallback");
    expect(result.overlayRows).toHaveLength(0);
    expect(result.rows).toHaveLength(1);
    expect(result.rows[0].id).toBe("rel-1");
  });

  it("returns aggregate rows only when no overlay is needed", async () => {
    prismaMock.paper.findFirst
      .mockResolvedValueOnce({
        id: "paper-1",
        entityId: "entity-1",
      })
      .mockResolvedValueOnce({
        id: "paper-2",
        entityId: "entity-2",
        title: "Peer",
        year: 2024,
        authors: null,
      });
    vi.mocked(getAggregatedRelationsForPaper).mockResolvedValue([
      {
        peerEntityId: "entity-2",
        peerEntity: {
          id: "entity-2",
          title: "Peer",
          year: 2024,
          authors: null,
        },
        relationType: "cites",
        maxConfidence: 0.9,
        assertionCount: 1,
        provenances: ["user_manual"],
        description: "aggregate",
      },
    ]);
    prismaMock.paperRelation.findMany.mockResolvedValue([]);

    const result = await listRelationsForPaper("paper-1", "user-1");

    expect(result.mode).toBe("aggregate_only");
    expect(result.overlayRows).toHaveLength(0);
    expect(result.rows).toHaveLength(1);
    expect(result.rows[0].id).toBe("agg::entity-2::cites");
  });

  it("adds overlay rows when aggregate output would drop visible legacy peers", async () => {
    prismaMock.paper.findFirst
      .mockResolvedValueOnce({
        id: "paper-1",
        entityId: "entity-1",
      })
      .mockResolvedValueOnce({
        id: "paper-2",
        entityId: "entity-2",
        title: "Represented peer",
        year: 2024,
        authors: null,
      });
    vi.mocked(getAggregatedRelationsForPaper).mockResolvedValue([
      {
        peerEntityId: "entity-2",
        peerEntity: {
          id: "entity-2",
          title: "Represented peer",
          year: 2024,
          authors: null,
        },
        relationType: "cites",
        maxConfidence: 0.9,
        assertionCount: 1,
        provenances: ["reference_match"],
        description: "aggregate",
      },
    ]);
    prismaMock.paperRelation.findMany
      .mockResolvedValueOnce([
        {
          id: "rel-1",
          relationType: "cites",
          description: "represented legacy",
          confidence: 0.9,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-2",
            entityId: "entity-2",
            title: "Represented peer",
            year: 2024,
            authors: null,
          },
        },
        {
          id: "rel-2",
          relationType: "cites",
          description: "unresolved legacy",
          confidence: 0.8,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-3",
            entityId: null,
            title: "Legacy-only peer",
            year: 2023,
            authors: null,
          },
        },
      ])
      .mockResolvedValueOnce([]);

    const result = await listRelationsForPaper("paper-1", "user-1");

    expect(result.mode).toBe("aggregate_with_overlay");
    expect(result.aggregateRows).toHaveLength(1);
    expect(result.overlayRows).toEqual([expect.objectContaining({ id: "rel-2" })]);
    expect(result.rows.map((row) => row.id)).toContain("agg::entity-2::cites");
    expect(result.rows.map((row) => row.id)).toContain("rel-2");
  });
});

describe("createManualRelation", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("fails the whole mutation when projection fails", async () => {
    const tx = {
      paper: {
        findFirst: vi
          .fn()
          .mockResolvedValueOnce({
            id: "paper-1",
            userId: "user-1",
            entityId: "entity-1",
            title: "Source",
            authors: null,
            year: 2024,
            venue: null,
            abstract: null,
            doi: "10.1/source",
            arxivId: null,
            semanticScholarId: null,
          })
          .mockResolvedValueOnce({
            id: "paper-2",
            userId: "user-1",
            entityId: "entity-2",
            title: "Target",
            authors: null,
            year: 2024,
            venue: null,
            abstract: null,
            doi: "10.1/target",
            arxivId: null,
            semanticScholarId: null,
          }),
      },
      paperRelation: {
        findUnique: vi.fn(),
      },
      relationAssertion: {},
      paperEntity: {},
      paperIdentifier: {},
      paperEntityCandidateLink: {},
    };

    prismaMock.$transaction.mockImplementation(async (callback) => callback(tx));
    vi.mocked(createRelationAssertion).mockResolvedValue({ id: "assertion-1" } as never);
    vi.mocked(projectLegacyRelation).mockRejectedValue(new Error("projection blew up"));

    await expect(
      createManualRelation({
        paperId: "paper-1",
        targetPaperId: "paper-2",
        userId: "user-1",
        relationType: "extends",
      })
    ).rejects.toThrow("projection blew up");
  });

  it("hydrates missing entities and returns the projected legacy payload", async () => {
    const tx = {
      paper: {
        findFirst: vi
          .fn()
          .mockResolvedValueOnce({
            id: "paper-1",
            userId: "user-1",
            entityId: null,
            title: "Source",
            authors: null,
            year: 2024,
            venue: null,
            abstract: null,
            doi: "10.1/source",
            arxivId: null,
            semanticScholarId: null,
          })
          .mockResolvedValueOnce({
            id: "paper-2",
            userId: "user-1",
            entityId: "entity-2",
            title: "Target",
            authors: null,
            year: 2024,
            venue: null,
            abstract: null,
            doi: "10.1/target",
            arxivId: null,
            semanticScholarId: null,
          })
          .mockResolvedValueOnce(null),
        update: vi.fn().mockResolvedValue({
          id: "paper-1",
          userId: "user-1",
          entityId: "entity-1",
          title: "Source",
          authors: null,
          year: 2024,
          venue: null,
          abstract: null,
          doi: "10.1/source",
          arxivId: null,
          semanticScholarId: null,
        }),
      },
      paperRelation: {
        findUnique: vi.fn().mockResolvedValue({
          id: "rel-1",
          relationType: "extends",
          description: "Manual relation",
          confidence: 1,
          isAutoGenerated: false,
          targetPaper: {
            id: "paper-2",
            entityId: "entity-2",
            title: "Target",
            year: 2024,
            authors: null,
          },
        }),
      },
      relationAssertion: {},
      paperEntity: {},
      paperIdentifier: {},
      paperEntityCandidateLink: {},
    };

    prismaMock.$transaction.mockImplementation(async (callback) => callback(tx));
    vi.mocked(collectIdentifiers).mockReturnValue([
      { type: "doi", value: "10.1/source", source: "graph_auto_heal" },
    ]);
    vi.mocked(resolveOrCreateEntity).mockResolvedValue({
      entityId: "entity-1",
      created: false,
    });
    vi.mocked(createRelationAssertion).mockResolvedValue({ id: "assertion-1" } as never);
    vi.mocked(projectLegacyRelation).mockResolvedValue();

    const result = await createManualRelation({
      paperId: "paper-1",
      targetPaperId: "paper-2",
      userId: "user-1",
      relationType: "extends",
      description: "Manual relation",
    });

    expect(result).toEqual({
      id: "rel-1",
      relatedPaper: {
        id: "paper-2",
        title: "Target",
        year: 2024,
        authors: null,
      },
      relationType: "extends",
      description: "Manual relation",
      confidence: 1,
      isAutoGenerated: false,
    });
    expect(resolveOrCreateEntity).toHaveBeenCalled();
  });
});

describe("clearAutoGeneratedRelationsForPaper", () => {
  it("clears auto-generated assertions and projected relations", async () => {
    await clearAutoGeneratedRelationsForPaper("paper-1");

    expect(prismaMock.relationAssertion.deleteMany).toHaveBeenCalledWith({
      where: {
        sourcePaperId: "paper-1",
        provenance: { not: "user_manual" },
      },
    });
    expect(prismaMock.paperRelation.deleteMany).toHaveBeenCalledWith({
      where: {
        isAutoGenerated: true,
        OR: [{ sourcePaperId: "paper-1" }, { targetPaperId: "paper-1" }],
      },
    });
  });
});
