import { describe, expect, it } from "vitest";

import { prisma } from "../../prisma";
import { listRelationsForPaper } from "../relation-reader";

function isSanctionedEntitylessLegacyRelation(relation: {
  relationType: string;
  description: string | null;
  isAutoGenerated: boolean;
}) {
  if (!relation.isAutoGenerated) return false;
  if (relation.relationType !== "cites") return true;
  return relation.description?.startsWith("Cited in references as:") ?? false;
}

describe("Phase 3 parity", () => {
  it("every PaperRelation is either assertion-backed or a sanctioned entity-less legacy edge", async () => {
    const relations = await prisma.paperRelation.findMany({
      include: {
        sourcePaper: { select: { entityId: true } },
        targetPaper: { select: { entityId: true } },
      },
    });

    const failures: string[] = [];

    for (const relation of relations) {
      if (!relation.sourcePaper.entityId || !relation.targetPaper.entityId) {
        if (!isSanctionedEntitylessLegacyRelation(relation)) {
          failures.push(
            `${relation.id}: unsanctioned entity-less relation ${relation.relationType} from ${relation.sourcePaperId} -> ${relation.targetPaperId}`,
          );
        }
        continue;
      }

      const matchingAssertion = await prisma.relationAssertion.findFirst({
        where: {
          sourcePaperId: relation.sourcePaperId,
          targetEntityId: relation.targetPaper.entityId,
          relationType: relation.relationType,
        },
        select: { id: true },
      });

      if (!matchingAssertion) {
        failures.push(
          `${relation.id}: ${relation.relationType} from ${relation.sourcePaperId} -> ${relation.targetPaper.entityId}`
        );
      }
    }

    expect(failures, failures.slice(0, 10).join("\n")).toHaveLength(0);
  });

  it("assertions preserve description from linked legacy PaperRelation rows", async () => {
    const relations = await prisma.paperRelation.findMany({
      where: { description: { not: null } },
      include: {
        sourcePaper: { select: { entityId: true } },
        targetPaper: { select: { entityId: true } },
      },
    });

    const mismatches: string[] = [];

    for (const relation of relations) {
      if (!relation.sourcePaper.entityId || !relation.targetPaper.entityId) continue;

      const assertion = await prisma.relationAssertion.findFirst({
        where: {
          sourcePaperId: relation.sourcePaperId,
          targetEntityId: relation.targetPaper.entityId,
          relationType: relation.relationType,
        },
        select: { description: true },
      });

      if (assertion && assertion.description !== relation.description) {
        mismatches.push(`${relation.id}: "${relation.description}" != "${assertion.description}"`);
      }
    }

    expect(mismatches, mismatches.slice(0, 10).join("\n")).toHaveLength(0);
  });

  it("shared relation reader covers inbound linked legacy relations", async () => {
    const papers = await prisma.paper.findMany({
      where: {
        userId: { not: null },
        targetRelations: { some: {} },
      },
      select: {
        id: true,
        userId: true,
      },
    });

    for (const paper of papers) {
      const inboundRelations = await prisma.paperRelation.findMany({
        where: { targetPaperId: paper.id },
        include: {
          sourcePaper: { select: { entityId: true } },
        },
      });

      const visibleRelations = await listRelationsForPaper(
        paper.id,
        paper.userId!,
      );

      for (const legacyRelation of inboundRelations) {
        const matchingRelation = visibleRelations.rows.find(
          (relation) =>
            relation.relatedPaper.id === legacyRelation.sourcePaperId &&
            relation.relationType === legacyRelation.relationType
        );

        expect(
          matchingRelation,
          `Paper ${paper.id}: missing inbound ${legacyRelation.relationType} from ${legacyRelation.sourcePaperId}`
        ).toBeDefined();
      }
    }
  });

  it("shared relation reader covers outbound linked legacy relations", async () => {
    const papers = await prisma.paper.findMany({
      where: {
        userId: { not: null },
        sourceRelations: { some: {} },
      },
      select: {
        id: true,
        userId: true,
      },
    });

    for (const paper of papers) {
      const outboundRelations = await prisma.paperRelation.findMany({
        where: { sourcePaperId: paper.id },
        include: {
          targetPaper: { select: { entityId: true } },
        },
      });

      const visibleRelations = await listRelationsForPaper(
        paper.id,
        paper.userId!,
      );

      for (const legacyRelation of outboundRelations) {
        const matchingRelation = visibleRelations.rows.find(
          (relation) =>
            relation.relatedPaper.id === legacyRelation.targetPaperId &&
            relation.relationType === legacyRelation.relationType
        );

        expect(
          matchingRelation,
          `Paper ${paper.id}: missing outbound ${legacyRelation.relationType} to ${legacyRelation.targetPaperId}`
        ).toBeDefined();
      }
    }
  });
});
