import { beforeEach, describe, expect, it, vi } from "vitest";

const { prismaMock } = vi.hoisted(() => ({
  prismaMock: {
    paper: {
      findFirst: vi.fn(),
      findUnique: vi.fn(),
    },
    paperRelation: {
      findMany: vi.fn(),
    },
    relationAssertion: {
      count: vi.fn(),
    },
    paperRepresentation: {
      findMany: vi.fn(),
      findUnique: vi.fn(),
    },
  },
}));

vi.mock("../../prisma", () => ({
  prisma: prismaMock,
}));

vi.mock("../relation-aggregate", () => ({
  getAggregatedRelationsForPaper: vi.fn(),
}));

vi.mock("../../papers/retrieval/related-ranker", () => ({
  rerankRelatedRelationRows: vi.fn(async (_paperId: string, _userId: string, rows: unknown[]) => rows),
}));

import {
  listProjectedTargetPaperIds,
  listRelationsForPaper,
} from "../relation-reader";
import { getAggregatedRelationsForPaper } from "../relation-aggregate";
import { rerankRelatedRelationRows } from "../../papers/retrieval/related-ranker";

describe("relation-reader rerank integration", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(rerankRelatedRelationRows).mockImplementation(
      async (_paperId: string, _userId: string, rows: unknown[]) => rows as never,
    );
  });

  it("applies reranking to the final visible rows without mutating aggregate bookkeeping", async () => {
    prismaMock.paper.findFirst
      .mockResolvedValueOnce({
        id: "paper-1",
        entityId: "entity-1",
      })
      .mockResolvedValueOnce({
        id: "paper-2",
        entityId: "entity-2",
        title: "Aggregate peer",
        year: 2024,
        authors: null,
        duplicateState: "ACTIVE",
      });

    vi.mocked(getAggregatedRelationsForPaper).mockResolvedValue([
      {
        peerEntityId: "entity-2",
        relationType: "related",
        description: "aggregate",
        maxConfidence: 0.9,
        provenances: ["deterministic_relatedness"],
      },
    ] as never);

    prismaMock.paperRelation.findMany
      .mockResolvedValueOnce([
        {
          id: "rel-overlay",
          relationType: "related",
          description: "legacy-only peer",
          confidence: 0.4,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-3",
            entityId: null,
            title: "Overlay peer",
            year: 2023,
            authors: null,
            duplicateState: "ACTIVE",
          },
        },
      ])
      .mockResolvedValueOnce([]);

    vi.mocked(rerankRelatedRelationRows).mockResolvedValue([
      {
        id: "rel-overlay",
        relatedPaper: {
          id: "paper-3",
          entityId: null,
          title: "Overlay peer",
          year: 2023,
          authors: null,
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "legacy-only peer",
        confidence: 0.4,
        isAutoGenerated: true,
      },
      {
        id: "agg::entity-2::related",
        relatedPaper: {
          id: "paper-2",
          entityId: "entity-2",
          title: "Aggregate peer",
          year: 2024,
          authors: null,
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "aggregate",
        confidence: 0.9,
        isAutoGenerated: true,
      },
    ] as never);

    const result = await listRelationsForPaper("paper-1", "user-1");

    expect(result.mode).toBe("aggregate_with_overlay");
    expect(result.aggregateRows.map((row) => row.id)).toEqual([
      "agg::entity-2::related",
    ]);
    expect(result.overlayRows.map((row) => row.id)).toEqual(["rel-overlay"]);
    expect(result.rows.map((row) => row.id)).toEqual([
      "rel-overlay",
      "agg::entity-2::related",
    ]);
    expect(rerankRelatedRelationRows).toHaveBeenCalledTimes(1);
  });

  it("uses the shared relation-reader path for projected target ids when a user-bound paper exists", async () => {
    prismaMock.paper.findUnique.mockResolvedValueOnce({
      userId: "user-1",
    });
    prismaMock.paper.findFirst.mockResolvedValueOnce({
      id: "paper-1",
      entityId: null,
    });
    prismaMock.paperRelation.findMany
      .mockResolvedValueOnce([
        {
          id: "rel-1",
          relationType: "related",
          description: null,
          confidence: 0.8,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-2",
            entityId: null,
            title: "Primary peer",
            year: 2024,
            authors: null,
            duplicateState: "ACTIVE",
          },
        },
        {
          id: "rel-2",
          relationType: "cites",
          description: null,
          confidence: 0.7,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-3",
            entityId: null,
            title: "Citation peer",
            year: 2024,
            authors: null,
            duplicateState: "ACTIVE",
          },
        },
        {
          id: "rel-3",
          relationType: "extends",
          description: null,
          confidence: 0.6,
          isAutoGenerated: true,
          targetPaper: {
            id: "paper-4",
            entityId: null,
            title: "Extension peer",
            year: 2024,
            authors: null,
            duplicateState: "ACTIVE",
          },
        },
      ])
      .mockResolvedValueOnce([]);

    const ids = await listProjectedTargetPaperIds("paper-1", {
      excludeRelationTypes: ["cites"],
      limit: 2,
    });

    expect(ids).toEqual(["paper-2", "paper-4"]);
    expect(prismaMock.paper.findUnique).toHaveBeenCalledTimes(1);
  });
});
