import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

const createTagSchema = z.object({
  name: z.string().min(1),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#6B7280"),
  isAutoGenerated: z.boolean().default(false),
});

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const groupByCluster = searchParams.get("groupByCluster") === "true";

  if (groupByCluster) {
    const clusters = await prisma.tagCluster.findMany({
      orderBy: { sortOrder: "asc" },
      include: {
        tags: {
          orderBy: { score: "desc" },
          include: { _count: { select: { papers: true } } },
        },
      },
    });
    // Also get unclustered tags
    const unclustered = await prisma.tag.findMany({
      where: { clusterId: null },
      orderBy: { score: "desc" },
      include: { _count: { select: { papers: true } } },
    });
    return NextResponse.json({ clusters, unclustered });
  }

  const tags = await prisma.tag.findMany({
    orderBy: { score: "desc" },
    include: {
      _count: { select: { papers: true } },
      cluster: { select: { id: true, name: true, color: true } },
    },
  });
  return NextResponse.json(tags);
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const data = createTagSchema.parse(body);

    const tag = await prisma.tag.create({ data });
    return NextResponse.json(tag, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation error", details: error.issues },
        { status: 400 }
      );
    }
    console.error("Create tag error:", error);
    return NextResponse.json(
      { error: "Failed to create tag" },
      { status: 500 }
    );
  }
}
