import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { processingQueue } from "@/lib/processing/queue";
import { requireUserId } from "@/lib/paper-auth";
import { clearAutoGeneratedRelationsForPaper } from "@/lib/assertions/graph-relations";

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const userId = await requireUserId();
    const { id } = await params;

  const paper = await prisma.paper.findFirst({ where: { id, userId } });
  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  if (!paper.fullText && !paper.abstract) {
    return NextResponse.json(
      { error: "No text available to process" },
      { status: 400 }
    );
  }

  // Clear stale analysis data and reset status
  await prisma.paper.update({
    where: { id },
    data: {
      processingStatus: "TEXT_EXTRACTED",
      processingStep: null,
      processingStartedAt: null,
      summary: null,
      keyFindings: null,
      categories: null,
    },
  });

  // Delete auto-generated tags for this paper
  const autoTagLinks = await prisma.paperTag.findMany({
    where: { paperId: id, tag: { isAutoGenerated: true } },
    select: { id: true },
  });
  if (autoTagLinks.length > 0) {
    await prisma.paperTag.deleteMany({
      where: { id: { in: autoTagLinks.map((t) => t.id) } },
    });
  }

  await clearAutoGeneratedRelationsForPaper(id);

  processingQueue.enqueue(id);

  return NextResponse.json({ success: true, message: "Reprocessing started" });
}
