import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { processingQueue } from "@/lib/processing/queue";
import { paperAccessErrorToResponse, requirePaperAccess } from "@/lib/paper-auth";
import { clearAutoGeneratedRelationsForPaper } from "@/lib/assertions/graph-relations";
import { setProcessingProjection } from "@/lib/processing/runtime-ledger";

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const access = await requirePaperAccess(id, { mode: "mutate" });
    if (!access) {
      return NextResponse.json({ error: "Paper not found" }, { status: 404 });
    }
    const paper = access.paper;

    if (!paper.fullText && !paper.abstract) {
      return NextResponse.json(
        { error: "No text available to process" },
        { status: 400 }
      );
    }

    await prisma.$transaction(async (tx) => {
      await tx.paper.update({
        where: { id },
        data: {
          summary: null,
          keyFindings: null,
          categories: null,
        },
      });
      await setProcessingProjection(
        id,
        {
          processingStatus: "TEXT_EXTRACTED",
          processingStep: null,
          processingStartedAt: null,
        },
        tx,
      );
    });

    const autoTagLinks = await prisma.paperTag.findMany({
      where: { paperId: id, tag: { isAutoGenerated: true } },
      select: { id: true },
    });
    if (autoTagLinks.length > 0) {
      await prisma.paperTag.deleteMany({
        where: { id: { in: autoTagLinks.map((t) => t.id) } },
      });
    }

    await clearAutoGeneratedRelationsForPaper(id);

    processingQueue.enqueue(id);

    return NextResponse.json({ success: true, message: "Reprocessing started" });
  } catch (error) {
    const response = paperAccessErrorToResponse(error);
    if (response) return response;
    throw error;
  }
}
