import { prisma } from "../../prisma";
import {
  listRelationsForPaper,
  type GraphRelationRow,
} from "../../assertions/relation-reader";

import {
  searchSharedPaperRepresentationsByPaper,
  searchSharedPaperRepresentationsByProfile,
  searchSharedPaperRepresentationsByQuery,
  type PaperRepresentationMatch,
} from "./embeddings";

export interface RetrievalCandidate {
  paperId: string;
  title: string;
  source: "graph" | "content";
  score: number;
  relationType?: string | null;
  description?: string | null;
  signals: Record<string, number | string | null>;
}

export interface RelatedCandidateResult {
  graphCandidates: RetrievalCandidate[];
  contentCandidates: RetrievalCandidate[];
  mergedCandidates: RetrievalCandidate[];
}

function toGraphCandidate(row: GraphRelationRow): RetrievalCandidate {
  return {
    paperId: row.relatedPaper.id,
    title: row.relatedPaper.title,
    source: "graph",
    score: row.confidence,
    relationType: row.relationType,
    description: row.description,
    signals: {
      confidence: row.confidence,
      relationType: row.relationType,
      isAutoGenerated: row.isAutoGenerated ? 1 : 0,
    },
  };
}

function toContentCandidate(row: PaperRepresentationMatch): RetrievalCandidate {
  return {
    paperId: row.paperId,
    title: row.title,
    source: "content",
    score: row.score,
    relationType: null,
    description: null,
    signals: {
      semanticSimilarity: row.score,
      representationKind: row.representationKind,
      encoderVersion: row.encoderVersion,
    },
  };
}

function mergeCandidates(
  graphCandidates: RetrievalCandidate[],
  contentCandidates: RetrievalCandidate[],
  limit: number,
): RetrievalCandidate[] {
  const merged = new Map<string, RetrievalCandidate>();

  for (const candidate of [...graphCandidates, ...contentCandidates]) {
    const existing = merged.get(candidate.paperId);
    if (!existing) {
      merged.set(candidate.paperId, candidate);
      continue;
    }

    const mergedScore = Math.max(existing.score, candidate.score);
    const winningSource =
      existing.score >= candidate.score ? existing.source : candidate.source;
    merged.set(candidate.paperId, {
      ...existing,
      source: winningSource,
      score: mergedScore,
      relationType: existing.relationType ?? candidate.relationType ?? null,
      description: existing.description ?? candidate.description ?? null,
      signals: {
        ...existing.signals,
        ...candidate.signals,
        graphScore:
          existing.source === "graph"
            ? existing.score
            : candidate.source === "graph"
              ? candidate.score
              : null,
        contentScore:
          existing.source === "content"
            ? existing.score
            : candidate.source === "content"
              ? candidate.score
              : null,
      },
    });
  }

  return Array.from(merged.values())
    .sort((left, right) => {
      if (right.score !== left.score) return right.score - left.score;
      return left.paperId.localeCompare(right.paperId);
    })
    .slice(0, limit);
}

export async function generateRelatedPaperCandidates(
  params: {
    paperId: string;
    userId: string;
    graphLimit?: number;
    contentLimit?: number;
    mergedLimit?: number;
  },
  db: Pick<typeof prisma, "paper" | "paperRelation" | "relationAssertion" | "paperRepresentation"> = prisma,
): Promise<RelatedCandidateResult> {
  const graphResult = await listRelationsForPaper(params.paperId, params.userId, db);
  const graphCandidates = graphResult.rows
    .slice(0, params.graphLimit ?? 50)
    .map(toGraphCandidate);

  const contentCandidates = (
    await searchSharedPaperRepresentationsByPaper(
      {
        userId: params.userId,
        paperId: params.paperId,
        limit: params.contentLimit ?? 200,
      },
      db,
    )
  ).map(toContentCandidate);

  return {
    graphCandidates,
    contentCandidates,
    mergedCandidates: mergeCandidates(
      graphCandidates,
      contentCandidates,
      params.mergedLimit ?? 200,
    ),
  };
}

export async function generateSearchContentCandidates(
  params: {
    userId: string;
    queryText: string;
    limit?: number;
    excludePaperIds?: string[];
  },
  db: Pick<typeof prisma, "paper" | "paperRepresentation"> = prisma,
): Promise<RetrievalCandidate[]> {
  return (
    await searchSharedPaperRepresentationsByQuery(
      {
        userId: params.userId,
        queryText: params.queryText,
        limit: params.limit,
        excludePaperIds: params.excludePaperIds,
      },
      db,
    )
  ).map(toContentCandidate);
}

export async function generateRecommendationProfileCandidates(
  params: {
    userId: string;
    paperIds: string[];
    limit?: number;
  },
  db: Pick<typeof prisma, "paper" | "paperRepresentation"> = prisma,
): Promise<RetrievalCandidate[]> {
  return (
    await searchSharedPaperRepresentationsByProfile(
      {
        userId: params.userId,
        paperIds: params.paperIds,
        limit: params.limit,
      },
      db,
    )
  ).map(toContentCandidate);
}
