import { describe, expect, it } from "vitest";

import type { GraphRelationRow } from "../../assertions/relation-reader";
import { buildRelatedRerankResult } from "./related-ranker";

interface MockPaperRow {
  id: string;
  userId: string;
  entityId: string;
  title: string;
  abstract: string | null;
  summary: string | null;
  authors: string;
  year: number;
  venue: string | null;
  citationCount: number;
  duplicateState: string;
  _count: {
    sourceRelations: number;
    targetRelations: number;
  };
}

function createRepresentationRow(
  paperId: string,
  vector: number[],
  tagNames: string[] = [],
) {
  return {
    paperId,
    representationKind: "shared_raw_features_v1",
    encoderVersion: "feature_hash_256_v1",
    sourceFingerprint: `fingerprint-${paperId}`,
    dimensions: vector.length,
    featureText: tagNames.join(" "),
    vectorJson: JSON.stringify(vector),
    metadataJson: JSON.stringify({
      title: paperId,
      authorNames: [],
      tagNames,
      claimCount: 0,
      sections: ["title", "abstract"],
    }),
  };
}

describe("related-ranker", () => {
  it("filters hub-paper topic drift that is only supported by weak generic similarity", async () => {
    const papers = new Map([
      [
        "seed",
        {
          id: "seed",
          userId: "user-1",
          entityId: "entity-seed",
          title: "Attention Is All You Need",
          abstract:
            "We propose the Transformer, a sequence transduction architecture based solely on attention mechanisms.",
          summary: null,
          authors: JSON.stringify(["Ashish Vaswani"]),
          year: 2017,
          venue: "NeurIPS",
          citationCount: 5000,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 2,
            targetRelations: 0,
          },
        },
      ],
      [
        "generic",
        {
          id: "generic",
          userId: "user-1",
          entityId: "entity-generic",
          title:
            "Boundary-aware Diffusion for Shadow Generation in Synthetic Scenes",
          abstract: null,
          summary: null,
          authors: JSON.stringify(["Vision Author"]),
          year: 2024,
          venue: null,
          citationCount: 180,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 1,
          },
        },
      ],
      [
        "relevant",
        {
          id: "relevant",
          userId: "user-1",
          entityId: "entity-relevant",
          title:
            "LongNet: Scaling Transformers to 1,000,000,000 Tokens",
          abstract: null,
          summary: null,
          authors: JSON.stringify(["Example Author"]),
          year: 2024,
          venue: null,
          citationCount: 80,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 1,
          },
        },
      ],
    ]);

    const representations = new Map([
      ["seed", createRepresentationRow("seed", [1, 0, 0], ["transformer", "attention"])],
      ["generic", createRepresentationRow("generic", [0.96, 0.04, 0], ["diffusion", "vision"])],
      ["relevant", createRepresentationRow("relevant", [0.91, 0.09, 0], ["transformer", "long context"])],
    ]);

    const relationRows: GraphRelationRow[] = [
      {
        id: "rel-generic",
        relatedPaper: {
          id: "generic",
          entityId: "entity-generic",
          title:
            "Boundary-aware Diffusion for Shadow Generation in Synthetic Scenes",
          year: 2024,
          authors: JSON.stringify(["Vision Author"]),
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "Related via generic semantic similarity.",
        confidence: 0.5,
        isAutoGenerated: true,
      },
      {
        id: "rel-relevant",
        relatedPaper: {
          id: "relevant",
          entityId: "entity-relevant",
          title: "LongNet: Scaling Transformers to 1,000,000,000 Tokens",
          year: 2023,
          authors: JSON.stringify(["Example Author"]),
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "Related via a direct citation and bibliographic coupling.",
        confidence: 0.42,
        isAutoGenerated: true,
      },
    ];

    const db = {
      paper: {
        findUnique: async ({ where }: { where: { id: string } }) =>
          papers.get(where.id) ?? null,
        findMany: async ({
          where,
          take,
        }: {
          where: {
            id?: { in?: string[]; not?: string; notIn?: string[] };
            userId?: string;
            duplicateState?: string;
            OR?: Array<{ title: { contains: string } }>;
            representations?: unknown;
          };
          take?: number;
        }) => {
          const allPapers = Array.from(papers.values());
          if (where.id?.in) {
            return allPapers.filter((paper) => where.id?.in?.includes(paper.id));
          }

          return allPapers
            .filter((paper) => paper.userId === where.userId)
            .filter((paper) => paper.duplicateState === where.duplicateState)
            .filter((paper) =>
              where.id?.not ? paper.id !== where.id.not : true,
            )
            .filter((paper) =>
              where.id?.notIn ? !where.id.notIn.includes(paper.id) : true,
            )
            .filter((paper) => {
              if (where.OR?.length) {
                return where.OR.some((clause) =>
                  paper.title.toLowerCase().includes(clause.title.contains.toLowerCase()),
                );
              }
              if (where.representations) {
                return representations.has(paper.id);
              }
              return true;
            })
            .map((paper) => ({
              ...paper,
              representations: representations.has(paper.id)
                ? [representations.get(paper.id)]
                : [],
            }))
            .slice(0, take ?? allPapers.length);
        },
      },
      paperRepresentation: {
        findUnique: async ({
          where,
        }: {
          where: { paperId_representationKind: { paperId: string } };
        }) => representations.get(where.paperId_representationKind.paperId) ?? null,
        findMany: async ({
          where,
        }: {
          where: { paperId?: { in?: string[] } };
        }) =>
          Array.from(representations.values()).filter((row) =>
            where.paperId?.in ? where.paperId.in.includes(row.paperId) : true,
          ),
        upsert: async () => {
          throw new Error("upsert should not be called in this test");
        },
      },
      paperRelation: {
        findMany: async () => [
          { sourcePaperId: "seed", targetPaperId: "generic" },
          { sourcePaperId: "seed", targetPaperId: "relevant" },
        ],
      },
      relationAssertion: {
        findMany: async () => [
          {
            targetEntityId: "entity-relevant",
            evidence: [
              {
                type: "deterministic_signal:direct_citation",
                excerpt: JSON.stringify({
                  rawValue: 1,
                  weight: 0.08,
                  contribution: 0.08,
                }),
              },
              {
                type: "deterministic_signal:bibliographic_coupling",
                excerpt: JSON.stringify({
                  rawValue: 0.76,
                  weight: 0.05,
                  contribution: 0.076,
                }),
              },
            ],
          },
        ],
      },
    };

    const result = await buildRelatedRerankResult(
      "seed",
      "user-1",
      relationRows,
      db as never,
    );

    expect(result.backend).toEqual({
      id: "feature_v1",
      family: "feature-ranker",
    });
    expect(result.baselineRows.map((row) => row.relatedPaper.id)).toEqual([
      "generic",
      "relevant",
    ]);
    expect(result.rerankedRows.map((row) => row.relatedPaper.id)).toEqual([
      "relevant",
    ]);
  });

  it("supports a baseline backend for judged comparisons and degraded fallback", async () => {
    const relationRows: GraphRelationRow[] = [
      {
        id: "rel-b",
        relatedPaper: {
          id: "paper-b",
          entityId: null,
          title: "Paper B",
          year: 2024,
          authors: null,
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: null,
        confidence: 0.4,
        isAutoGenerated: true,
      },
      {
        id: "rel-a",
        relatedPaper: {
          id: "paper-a",
          entityId: null,
          title: "Paper A",
          year: 2023,
          authors: null,
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: null,
        confidence: 0.8,
        isAutoGenerated: true,
      },
    ];

    const result = await buildRelatedRerankResult(
      "seed",
      "user-1",
      relationRows,
      undefined as never,
      { backendId: "baseline_v1" },
    );

    expect(result.backend).toEqual({
      id: "baseline_v1",
      family: "baseline",
    });
    expect(result.baselineRows.map((row) => row.relatedPaper.id)).toEqual([
      "paper-a",
      "paper-b",
    ]);
    expect(result.rerankedRows.map((row) => row.relatedPaper.id)).toEqual([
      "paper-a",
      "paper-b",
    ]);
  });

  it("fails closed when only broad body-level similarity exists", async () => {
    const papers = new Map<string, MockPaperRow>([
      [
        "seed",
        {
          id: "seed",
          userId: "user-1",
          entityId: "entity-seed",
          title:
            "Phi-3 Technical Report: A Highly Capable Language Model Locally on Your Phone",
          abstract: "Small language model tuned for phone and local usage.",
          summary: null,
          authors: JSON.stringify(["Example Author"]),
          year: 2024,
          venue: null,
          citationCount: 20,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 0,
          },
        },
      ] as const,
      ...["cand-a", "cand-b", "cand-c"].map((id, index) => [
        id,
        {
          id,
          userId: "user-1",
          entityId: `entity-${id}`,
          title: `Generic candidate ${index + 1}`,
          abstract:
            "This work discusses running models locally on a phone with efficient deployment.",
          summary: null,
          authors: JSON.stringify([`Author ${index + 1}`]),
          year: 2024,
          venue: null,
          citationCount: 0,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 0,
          },
        },
      ] as const),
    ]);

    const representations = new Map([
      ["seed", createRepresentationRow("seed", [1, 0, 0], [])],
      ["cand-a", createRepresentationRow("cand-a", [0.72, 0.28, 0], [])],
      ["cand-b", createRepresentationRow("cand-b", [0.7, 0.3, 0], [])],
      ["cand-c", createRepresentationRow("cand-c", [0.68, 0.32, 0], [])],
    ]);

    const relationRows: GraphRelationRow[] = ["cand-a", "cand-b", "cand-c"].map(
      (paperId, index) => ({
        id: `rel-${paperId}`,
        relatedPaper: {
          id: paperId,
          entityId: `entity-${paperId}`,
          title: `Generic candidate ${index + 1}`,
          year: 2024,
          authors: JSON.stringify([`Author ${index + 1}`]),
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: null,
        confidence: 0.34 - index * 0.01,
        isAutoGenerated: true,
      }),
    );

    const db = {
      paper: {
        findUnique: async ({ where }: { where: { id: string } }) =>
          papers.get(where.id) ?? null,
        findMany: async ({
          where,
          take,
        }: {
          where: {
            id?: { in?: string[]; not?: string; notIn?: string[] };
            userId?: string;
            duplicateState?: string;
            OR?: Array<
              | { title: { contains: string } }
              | { abstract: { contains: string } }
              | { summary: { contains: string } }
              | { tags: { some: { tag: { name: { contains: string } } } } }
            >;
            representations?: unknown;
          };
          take?: number;
        }) => {
          const allPapers = Array.from(papers.values()) as MockPaperRow[];
          if (where.id?.in) {
            return allPapers.filter((paper) => where.id?.in?.includes(paper.id));
          }

          return allPapers
            .filter((paper) => (where.userId ? paper.userId === where.userId : true))
            .filter((paper) =>
              where.duplicateState ? paper.duplicateState === where.duplicateState : true,
            )
            .filter((paper) =>
              where.id?.not ? paper.id !== where.id.not : true,
            )
            .filter((paper) =>
              where.id?.notIn ? !where.id.notIn.includes(paper.id) : true,
            )
            .filter((paper) => {
              if (where.OR?.length) {
                return where.OR.some((clause) => {
                  if ("title" in clause) {
                    return paper.title
                      .toLowerCase()
                      .includes(clause.title.contains.toLowerCase());
                  }
                  if ("abstract" in clause) {
                    return (paper.abstract ?? "")
                      .toLowerCase()
                      .includes(clause.abstract.contains.toLowerCase());
                  }
                  if ("summary" in clause) {
                    return (paper.summary ?? "")
                      .toLowerCase()
                      .includes(clause.summary.contains.toLowerCase());
                  }
                  return false;
                });
              }
              if (where.representations) {
                return representations.has(paper.id);
              }
              return true;
            })
            .map((paper) => ({
              ...paper,
              representations: representations.has(paper.id)
                ? [representations.get(paper.id)]
                : [],
            }))
            .slice(0, take ?? allPapers.length);
        },
      },
      paperRepresentation: {
        findUnique: async ({
          where,
        }: {
          where: { paperId_representationKind: { paperId: string } };
        }) => representations.get(where.paperId_representationKind.paperId) ?? null,
        findMany: async ({
          where,
        }: {
          where: { paperId?: { in?: string[] } };
        }) =>
          Array.from(representations.values()).filter((row) =>
            where.paperId?.in ? where.paperId.in.includes(row.paperId) : true,
          ),
        upsert: async () => {
          throw new Error("upsert should not be called in this test");
        },
      },
      paperRelation: {
        findMany: async () => [],
      },
      relationAssertion: {
        findMany: async () => [],
      },
    };

    const result = await buildRelatedRerankResult(
      "seed",
      "user-1",
      relationRows,
      db as never,
    );

    expect(result.rerankedRows).toHaveLength(2);
    expect(result.rerankedRows.map((row) => row.relatedPaper.id)).toEqual([
      "cand-a",
      "cand-b",
    ]);
  });
});
