import { describe, expect, it } from "vitest";

import type { GraphRelationRow } from "../../assertions/relation-reader";
import { buildRelatedRerankResult } from "./related-ranker";

function createRepresentationRow(
  paperId: string,
  vector: number[],
  tagNames: string[] = [],
) {
  return {
    paperId,
    representationKind: "shared_raw_features_v1",
    encoderVersion: "feature_hash_256_v1",
    sourceFingerprint: `fingerprint-${paperId}`,
    dimensions: vector.length,
    featureText: tagNames.join(" "),
    vectorJson: JSON.stringify(vector),
    metadataJson: JSON.stringify({
      title: paperId,
      authorNames: [],
      tagNames,
      claimCount: 0,
      sections: ["title", "abstract"],
    }),
  };
}

describe("related-ranker", () => {
  it("filters hub-paper topic drift that is only supported by weak generic similarity", async () => {
    const papers = new Map([
      [
        "seed",
        {
          id: "seed",
          userId: "user-1",
          entityId: "entity-seed",
          title: "Attention Is All You Need",
          abstract:
            "We propose the Transformer, a sequence transduction architecture based solely on attention mechanisms.",
          summary: null,
          authors: JSON.stringify(["Ashish Vaswani"]),
          year: 2017,
          venue: "NeurIPS",
          citationCount: 5000,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 2,
            targetRelations: 0,
          },
        },
      ],
      [
        "generic",
        {
          id: "generic",
          userId: "user-1",
          entityId: "entity-generic",
          title:
            "Boundary-aware Diffusion for Shadow Generation in Synthetic Scenes",
          abstract: null,
          summary: null,
          authors: JSON.stringify(["Vision Author"]),
          year: 2024,
          venue: null,
          citationCount: 180,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 1,
          },
        },
      ],
      [
        "relevant",
        {
          id: "relevant",
          userId: "user-1",
          entityId: "entity-relevant",
          title:
            "LongNet: Scaling Transformers to 1,000,000,000 Tokens",
          abstract: null,
          summary: null,
          authors: JSON.stringify(["Example Author"]),
          year: 2024,
          venue: null,
          citationCount: 80,
          duplicateState: "ACTIVE",
          _count: {
            sourceRelations: 0,
            targetRelations: 1,
          },
        },
      ],
    ]);

    const representations = new Map([
      ["seed", createRepresentationRow("seed", [1, 0, 0], ["transformer", "attention"])],
      ["generic", createRepresentationRow("generic", [0.96, 0.04, 0], ["diffusion", "vision"])],
      ["relevant", createRepresentationRow("relevant", [0.91, 0.09, 0], ["transformer", "long context"])],
    ]);

    const relationRows: GraphRelationRow[] = [
      {
        id: "rel-generic",
        relatedPaper: {
          id: "generic",
          entityId: "entity-generic",
          title:
            "Boundary-aware Diffusion for Shadow Generation in Synthetic Scenes",
          year: 2024,
          authors: JSON.stringify(["Vision Author"]),
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "Related via generic semantic similarity.",
        confidence: 0.5,
        isAutoGenerated: true,
      },
      {
        id: "rel-relevant",
        relatedPaper: {
          id: "relevant",
          entityId: "entity-relevant",
          title: "LongNet: Scaling Transformers to 1,000,000,000 Tokens",
          year: 2023,
          authors: JSON.stringify(["Example Author"]),
          duplicateState: "ACTIVE",
        },
        relationType: "related",
        description: "Related via a direct citation and bibliographic coupling.",
        confidence: 0.42,
        isAutoGenerated: true,
      },
    ];

    const db = {
      paper: {
        findUnique: async ({ where }: { where: { id: string } }) =>
          papers.get(where.id) ?? null,
        findMany: async ({
          where,
          take,
        }: {
          where: {
            id?: { in?: string[]; not?: string; notIn?: string[] };
            userId?: string;
            duplicateState?: string;
            OR?: Array<{ title: { contains: string } }>;
            representations?: unknown;
          };
          take?: number;
        }) => {
          const allPapers = Array.from(papers.values());
          if (where.id?.in) {
            return allPapers.filter((paper) => where.id?.in?.includes(paper.id));
          }

          return allPapers
            .filter((paper) => paper.userId === where.userId)
            .filter((paper) => paper.duplicateState === where.duplicateState)
            .filter((paper) =>
              where.id?.not ? paper.id !== where.id.not : true,
            )
            .filter((paper) =>
              where.id?.notIn ? !where.id.notIn.includes(paper.id) : true,
            )
            .filter((paper) => {
              if (where.OR?.length) {
                return where.OR.some((clause) =>
                  paper.title.toLowerCase().includes(clause.title.contains.toLowerCase()),
                );
              }
              if (where.representations) {
                return representations.has(paper.id);
              }
              return true;
            })
            .map((paper) => ({
              ...paper,
              representations: representations.has(paper.id)
                ? [representations.get(paper.id)]
                : [],
            }))
            .slice(0, take ?? allPapers.length);
        },
      },
      paperRepresentation: {
        findUnique: async ({
          where,
        }: {
          where: { paperId_representationKind: { paperId: string } };
        }) => representations.get(where.paperId_representationKind.paperId) ?? null,
        findMany: async ({
          where,
        }: {
          where: { paperId?: { in?: string[] } };
        }) =>
          Array.from(representations.values()).filter((row) =>
            where.paperId?.in ? where.paperId.in.includes(row.paperId) : true,
          ),
        upsert: async () => {
          throw new Error("upsert should not be called in this test");
        },
      },
      paperRelation: {
        findMany: async () => [
          { sourcePaperId: "seed", targetPaperId: "generic" },
          { sourcePaperId: "seed", targetPaperId: "relevant" },
        ],
      },
      relationAssertion: {
        findMany: async () => [
          {
            targetEntityId: "entity-relevant",
            evidence: [
              {
                type: "deterministic_signal:direct_citation",
                excerpt: JSON.stringify({
                  rawValue: 1,
                  weight: 0.08,
                  contribution: 0.08,
                }),
              },
              {
                type: "deterministic_signal:bibliographic_coupling",
                excerpt: JSON.stringify({
                  rawValue: 0.76,
                  weight: 0.05,
                  contribution: 0.076,
                }),
              },
            ],
          },
        ],
      },
    };

    const result = await buildRelatedRerankResult(
      "seed",
      "user-1",
      relationRows,
      db as never,
    );

    expect(result.baselineRows.map((row) => row.relatedPaper.id)).toEqual([
      "generic",
      "relevant",
    ]);
    expect(result.rerankedRows.map((row) => row.relatedPaper.id)).toEqual([
      "relevant",
    ]);
  });
});
