import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { cleanJsonResponse } from "@/lib/llm/prompts";
import { resolveAndAssignTags } from "@/lib/tags/auto-tag";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const { promptResultId } = await request.json();

  if (!promptResultId) {
    return NextResponse.json(
      { error: "promptResultId is required" },
      { status: 400 }
    );
  }

  const promptResult = await prisma.promptResult.findUnique({
    where: { id: promptResultId },
  });

  if (!promptResult || promptResult.paperId !== id) {
    return NextResponse.json(
      { error: "PromptResult not found for this paper" },
      { status: 404 }
    );
  }

  try {
    switch (promptResult.promptType) {
      case "summarize": {
        await prisma.paper.update({
          where: { id },
          data: { summary: promptResult.result },
        });
        break;
      }

      case "extract": {
        const cleaned = cleanJsonResponse(promptResult.result);
        const parsed = JSON.parse(cleaned);
        const updateData: Record<string, unknown> = {};
        if (parsed.title) updateData.title = parsed.title;
        if (parsed.authors) updateData.authors = JSON.stringify(parsed.authors);
        if (parsed.year) updateData.year = parsed.year;
        if (parsed.venue) updateData.venue = parsed.venue;
        if (parsed.abstract) updateData.abstract = parsed.abstract;
        if (parsed.keyFindings)
          updateData.keyFindings = JSON.stringify(parsed.keyFindings);

        if (Object.keys(updateData).length > 0) {
          await prisma.paper.update({ where: { id }, data: updateData });
        }
        break;
      }

      case "categorize": {
        const cleaned = cleanJsonResponse(promptResult.result);
        const parsed = JSON.parse(cleaned);
        const tagNames = (parsed.tags || []) as string[];

        // Remove existing auto-generated tags for this paper
        const autoTagLinks = await prisma.paperTag.findMany({
          where: { paperId: id, tag: { isAutoGenerated: true } },
          select: { id: true },
        });
        if (autoTagLinks.length > 0) {
          await prisma.paperTag.deleteMany({
            where: { id: { in: autoTagLinks.map((t) => t.id) } },
          });
        }

        // Re-assign tags from the restored result
        await resolveAndAssignTags(id, tagNames);
        break;
      }

      default:
        return NextResponse.json(
          { error: `Cannot restore promptType: ${promptResult.promptType}` },
          { status: 400 }
        );
    }

    // Return updated paper
    const paper = await prisma.paper.findUnique({
      where: { id },
      include: {
        tags: { include: { tag: true } },
        promptResults: { orderBy: { createdAt: "desc" } },
      },
    });

    return NextResponse.json(paper);
  } catch (error) {
    console.error("Restore failed:", error);
    return NextResponse.json(
      { error: "Failed to restore analysis version" },
      { status: 500 }
    );
  }
}
