import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { generateLLMResponse, truncateText } from "@/lib/llm/provider";
import {
  PAPER_INTERACTIVE_LLM_OPERATIONS,
  withPaperLlmContext,
} from "@/lib/llm/paper-llm-context";
import { buildPrompt, cleanJsonResponse } from "@/lib/llm/prompts";
import { resolveModelConfig, getDefaultModel } from "@/lib/llm/auto-process";
import { paperAccessErrorToResponse, requirePaperAccess } from "@/lib/paper-auth";
import { getUserContext, buildUserContextPreamble } from "@/lib/llm/user-context";
import { setProcessingProjection } from "@/lib/processing/runtime-ledger";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const access = await requirePaperAccess(id, { mode: "mutate" });
    if (!access) {
      return NextResponse.json({ error: "Paper not found" }, { status: 404 });
    }
    const body = await request.json();
    const { provider, modelId, proxyConfig } = await resolveModelConfig(body);
    const paper = access.paper;

    const text = paper.fullText || paper.abstract || "";
    if (!text) {
      return NextResponse.json(
        { error: "No text available for this paper" },
        { status: 400 }
      );
    }

    const truncated = truncateText(text, modelId, proxyConfig);
    const userCtx = await getUserContext(access.userId);
    const userContextPreamble = buildUserContextPreamble(userCtx);
    const { system, prompt } = buildPrompt("summarize", truncated, undefined, { userContextPreamble });

    const result = await withPaperLlmContext(
      {
        operation: PAPER_INTERACTIVE_LLM_OPERATIONS.SUMMARIZE,
        paperId: id,
        userId: access.userId,
        runtime: "interactive",
        source: "papers.llm.summarize",
      },
      () =>
        generateLLMResponse({
          provider,
          modelId,
          system,
          prompt,
          proxyConfig,
        }),
    );

    // Save result
    const promptResult = await prisma.promptResult.create({
      data: {
        paperId: id,
        promptType: "summarize",
        prompt: "Summarize this paper",
        result,
        provider,
        model: modelId,
      },
    });

    // Also update paper summary
    await prisma.$transaction(async (tx) => {
      await tx.paper.update({
        where: { id },
        data: { summary: result },
      });
      await setProcessingProjection(
        id,
        {
          processingStatus: "COMPLETED",
          processingStep: null,
          processingStartedAt: null,
        },
        tx,
      );
    });

    // Fire-and-forget: auto-categorize + tag after manual summarize
    getDefaultModel()
      .then(async ({ provider: autoProvider, modelId: autoModelId, proxyConfig: autoProxyConfig }) => {
        const autoTruncated = truncateText(
          paper.fullText || paper.abstract || "",
          autoModelId,
          autoProxyConfig
        );
        const { system: catSystem, prompt: catPrompt } = buildPrompt(
          "categorize",
          autoTruncated
        );
        const catResult = await withPaperLlmContext(
          {
            operation: PAPER_INTERACTIVE_LLM_OPERATIONS.CATEGORIZE,
            paperId: id,
            userId: access.userId,
            runtime: "interactive",
            source: "papers.llm.summarize.auto_categorize",
          },
          () =>
            generateLLMResponse({
              provider: autoProvider,
              modelId: autoModelId,
              system: catSystem,
              prompt: catPrompt,
              proxyConfig: autoProxyConfig,
            }),
        );

        await prisma.promptResult.create({
          data: {
            paperId: id,
            promptType: "categorize",
            prompt: "Auto-categorize after summarize",
            result: catResult,
            provider: autoProvider,
            model: autoModelId,
          },
        });

        // Auto-tag from result
        try {
          const parsed = JSON.parse(cleanJsonResponse(catResult));
          const tagNames = (parsed.tags || []) as string[];
          const colors = [
            "#EF4444", "#F59E0B", "#10B981", "#3B82F6",
            "#8B5CF6", "#EC4899", "#06B6D4",
          ];
          for (const name of tagNames.slice(0, 5)) {
            const tag = await prisma.tag.upsert({
              where: { name },
              create: {
                name,
                color: colors[Math.floor(Math.random() * colors.length)],
                isAutoGenerated: true,
              },
              update: {},
            });
            await prisma.paperTag
              .create({ data: { paperId: id, tagId: tag.id } })
              .catch(() => {});
          }
          if (tagNames.length > 0) {
            await prisma.paper.update({
              where: { id },
              data: { categories: JSON.stringify(tagNames) },
            });
          }
        } catch {
          // JSON parse failed
        }
      })
      .catch((e) => {
        console.error("[auto-categorize] Failed after summarize:", e);
      });

    return NextResponse.json(promptResult);
  } catch (error) {
    const response = paperAccessErrorToResponse(error);
    if (response) return response;
    console.error("Summarize error:", error);
    return NextResponse.json(
      { error: "Failed to generate summary" },
      { status: 500 }
    );
  }
}
