/**
 * Backfill RelationAssertion rows from legacy PaperRelation rows.
 *
 * Run: npx tsx src/lib/assertions/backfill-assertions.ts
 */
import { prisma } from "../prisma";
import { createRelationAssertion } from "./relation-assertion-service";

async function main() {
  const relations = await prisma.paperRelation.findMany({
    include: {
      sourcePaper: { select: { entityId: true } },
      targetPaper: { select: { entityId: true } },
    },
  });

  let created = 0;
  let skipped = 0;

  for (const relation of relations) {
    if (!relation.sourcePaper.entityId || !relation.targetPaper.entityId) {
      skipped++;
      continue;
    }

    await createRelationAssertion({
      sourceEntityId: relation.sourcePaper.entityId,
      targetEntityId: relation.targetPaper.entityId,
      sourcePaperId: relation.sourcePaperId,
      relationType: relation.relationType,
      description: relation.description,
      confidence: relation.confidence,
      provenance: relation.isAutoGenerated ? (relation.relationType === "cites" ? "reference_match" : "llm_semantic") : "user_manual",
      extractorVersion: "legacy_backfill_v1",
    });
    created++;
  }

  console.log(JSON.stringify({ created, skipped }, null, 2));
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
