import { prisma } from "../prisma";
import { comparePrioritizedRelationAssertions } from "./provenance";

export interface AssertionForProjection {
  id: string;
  relationType: string;
  confidence: number;
  provenance: string;
  description: string | null;
}

type LegacyProjectionDb = Pick<typeof prisma, "relationAssertion" | "paperRelation">;

export function pickWinningAssertion(
  assertions: AssertionForProjection[]
): AssertionForProjection | null {
  if (assertions.length === 0) return null;
  return assertions.reduce((best, current) =>
    comparePrioritizedRelationAssertions(best, current),
  );
}

export async function projectLegacyRelation(
  sourcePaperId: string,
  targetPaperId: string,
  _sourceEntityId: string,
  targetEntityId: string,
  db: LegacyProjectionDb = prisma
): Promise<void> {
  const assertions = await db.relationAssertion.findMany({
    where: { sourcePaperId, targetEntityId },
    select: {
      id: true,
      relationType: true,
      confidence: true,
      provenance: true,
      description: true,
    },
  });

  const existing = await db.paperRelation.findUnique({
    where: {
      sourcePaperId_targetPaperId: { sourcePaperId, targetPaperId },
    },
  });

  const winner = pickWinningAssertion(assertions);
  if (!winner) {
    if (existing) {
      await db.paperRelation.delete({ where: { id: existing.id } });
    }
    return;
  }

  if (existing) {
    await db.paperRelation.update({
      where: { id: existing.id },
      data: {
        relationType: winner.relationType,
        description: winner.description,
        confidence: winner.confidence,
        isAutoGenerated: winner.provenance !== "user_manual",
      },
    });
    return;
  }

  await db.paperRelation.create({
    data: {
      sourcePaperId,
      targetPaperId,
      relationType: winner.relationType,
      description: winner.description,
      confidence: winner.confidence,
      isAutoGenerated: winner.provenance !== "user_manual",
    },
  });
}
