import { prisma } from "../prisma";

const PROVENANCE_PRIORITY: Record<string, number> = {
  reference_match: 0,
  citation_analysis: 1,
  discovery: 2,
  llm_semantic: 3,
  user_manual: 4,
};

export interface AssertionForProjection {
  id: string;
  relationType: string;
  confidence: number;
  provenance: string;
  description: string | null;
}

export function pickWinningAssertion(
  assertions: AssertionForProjection[]
): AssertionForProjection | null {
  if (assertions.length === 0) return null;
  return assertions.reduce((best, current) => {
    const bestPriority = PROVENANCE_PRIORITY[best.provenance] ?? 0;
    const currentPriority = PROVENANCE_PRIORITY[current.provenance] ?? 0;
    if (currentPriority > bestPriority) return current;
    if (currentPriority === bestPriority && current.confidence > best.confidence) return current;
    return best;
  });
}

export async function projectLegacyRelation(
  sourcePaperId: string,
  targetPaperId: string,
  _sourceEntityId: string,
  targetEntityId: string,
  isAutoGenerated: boolean
): Promise<void> {
  const assertions = await prisma.relationAssertion.findMany({
    where: { sourcePaperId, targetEntityId },
    select: {
      id: true,
      relationType: true,
      confidence: true,
      provenance: true,
      description: true,
    },
  });

  const winner = pickWinningAssertion(assertions);
  if (!winner) return;

  const existing = await prisma.paperRelation.findUnique({
    where: {
      sourcePaperId_targetPaperId: { sourcePaperId, targetPaperId },
    },
  });

  if (existing) {
    await prisma.paperRelation.update({
      where: { id: existing.id },
      data: {
        relationType: winner.relationType,
        description: winner.description,
        confidence: winner.confidence,
        isAutoGenerated,
      },
    });
    return;
  }

  await prisma.paperRelation.create({
    data: {
      sourcePaperId,
      targetPaperId,
      relationType: winner.relationType,
      description: winner.description,
      confidence: winner.confidence,
      isAutoGenerated,
    },
  }).catch(() => {});
}
