import { prisma } from "../prisma";
import { getAggregatedRelationsForPaper } from "./relation-aggregate";
import { isUserVisiblePaper, paperVisibilityWhere } from "../papers/visibility";
import { rerankRelatedRelationRows } from "../papers/retrieval/related-ranker";

type RelationReaderDb = Pick<
  typeof prisma,
  "paper" | "paperRelation" | "relationAssertion" | "paperRepresentation"
>;
type ProjectedRelationDb = Pick<typeof prisma, "paperRelation"> &
  Partial<Pick<typeof prisma, "paper" | "relationAssertion" | "paperRepresentation">>;

export const GRAPH_RELATED_PAPER_SELECT = {
  id: true,
  entityId: true,
  title: true,
  year: true,
  authors: true,
  duplicateState: true,
} as const;

export interface GraphRelatedPaperSummary {
  id: string;
  entityId: string | null;
  title: string;
  year: number | null;
  authors: string | null;
  duplicateState?: string | null;
}

export interface GraphRelationRow {
  id: string;
  relatedPaper: GraphRelatedPaperSummary;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
}

export interface GraphRouteRelationRow {
  id: string;
  relatedPaper: Omit<GraphRelatedPaperSummary, "entityId">;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
}

export type GraphRelationReadMode =
  | "legacy_fallback"
  | "aggregate_only"
  | "aggregate_with_overlay";

export interface GraphRelationListResult {
  mode: GraphRelationReadMode;
  rows: GraphRelationRow[];
  aggregateRows: GraphRelationRow[];
  legacyRows: GraphRelationRow[];
  overlayRows: GraphRelationRow[];
}

export class GraphRelationError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code: string,
  ) {
    super(message);
    this.name = "GraphRelationError";
  }
}

export function parseAggregateKey(
  key: string,
): { peerEntityId: string; relationType: string } | null {
  if (!key.startsWith("agg::")) return null;
  const parts = key.split("::");
  if (parts.length !== 3) return null;
  return { peerEntityId: parts[1], relationType: parts[2] };
}

export function toRouteRelationRow(row: GraphRelationRow): GraphRouteRelationRow {
  const { entityId: _entityId, duplicateState: _duplicateState, ...relatedPaper } = row.relatedPaper;
  return {
    id: row.id,
    relatedPaper,
    relationType: row.relationType,
    description: row.description,
    confidence: row.confidence,
    isAutoGenerated: row.isAutoGenerated,
  };
}

function sortRelationRows(rows: GraphRelationRow[]): GraphRelationRow[] {
  return [...rows].sort((a, b) => b.confidence - a.confidence);
}

async function rerankGraphRows(
  paperId: string,
  userId: string,
  rows: GraphRelationRow[],
  db: RelationReaderDb,
): Promise<GraphRelationRow[]> {
  if (rows.length <= 1) return rows;
  return rerankRelatedRelationRows(paperId, userId, rows, db);
}

function mapAggregateRowToRelation(
  aggregate: {
    peerEntityId: string;
    relationType: string;
    description: string | null;
    maxConfidence: number;
    provenances: string[];
  },
  relatedPaper: GraphRelatedPaperSummary,
): GraphRelationRow {
  return {
    id: `agg::${aggregate.peerEntityId}::${aggregate.relationType}`,
    relatedPaper,
    relationType: aggregate.relationType,
    description: aggregate.description,
    confidence: aggregate.maxConfidence,
    isAutoGenerated: !aggregate.provenances.includes("user_manual"),
  };
}

function mapLegacySourceRelation(relation: {
  id: string;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
  targetPaper: GraphRelatedPaperSummary;
}): GraphRelationRow {
  return {
    id: relation.id,
    relatedPaper: relation.targetPaper,
    relationType: relation.relationType,
    description: relation.description,
    confidence: relation.confidence,
    isAutoGenerated: relation.isAutoGenerated,
  };
}

function mapLegacyTargetRelation(relation: {
  id: string;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
  sourcePaper: GraphRelatedPaperSummary;
}): GraphRelationRow {
  return {
    id: relation.id,
    relatedPaper: relation.sourcePaper,
    relationType: relation.relationType,
    description: relation.description,
    confidence: relation.confidence,
    isAutoGenerated: relation.isAutoGenerated,
  };
}

function isEquivalentAggregateRow(
  aggregateRow: GraphRelationRow,
  legacyRow: GraphRelationRow,
): boolean {
  if (aggregateRow.relationType !== legacyRow.relationType) {
    return false;
  }

  if (aggregateRow.relatedPaper.id === legacyRow.relatedPaper.id) {
    return true;
  }

  return (
    Boolean(legacyRow.relatedPaper.entityId) &&
    aggregateRow.relatedPaper.entityId === legacyRow.relatedPaper.entityId
  );
}

export async function listAggregatedRelationRowsForPaper(
  paperId: string,
  entityId: string,
  userId: string,
  db: RelationReaderDb = prisma,
): Promise<GraphRelationRow[]> {
  const aggregated = await getAggregatedRelationsForPaper(paperId, entityId, userId, db);
  const rows: GraphRelationRow[] = [];

  for (const aggregate of aggregated) {
    const localPaper = await db.paper.findFirst({
      where: {
        ...paperVisibilityWhere(userId),
        entityId: aggregate.peerEntityId,
      },
      select: GRAPH_RELATED_PAPER_SELECT,
    });

    if (!localPaper) continue;

    rows.push(
      mapAggregateRowToRelation(
        aggregate,
        localPaper as GraphRelatedPaperSummary,
      ),
    );
  }

  return sortRelationRows(rows);
}

export async function listLegacyVisibleRelationsForPaper(
  paperId: string,
  userId: string,
  db: ProjectedRelationDb = prisma,
): Promise<GraphRelationRow[]> {
  const [sourceRelations, targetRelations] = await Promise.all([
    db.paperRelation.findMany({
      where: { sourcePaperId: paperId },
      include: { targetPaper: { select: GRAPH_RELATED_PAPER_SELECT } },
    }),
    db.paperRelation.findMany({
      where: { targetPaperId: paperId },
      include: { sourcePaper: { select: GRAPH_RELATED_PAPER_SELECT } },
    }),
  ]);

  const seen = new Set<string>();
  const rows: GraphRelationRow[] = [];

  for (const relation of sourceRelations) {
    if (!isUserVisiblePaper(relation.targetPaper)) continue;
    if (seen.has(relation.targetPaper.id)) continue;
    seen.add(relation.targetPaper.id);
    rows.push(
      mapLegacySourceRelation({
        ...relation,
        targetPaper: relation.targetPaper as GraphRelatedPaperSummary,
      }),
    );
  }

  for (const relation of targetRelations) {
    if (!isUserVisiblePaper(relation.sourcePaper)) continue;
    if (seen.has(relation.sourcePaper.id)) continue;
    seen.add(relation.sourcePaper.id);
    rows.push(
      mapLegacyTargetRelation({
        ...relation,
        sourcePaper: relation.sourcePaper as GraphRelatedPaperSummary,
      }),
    );
  }

  return sortRelationRows(rows);
}

export async function countUserAuthoredRelationRowsForPaper(
  paperId: string,
  db: RelationReaderDb = prisma,
): Promise<number> {
  const [manualLegacyCount, manualAssertionCount] = await Promise.all([
    db.paperRelation.count({
      where: {
        isAutoGenerated: false,
        OR: [{ sourcePaperId: paperId }, { targetPaperId: paperId }],
      },
    }),
    db.relationAssertion.count({
      where: {
        sourcePaperId: paperId,
        provenance: "user_manual",
      },
    }),
  ]);

  return manualLegacyCount + manualAssertionCount;
}

export function buildLegacyOverlayRows(
  aggregateRows: GraphRelationRow[],
  legacyRows: GraphRelationRow[],
): GraphRelationRow[] {
  return legacyRows.filter(
    (legacyRow) =>
      !aggregateRows.some((aggregateRow) =>
        isEquivalentAggregateRow(aggregateRow, legacyRow),
      ),
  );
}

export async function listRelationsForPaper(
  paperId: string,
  userId: string,
  db: RelationReaderDb = prisma,
): Promise<GraphRelationListResult> {
  const paper = await db.paper.findFirst({
    where: { id: paperId, userId },
    select: { id: true, entityId: true },
  });

  if (!paper) {
    throw new GraphRelationError("Paper not found", 404, "paper_not_found");
  }

  const legacyRows = await listLegacyVisibleRelationsForPaper(paperId, userId, db);

  if (paper.entityId) {
    const aggregateRows = await listAggregatedRelationRowsForPaper(
      paperId,
      paper.entityId,
      userId,
      db,
    );
    if (aggregateRows.length > 0) {
      const overlayRows = buildLegacyOverlayRows(aggregateRows, legacyRows);
      const combinedRows = sortRelationRows([...aggregateRows, ...overlayRows]);
      const rerankedRows = await rerankGraphRows(
        paperId,
        userId,
        combinedRows,
        db,
      );
      if (overlayRows.length > 0) {
        return {
          mode: "aggregate_with_overlay",
          rows: rerankedRows,
          aggregateRows,
          legacyRows,
          overlayRows,
        };
      }

      return {
        mode: "aggregate_only",
        rows: rerankedRows,
        aggregateRows,
        legacyRows,
        overlayRows: [],
      };
    }
  }

  const rerankedLegacyRows = await rerankGraphRows(paperId, userId, legacyRows, db);
  return {
    mode: "legacy_fallback",
    rows: rerankedLegacyRows,
    aggregateRows: [],
    legacyRows,
    overlayRows: [],
  };
}

export async function listProjectedTargetPaperIds(
  sourcePaperId: string,
  {
    excludeRelationTypes = [],
    limit = 10,
  }: { excludeRelationTypes?: string[]; limit?: number } = {},
  db: ProjectedRelationDb = prisma,
): Promise<string[]> {
  if ("paper" in db && db.paper) {
    const sourcePaper = await db.paper.findUnique({
      where: { id: sourcePaperId },
      select: { userId: true },
    });

    if (sourcePaper?.userId) {
      const relatedRows = await listRelationsForPaper(
        sourcePaperId,
        sourcePaper.userId,
        db as RelationReaderDb,
      );

      const excludedTypes = new Set(
        excludeRelationTypes.map((relationType) => relationType.toLowerCase()),
      );

      return relatedRows.rows
        .filter(
          (row) =>
            !excludedTypes.has(row.relationType.toLowerCase()),
        )
        .slice(0, limit)
        .map((row) => row.relatedPaper.id);
    }
  }

  const relationTypeFilter =
    excludeRelationTypes.length > 0 ? { notIn: excludeRelationTypes } : undefined;
  const relations = await db.paperRelation.findMany({
    where: {
      sourcePaperId,
      ...(relationTypeFilter ? { relationType: relationTypeFilter } : {}),
    },
    orderBy: { confidence: "desc" },
    take: limit,
    select: { targetPaperId: true },
  });

  return relations.map((relation) => relation.targetPaperId);
}

export async function listProjectedRelationEdgesWithinPaperIds(
  paperIds: string[],
  db: ProjectedRelationDb = prisma,
): Promise<Array<{ sourcePaperId: string; targetPaperId: string }>> {
  if (paperIds.length === 0) return [];

  return db.paperRelation.findMany({
    where: {
      sourcePaperId: { in: paperIds },
      targetPaperId: { in: paperIds },
    },
    select: {
      sourcePaperId: true,
      targetPaperId: true,
    },
  });
}
