"use client";

import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Trash2 } from "lucide-react";
import { toast } from "sonner";
import Link from "next/link";

interface RelatedPaper {
  id: string;
  title: string;
  year: number | null;
  authors: string | null;
}

interface Relation {
  id: string;
  relatedPaper: RelatedPaper;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
}

export function RelatedPapers({ paperId }: { paperId: string }) {
  const [relations, setRelations] = useState<Relation[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchRelations = async () => {
    try {
      const res = await fetch(`/api/papers/${paperId}/relations`);
      if (res.ok) {
        setRelations(await res.json());
      }
    } catch {
      toast.error("Failed to load related papers");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRelations();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paperId]);

  const handleDelete = async (relationId: string) => {
    try {
      const res = await fetch(
        `/api/papers/${paperId}/relations?relationId=${relationId}`,
        { method: "DELETE" }
      );
      if (res.ok) {
        setRelations((prev) => prev.filter((r) => r.id !== relationId));
        toast.success("Relation removed");
      }
    } catch {
      toast.error("Failed to remove relation");
    }
  };

  if (loading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
      </div>
    );
  }

  if (relations.length === 0) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          No related papers found
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-3">
      {relations.map((rel) => (
        <Card key={rel.id} className="group relative">
          <CardContent className="py-3">
            <div className="min-w-0">
              <div className="pr-14 mb-1">
                <Link
                  href={`/papers/${rel.relatedPaper.id}`}
                  className="font-medium text-sm hover:underline"
                >
                  {rel.relatedPaper.title}
                </Link>
                {rel.relatedPaper.year && (
                  <span className="text-xs text-muted-foreground">
                    {" "}({rel.relatedPaper.year})
                  </span>
                )}
              </div>
              <div className="text-xs text-muted-foreground">
                <Badge variant="secondary" className="text-xs mr-1.5 align-middle">
                  {rel.relationType}
                </Badge>
                {rel.description}
              </div>
            </div>
            <div className="absolute top-2 right-2 flex items-center gap-1">
              <ConfidenceGauge value={rel.confidence} />
              <button
                className="inline-flex h-6 w-6 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
                onClick={() => handleDelete(rel.id)}
                title="Remove"
              >
                <Trash2 className="h-3.5 w-3.5" />
              </button>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

function ConfidenceGauge({ value }: { value: number }) {
  const pct = Math.round(value * 100);
  const r = 7;
  const circumference = 2 * Math.PI * r;
  const filled = circumference * value;
  const color =
    pct >= 80 ? "text-green-500" : pct >= 50 ? "text-yellow-500" : "text-red-400";

  return (
    <div className="h-5 w-5" title={`${pct}% confidence`}>
      <svg viewBox="0 0 18 18" className="h-5 w-5 -rotate-90">
        <circle
          cx="9"
          cy="9"
          r={r}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          className="text-muted-foreground/20"
        />
        <circle
          cx="9"
          cy="9"
          r={r}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeDasharray={`${filled} ${circumference - filled}`}
          strokeLinecap="round"
          className={color}
        />
      </svg>
    </div>
  );
}
