"use client";

import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Trash2, Bot } from "lucide-react";
import { toast } from "sonner";
import Link from "next/link";

interface RelatedPaper {
  id: string;
  title: string;
  year: number | null;
  authors: string | null;
}

interface Relation {
  id: string;
  relatedPaper: RelatedPaper;
  relationType: string;
  description: string | null;
  confidence: number;
  isAutoGenerated: boolean;
}

export function RelatedPapers({ paperId }: { paperId: string }) {
  const [relations, setRelations] = useState<Relation[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchRelations = async () => {
    try {
      const res = await fetch(`/api/papers/${paperId}/relations`);
      if (res.ok) {
        setRelations(await res.json());
      }
    } catch {
      toast.error("Failed to load related papers");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRelations();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paperId]);

  const handleDelete = async (relationId: string) => {
    try {
      const res = await fetch(
        `/api/papers/${paperId}/relations?relationId=${relationId}`,
        { method: "DELETE" }
      );
      if (res.ok) {
        setRelations((prev) => prev.filter((r) => r.id !== relationId));
        toast.success("Relation removed");
      }
    } catch {
      toast.error("Failed to remove relation");
    }
  };

  if (loading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
      </div>
    );
  }

  if (relations.length === 0) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          No related papers found
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-3">
      {relations.map((rel) => (
        <Card key={rel.id} className="group">
          <CardContent className="py-4 flex items-start justify-between gap-4">
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-2 flex-wrap mb-1">
                <Link
                  href={`/papers/${rel.relatedPaper.id}`}
                  className="font-medium text-sm hover:underline truncate"
                >
                  {rel.relatedPaper.title}
                </Link>
                {rel.relatedPaper.year && (
                  <span className="text-xs text-muted-foreground">
                    ({rel.relatedPaper.year})
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2 flex-wrap">
                <Badge variant="secondary" className="text-xs">
                  {rel.relationType}
                </Badge>
                {rel.isAutoGenerated && (
                  <Badge variant="outline" className="text-xs gap-1">
                    <Bot className="h-3 w-3" />
                    auto
                  </Badge>
                )}
                <span className="text-xs text-muted-foreground">
                  {Math.round(rel.confidence * 100)}% confidence
                </span>
              </div>
              {rel.description && (
                <p className="text-xs text-muted-foreground mt-1">
                  {rel.description}
                </p>
              )}
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="opacity-0 group-hover:opacity-100 transition-opacity shrink-0"
              onClick={() => handleDelete(rel.id)}
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
