import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { requireUserId } from "@/lib/paper-auth";
import { createRelationAssertion } from "@/lib/assertions/relation-assertion-service";
import { getAggregatedRelationsForPaper } from "@/lib/assertions/relation-aggregate";
import { projectLegacyRelation } from "@/lib/assertions/legacy-projection";

const createRelationSchema = z.object({
  targetPaperId: z.string().uuid(),
  relationType: z.string().min(1),
  description: z.string().optional(),
});

function parseAggregateKey(
  key: string
): { peerEntityId: string; relationType: string } | null {
  if (!key.startsWith("agg::")) return null;
  const parts = key.split("::");
  if (parts.length !== 3) return null;
  return { peerEntityId: parts[1], relationType: parts[2] };
}

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const userId = await requireUserId();
  const paperId = params.id;

  const paper = await prisma.paper.findFirst({
    where: { id: paperId, userId },
    select: { id: true, entityId: true },
  });
  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  if (paper.entityId) {
    const aggregated = await getAggregatedRelationsForPaper(paperId, paper.entityId, userId);
    const relations = [];

    for (const aggregate of aggregated) {
      const localPaper = await prisma.paper.findFirst({
        where: { entityId: aggregate.peerEntityId, userId },
        select: { id: true, title: true, year: true, authors: true },
      });

      if (!localPaper) continue;

      relations.push({
        id: `agg::${aggregate.peerEntityId}::${aggregate.relationType}`,
        relatedPaper: localPaper,
        relationType: aggregate.relationType,
        description: aggregate.description,
        confidence: aggregate.maxConfidence,
        isAutoGenerated: !aggregate.provenances.includes("user_manual"),
      });
    }

    if (relations.length > 0) {
      relations.sort((a, b) => b.confidence - a.confidence);
      return NextResponse.json(relations);
    }
  }

  const [sourceRelations, targetRelations] = await Promise.all([
    prisma.paperRelation.findMany({
      where: { sourcePaperId: paperId },
      include: {
        targetPaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    }),
    prisma.paperRelation.findMany({
      where: { targetPaperId: paperId },
      include: {
        sourcePaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    }),
  ]);

  const seen = new Set<string>();
  const relations = [];

  for (const relation of sourceRelations) {
    if (seen.has(relation.targetPaper.id)) continue;
    seen.add(relation.targetPaper.id);
    relations.push({
      id: relation.id,
      relatedPaper: relation.targetPaper,
      relationType: relation.relationType,
      description: relation.description,
      confidence: relation.confidence,
      isAutoGenerated: relation.isAutoGenerated,
    });
  }

  for (const relation of targetRelations) {
    if (seen.has(relation.sourcePaper.id)) continue;
    seen.add(relation.sourcePaper.id);
    relations.push({
      id: relation.id,
      relatedPaper: relation.sourcePaper,
      relationType: relation.relationType,
      description: relation.description,
      confidence: relation.confidence,
      isAutoGenerated: relation.isAutoGenerated,
    });
  }

  relations.sort((a, b) => b.confidence - a.confidence);
  return NextResponse.json(relations);
}

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const userId = await requireUserId();

  try {
    const body = await request.json();
    const data = createRelationSchema.parse(body);

    if (data.targetPaperId === paperId) {
      return NextResponse.json(
        { error: "Cannot create a relation to the same paper" },
        { status: 400 }
      );
    }

    const [source, target] = await Promise.all([
      prisma.paper.findFirst({
        where: { id: paperId, userId },
        select: { id: true, entityId: true },
      }),
      prisma.paper.findFirst({
        where: { id: data.targetPaperId, userId },
        select: { id: true, entityId: true, title: true, year: true, authors: true },
      }),
    ]);

    if (!source || !target) {
      return NextResponse.json(
        { error: "One or both papers not found" },
        { status: 404 }
      );
    }

    const relation = await prisma.paperRelation.upsert({
      where: {
        sourcePaperId_targetPaperId: {
          sourcePaperId: paperId,
          targetPaperId: data.targetPaperId,
        },
      },
      update: {
        relationType: data.relationType,
        description: data.description || null,
        confidence: 1.0,
        isAutoGenerated: false,
      },
      create: {
        sourcePaperId: paperId,
        targetPaperId: data.targetPaperId,
        relationType: data.relationType,
        description: data.description || null,
        confidence: 1.0,
        isAutoGenerated: false,
      },
      include: {
        targetPaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    });

    if (source.entityId && target.entityId) {
      try {
        await createRelationAssertion({
          sourceEntityId: source.entityId,
          targetEntityId: target.entityId,
          sourcePaperId: paperId,
          relationType: data.relationType,
          description: data.description || null,
          confidence: 1.0,
          provenance: "user_manual",
          createdByUserId: userId,
        });
        await projectLegacyRelation(
          paperId,
          data.targetPaperId,
          source.entityId,
          target.entityId,
          false
        );
      } catch {
        // Non-fatal
      }
    }

    return NextResponse.json(relation, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation error", details: error.issues },
        { status: 400 }
      );
    }
    console.error("Create relation error:", error);
    return NextResponse.json(
      { error: "Failed to create relation" },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const userId = await requireUserId();
  const { searchParams } = new URL(request.url);
  const relationId = searchParams.get("relationId");

  if (!relationId) {
    return NextResponse.json(
      { error: "relationId query parameter is required" },
      { status: 400 }
    );
  }

  const paper = await prisma.paper.findFirst({
    where: { id: paperId, userId },
    select: { id: true, entityId: true },
  });
  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  const aggregateKey = parseAggregateKey(relationId);
  if (aggregateKey && paper.entityId) {
    const deleted = await prisma.relationAssertion.deleteMany({
      where: {
        relationType: aggregateKey.relationType,
        OR: [
          { sourcePaperId: paperId, targetEntityId: aggregateKey.peerEntityId },
          {
            sourceEntityId: aggregateKey.peerEntityId,
            targetEntityId: paper.entityId,
            sourcePaper: { userId },
          },
        ],
      },
    });

    if (deleted.count === 0) {
      return NextResponse.json({ error: "No assertions found" }, { status: 404 });
    }

    const peerPaper = await prisma.paper.findFirst({
      where: { entityId: aggregateKey.peerEntityId, userId },
      select: { id: true },
    });
    if (peerPaper) {
      await prisma.paperRelation.deleteMany({
        where: {
          OR: [
            { sourcePaperId: paperId, targetPaperId: peerPaper.id },
            { sourcePaperId: peerPaper.id, targetPaperId: paperId },
          ],
        },
      });
    }

    return NextResponse.json({ success: true });
  }

  const relation = await prisma.paperRelation.findUnique({
    where: { id: relationId },
    include: {
      sourcePaper: { select: { userId: true } },
      targetPaper: { select: { userId: true } },
    },
  });

  if (!relation) {
    return NextResponse.json({ error: "Relation not found" }, { status: 404 });
  }

  const belongsToUser =
    (relation.sourcePaperId === paperId && relation.sourcePaper?.userId === userId) ||
    (relation.targetPaperId === paperId && relation.targetPaper?.userId === userId);

  if (!belongsToUser) {
    return NextResponse.json(
      { error: "Relation does not belong to this paper" },
      { status: 403 }
    );
  }

  await prisma.paperRelation.delete({ where: { id: relationId } });
  return NextResponse.json({ success: true });
}
