import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { requireUserId } from "@/lib/paper-auth";
import { createRelationAssertion } from "@/lib/assertions/relation-assertion-service";
import { projectLegacyRelation } from "@/lib/assertions/legacy-projection";
import {
  GraphRelationError,
  listRelationsForPaper,
  parseAggregateKey,
  toRouteRelationRow,
} from "@/lib/assertions/graph-relations";

const createRelationSchema = z.object({
  targetPaperId: z.string().uuid(),
  relationType: z.string().min(1),
  description: z.string().optional(),
});

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const userId = await requireUserId();
  try {
    const result = await listRelationsForPaper(params.id, userId);
    return NextResponse.json(result.rows.map(toRouteRelationRow));
  } catch (error) {
    if (error instanceof GraphRelationError) {
      const status = typeof error.status === "number" ? error.status : 500;
      return NextResponse.json({ error: error.message }, { status });
    }
    throw error;
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const userId = await requireUserId();

  try {
    const body = await request.json();
    const data = createRelationSchema.parse(body);

    if (data.targetPaperId === paperId) {
      return NextResponse.json(
        { error: "Cannot create a relation to the same paper" },
        { status: 400 }
      );
    }

    const [source, target] = await Promise.all([
      prisma.paper.findFirst({
        where: { id: paperId, userId },
        select: { id: true, entityId: true },
      }),
      prisma.paper.findFirst({
        where: { id: data.targetPaperId, userId },
        select: { id: true, entityId: true, title: true, year: true, authors: true },
      }),
    ]);

    if (!source || !target) {
      return NextResponse.json(
        { error: "One or both papers not found" },
        { status: 404 }
      );
    }

    const relation = await prisma.paperRelation.upsert({
      where: {
        sourcePaperId_targetPaperId: {
          sourcePaperId: paperId,
          targetPaperId: data.targetPaperId,
        },
      },
      update: {
        relationType: data.relationType,
        description: data.description || null,
        confidence: 1.0,
        isAutoGenerated: false,
      },
      create: {
        sourcePaperId: paperId,
        targetPaperId: data.targetPaperId,
        relationType: data.relationType,
        description: data.description || null,
        confidence: 1.0,
        isAutoGenerated: false,
      },
      include: {
        targetPaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    });

    if (source.entityId && target.entityId) {
      try {
        await createRelationAssertion({
          sourceEntityId: source.entityId,
          targetEntityId: target.entityId,
          sourcePaperId: paperId,
          relationType: data.relationType,
          description: data.description || null,
          confidence: 1.0,
          provenance: "user_manual",
          createdByUserId: userId,
        });
        await projectLegacyRelation(
          paperId,
          data.targetPaperId,
          source.entityId,
          target.entityId,
          false
        );
      } catch {
        // Non-fatal
      }
    }

    return NextResponse.json(relation, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation error", details: error.issues },
        { status: 400 }
      );
    }
    console.error("Create relation error:", error);
    return NextResponse.json(
      { error: "Failed to create relation" },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const userId = await requireUserId();
  const { searchParams } = new URL(request.url);
  const relationId = searchParams.get("relationId");

  if (!relationId) {
    return NextResponse.json(
      { error: "relationId query parameter is required" },
      { status: 400 }
    );
  }

  const paper = await prisma.paper.findFirst({
    where: { id: paperId, userId },
    select: { id: true, entityId: true },
  });
  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  const aggregateKey = parseAggregateKey(relationId);
  if (aggregateKey && paper.entityId) {
    const deleted = await prisma.relationAssertion.deleteMany({
      where: {
        relationType: aggregateKey.relationType,
        OR: [
          { sourcePaperId: paperId, targetEntityId: aggregateKey.peerEntityId },
          {
            sourceEntityId: aggregateKey.peerEntityId,
            targetEntityId: paper.entityId,
            sourcePaper: { userId },
          },
        ],
      },
    });

    if (deleted.count === 0) {
      return NextResponse.json({ error: "No assertions found" }, { status: 404 });
    }

    const peerPaper = await prisma.paper.findFirst({
      where: { entityId: aggregateKey.peerEntityId, userId },
      select: { id: true },
    });
    if (peerPaper) {
      await prisma.paperRelation.deleteMany({
        where: {
          OR: [
            { sourcePaperId: paperId, targetPaperId: peerPaper.id },
            { sourcePaperId: peerPaper.id, targetPaperId: paperId },
          ],
        },
      });
    }

    return NextResponse.json({ success: true });
  }

  const relation = await prisma.paperRelation.findUnique({
    where: { id: relationId },
    include: {
      sourcePaper: { select: { userId: true } },
      targetPaper: { select: { userId: true } },
    },
  });

  if (!relation) {
    return NextResponse.json({ error: "Relation not found" }, { status: 404 });
  }

  const belongsToUser =
    (relation.sourcePaperId === paperId && relation.sourcePaper?.userId === userId) ||
    (relation.targetPaperId === paperId && relation.targetPaper?.userId === userId);

  if (!belongsToUser) {
    return NextResponse.json(
      { error: "Relation does not belong to this paper" },
      { status: 403 }
    );
  }

  await prisma.paperRelation.delete({ where: { id: relationId } });
  return NextResponse.json({ success: true });
}
