import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { requireUserId } from "@/lib/paper-auth";

const createRelationSchema = z.object({
  targetPaperId: z.string().uuid(),
  relationType: z.string().min(1),
  description: z.string().optional(),
});

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const userId = await requireUserId();
    const paperId = params.id;

  const paper = await prisma.paper.findFirst({ where: { id: paperId, userId } });
  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  const [sourceRelations, targetRelations] = await Promise.all([
    prisma.paperRelation.findMany({
      where: { sourcePaperId: paperId },
      include: {
        targetPaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    }),
    prisma.paperRelation.findMany({
      where: { targetPaperId: paperId },
      include: {
        sourcePaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    }),
  ]);

  const seen = new Set<string>();
  const relations = [];

  for (const rel of sourceRelations) {
    if (seen.has(rel.targetPaper.id)) continue;
    seen.add(rel.targetPaper.id);
    relations.push({
      id: rel.id,
      relatedPaper: rel.targetPaper,
      relationType: rel.relationType,
      description: rel.description,
      confidence: rel.confidence,
      isAutoGenerated: rel.isAutoGenerated,
    });
  }

  for (const rel of targetRelations) {
    if (seen.has(rel.sourcePaper.id)) continue;
    seen.add(rel.sourcePaper.id);
    relations.push({
      id: rel.id,
      relatedPaper: rel.sourcePaper,
      relationType: rel.relationType,
      description: rel.description,
      confidence: rel.confidence,
      isAutoGenerated: rel.isAutoGenerated,
    });
  }

  relations.sort((a, b) => b.confidence - a.confidence);

  return NextResponse.json(relations);
}

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const userId = await requireUserId();

  try {
    const body = await request.json();
    const data = createRelationSchema.parse(body);

    if (data.targetPaperId === paperId) {
      return NextResponse.json(
        { error: "Cannot create a relation to the same paper" },
        { status: 400 }
      );
    }

    const [source, target] = await Promise.all([
      prisma.paper.findFirst({ where: { id: paperId, userId } }),
      prisma.paper.findFirst({ where: { id: data.targetPaperId, userId } }),
    ]);

    if (!source || !target) {
      return NextResponse.json(
        { error: "One or both papers not found" },
        { status: 404 }
      );
    }

    const relation = await prisma.paperRelation.create({
      data: {
        sourcePaperId: paperId,
        targetPaperId: data.targetPaperId,
        relationType: data.relationType,
        description: data.description || null,
        confidence: 1.0,
        isAutoGenerated: false,
      },
      include: {
        targetPaper: {
          select: { id: true, title: true, year: true, authors: true },
        },
      },
    });

    return NextResponse.json(relation, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation error", details: error.issues },
        { status: 400 }
      );
    }
    console.error("Create relation error:", error);
    return NextResponse.json(
      { error: "Failed to create relation" },
      { status: 500 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const paperId = params.id;
  const { searchParams } = new URL(request.url);
  const relationId = searchParams.get("relationId");

  if (!relationId) {
    return NextResponse.json(
      { error: "relationId query parameter is required" },
      { status: 400 }
    );
  }

  const relation = await prisma.paperRelation.findUnique({
    where: { id: relationId },
  });

  if (!relation) {
    return NextResponse.json(
      { error: "Relation not found" },
      { status: 404 }
    );
  }

  if (relation.sourcePaperId !== paperId && relation.targetPaperId !== paperId) {
    return NextResponse.json(
      { error: "Relation does not belong to this paper" },
      { status: 403 }
    );
  }

  await prisma.paperRelation.delete({ where: { id: relationId } });

  return NextResponse.json({ success: true });
}
