"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Trash2, Plus, Merge, Loader2, Check } from "lucide-react";
import { toast } from "sonner";

interface Tag {
  id: string;
  name: string;
  color: string;
  isAutoGenerated: boolean;
  _count: { papers: number };
}

interface DuplicateTag {
  id: string;
  name: string;
  paperCount: number;
}

type DuplicateGroup = DuplicateTag[];

const TAG_COLORS = [
  "#EF4444",
  "#F59E0B",
  "#10B981",
  "#3B82F6",
  "#8B5CF6",
  "#EC4899",
  "#06B6D4",
  "#F97316",
];

export default function TagsPage() {
  const [tags, setTags] = useState<Tag[]>([]);
  const [newName, setNewName] = useState("");
  const [newColor, setNewColor] = useState(TAG_COLORS[0]);
  const [duplicates, setDuplicates] = useState<DuplicateGroup[]>([]);
  const [dupsLoading, setDupsLoading] = useState(false);
  const [dupsScanned, setDupsScanned] = useState(false);
  const [mergingGroup, setMergingGroup] = useState<number | null>(null);
  // Track which tag is selected as the merge target per group
  const [selectedTargets, setSelectedTargets] = useState<
    Record<number, string>
  >({});

  const fetchTags = async () => {
    const res = await fetch("/api/tags");
    setTags(await res.json());
  };

  useEffect(() => {
    fetchTags();
  }, []);

  const createTag = async () => {
    if (!newName.trim()) return;
    const res = await fetch("/api/tags", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newName.trim(), color: newColor }),
    });
    if (res.ok) {
      toast.success("Tag created");
      setNewName("");
      fetchTags();
    } else {
      toast.error("Failed to create tag");
    }
  };

  const deleteTag = async (id: string) => {
    if (!confirm("Delete this tag?")) return;
    await fetch(`/api/tags/${id}`, { method: "DELETE" });
    toast.success("Tag deleted");
    fetchTags();
  };

  const findDuplicates = async () => {
    setDupsLoading(true);
    try {
      const res = await fetch("/api/tags/duplicates");
      const groups: DuplicateGroup[] = await res.json();
      setDuplicates(groups);
      setDupsScanned(true);
      // Default: pick the tag with the most papers as the target
      const targets: Record<number, string> = {};
      groups.forEach((group, i) => {
        const best = group.reduce((a, b) =>
          b.paperCount > a.paperCount ? b : a
        );
        targets[i] = best.id;
      });
      setSelectedTargets(targets);
      if (groups.length === 0) {
        toast.success("No duplicate tags found");
      }
    } catch {
      toast.error("Failed to scan for duplicates");
    }
    setDupsLoading(false);
  };

  const mergeGroup = async (groupIndex: number) => {
    const group = duplicates[groupIndex];
    const targetId = selectedTargets[groupIndex];
    if (!targetId) return;
    const sourceIds = group.filter((t) => t.id !== targetId).map((t) => t.id);
    if (sourceIds.length === 0) return;

    setMergingGroup(groupIndex);
    try {
      const res = await fetch("/api/tags/merge", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId, sourceIds }),
      });
      if (res.ok) {
        toast.success("Tags merged");
        setDuplicates((prev) => prev.filter((_, i) => i !== groupIndex));
        fetchTags();
      } else {
        toast.error("Failed to merge tags");
      }
    } catch {
      toast.error("Failed to merge tags");
    }
    setMergingGroup(null);
  };

  const mergeAll = async () => {
    for (let i = 0; i < duplicates.length; i++) {
      await mergeGroup(i);
    }
  };

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">Tags</h2>
        <p className="text-muted-foreground">
          Manage tags to organize your papers.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Create Tag</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-3">
            <Input
              placeholder="Tag name..."
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && createTag()}
            />
            <div className="flex gap-1">
              {TAG_COLORS.map((c) => (
                <button
                  key={c}
                  onClick={() => setNewColor(c)}
                  className={`h-8 w-8 rounded-full border-2 transition-transform ${
                    newColor === c
                      ? "scale-110 border-foreground"
                      : "border-transparent"
                  }`}
                  style={{ backgroundColor: c }}
                />
              ))}
            </div>
            <Button onClick={createTag}>
              <Plus className="mr-1 h-4 w-4" />
              Create
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Duplicate detection */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Deduplicate Tags</CardTitle>
            <Button
              variant="outline"
              size="sm"
              onClick={findDuplicates}
              disabled={dupsLoading}
            >
              {dupsLoading ? (
                <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
              ) : (
                <Merge className="mr-1.5 h-4 w-4" />
              )}
              {dupsScanned ? "Rescan" : "Find Duplicates"}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {!dupsScanned ? (
            <p className="text-sm text-muted-foreground">
              Scan for similar tags that can be merged (e.g. &quot;nlp&quot; and
              &quot;natural-language-processing&quot;).
            </p>
          ) : duplicates.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No duplicate tags found.
            </p>
          ) : (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <p className="text-sm text-muted-foreground">
                  Found {duplicates.length} group
                  {duplicates.length !== 1 ? "s" : ""} of similar tags.
                  Select which tag to keep in each group.
                </p>
                <Button size="sm" onClick={mergeAll}>
                  Merge All
                </Button>
              </div>
              {duplicates.map((group, i) => (
                <div
                  key={i}
                  className="rounded-md border p-3 space-y-2"
                >
                  <div className="flex flex-wrap gap-2">
                    {group.map((tag) => {
                      const isTarget = selectedTargets[i] === tag.id;
                      return (
                        <button
                          key={tag.id}
                          onClick={() =>
                            setSelectedTargets((prev) => ({
                              ...prev,
                              [i]: tag.id,
                            }))
                          }
                          className={`flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 text-sm transition-colors ${
                            isTarget
                              ? "border-primary bg-primary/5 font-medium"
                              : "border-transparent hover:bg-accent"
                          }`}
                        >
                          {isTarget && (
                            <Check className="h-3.5 w-3.5 text-primary" />
                          )}
                          <span>{tag.name}</span>
                          <span className="text-xs text-muted-foreground">
                            ({tag.paperCount})
                          </span>
                        </button>
                      );
                    })}
                  </div>
                  <div className="flex justify-end">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => mergeGroup(i)}
                      disabled={mergingGroup === i}
                    >
                      {mergingGroup === i ? (
                        <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <Merge className="mr-1.5 h-3.5 w-3.5" />
                      )}
                      Merge into &quot;
                      {group.find((t) => t.id === selectedTargets[i])
                        ?.name || "..."}
                      &quot;
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>All Tags ({tags.length})</CardTitle>
        </CardHeader>
        <CardContent>
          {tags.length === 0 ? (
            <p className="text-sm text-muted-foreground">No tags yet.</p>
          ) : (
            <div className="space-y-2">
              {tags.map((tag) => (
                <div
                  key={tag.id}
                  className="flex items-center justify-between rounded-md border p-3"
                >
                  <div className="flex items-center gap-3">
                    <Badge
                      style={{
                        backgroundColor: tag.color + "20",
                        color: tag.color,
                      }}
                    >
                      {tag.name}
                    </Badge>
                    <span className="text-sm text-muted-foreground">
                      {tag._count.papers} paper
                      {tag._count.papers !== 1 ? "s" : ""}
                    </span>
                    {tag.isAutoGenerated && (
                      <Badge variant="outline" className="text-xs">
                        Auto
                      </Badge>
                    )}
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => deleteTag(tag.id)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
