"use client";

import { useState, useEffect, useCallback } from "react";
import { Image, X, Download, RefreshCw, Loader2, ChevronDown } from "lucide-react";

interface FigureFile {
  name: string;
  path: string;
  size: number;
  modified: string;
}

interface FiguresGalleryProps {
  projectId: string;
  /** When true, the gallery starts collapsed and only shows if figures exist */
  collapsible?: boolean;
}

export function FiguresGallery({ projectId, collapsible = false }: FiguresGalleryProps) {
  const [figures, setFigures] = useState<FigureFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedFigure, setSelectedFigure] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState(collapsible);

  const fetchFigures = useCallback(() => {
    setLoading(true);
    fetch(`/api/research/${projectId}/files`)
      .then((r) => r.json())
      .then((data) => {
        const allFiles: FigureFile[] = [];
        const walk = (files: { name: string; path: string; size: number; modified: string; isDir: boolean; children?: unknown[] }[]) => {
          for (const f of files) {
            if (f.isDir && f.children) {
              walk(f.children as typeof files);
            } else if (/\.(png|jpg|jpeg|svg|gif)$/i.test(f.name) && !f.path.includes(".venv")) {
              allFiles.push({ name: f.name, path: f.path, size: f.size, modified: f.modified });
            }
          }
        };
        if (data.files) walk(data.files);
        // Sort by modified date, newest first
        allFiles.sort((a, b) => (b.modified || "").localeCompare(a.modified || ""));
        setFigures(allFiles);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [projectId]);

  useEffect(() => {
    fetchFigures();
    const interval = setInterval(fetchFigures, 30_000);
    return () => clearInterval(interval);
  }, [fetchFigures]);

  const imgUrl = (filePath: string) =>
    `/api/research/${projectId}/files/download?path=${encodeURIComponent(filePath)}`;

  // When collapsible and no figures, render nothing
  if (collapsible && !loading && figures.length === 0) {
    return null;
  }

  // Loading state (only on first load)
  if (loading && figures.length === 0) {
    if (collapsible) return null;
    return (
      <div className="flex items-center gap-2 py-4 text-muted-foreground text-xs justify-center">
        <Loader2 className="h-3 w-3 animate-spin" /> Loading figures...
      </div>
    );
  }

  // No figures (non-collapsible only)
  if (figures.length === 0) {
    return (
      <div className="rounded-lg border border-dashed border-border p-6 text-center">
        <Image className="h-6 w-6 mx-auto mb-2 text-muted-foreground/30" />
        <p className="text-xs text-muted-foreground">
          No figures yet. Figures generated by the visualizer will appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={() => collapsible && setCollapsed(!collapsed)}
          className={`flex items-center gap-2 ${collapsible ? "cursor-pointer hover:text-foreground" : "cursor-default"} transition-colors`}
        >
          {collapsible && (
            <ChevronDown className={`h-3.5 w-3.5 text-muted-foreground transition-transform ${collapsed ? "-rotate-90" : ""}`} />
          )}
          <Image className="h-4 w-4 text-muted-foreground/60" />
          <h3 className="text-sm font-medium">
            Figures
            <span className="ml-1.5 text-xs font-normal text-muted-foreground">({figures.length})</span>
          </h3>
        </button>
        <button
          onClick={fetchFigures}
          className="text-muted-foreground/40 hover:text-muted-foreground transition-colors"
          title="Refresh figures"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
        </button>
      </div>

      {/* Figure grid */}
      {!collapsed && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {figures.map((fig) => (
            <button
              key={fig.path}
              onClick={() => setSelectedFigure(fig.path)}
              className="group rounded-lg border border-border/50 overflow-hidden hover:border-foreground/20 transition-colors bg-white"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={imgUrl(fig.path)}
                alt={fig.name}
                className="w-full object-contain bg-white"
                loading="lazy"
              />
              <div className="px-3 py-2 bg-background border-t border-border/30">
                <p className="text-xs text-muted-foreground truncate">{fig.name}</p>
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Lightbox */}
      {selectedFigure && (
        <div
          className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-8 animate-in fade-in-0 duration-150"
          onClick={() => setSelectedFigure(null)}
        >
          <div className="relative max-w-[90vw] max-h-[90vh]" onClick={(e) => e.stopPropagation()}>
            <div className="absolute -top-10 right-0 flex gap-2">
              <a
                href={imgUrl(selectedFigure)}
                download
                className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors"
              >
                <Download className="h-4 w-4" />
              </a>
              <button
                onClick={() => setSelectedFigure(null)}
                className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={imgUrl(selectedFigure)}
              alt={figures.find((f) => f.path === selectedFigure)?.name || ""}
              className="max-w-full max-h-[85vh] object-contain rounded-lg bg-white"
            />
            <p className="text-center text-xs text-white/50 mt-2">
              {figures.find((f) => f.path === selectedFigure)?.name}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
