import { describe, expect, it } from "vitest";

import {
  buildMultiplicitySummary,
  classifyParityChange,
  validateWaivers,
} from "../lib/graph-readiness.mjs";

const manualRow = (overrides: Partial<any> = {}) => ({
  id: "row-1",
  relatedPaper: {
    id: "peer-1",
    title: "Peer Paper",
    year: 2024,
    authors: null,
  },
  relationType: "cites",
  description: null,
  confidence: 0.9,
  isAutoGenerated: false,
  ...overrides,
});

describe("graph readiness helpers", () => {
  it("classifies pure fan-out as expected mode-switch", () => {
    const beforeRows = [manualRow()];
    const afterRows = [
      manualRow({ id: "agg::peer-1::cites" }),
      manualRow({
        id: "agg::peer-1::extends",
        relationType: "extends",
        description: "Extends the method",
      }),
    ];

    const result = classifyParityChange({
      beforeMode: "legacy",
      beforeRows,
      afterMode: "aggregate",
      afterRows,
    });

    expect(result.classification).toBe("expected_mode_switch");
    expect(result.multiplicity.fanOutPeers).toEqual([
      { peerPaperId: "peer-1", relationTypes: ["cites", "extends"] },
    ]);
  });

  it("classifies peer-set drift as a true mismatch", () => {
    const result = classifyParityChange({
      beforeMode: "legacy",
      beforeRows: [manualRow()],
      afterMode: "aggregate",
      afterRows: [manualRow({ relatedPaper: { id: "peer-2", title: "Other", year: 2025, authors: null } })],
    });

    expect(result.classification).toBe("true_mismatch");
    expect(result.mismatchDetails?.missingPeers).toEqual(["peer-1"]);
    expect(result.mismatchDetails?.addedPeers).toEqual(["peer-2"]);
  });

  it("rejects waivers for write-visible papers", () => {
    const result = validateWaivers(
      [
        {
          paperId: "paper-1",
          reason: "bad waiver",
          decided_by: "PE",
          decided_at: "2026-04-17T00:00:00.000Z",
          write_visible: false,
        },
      ],
      new Map([
        [
          "paper-1",
          {
            owner_userId: "user-1",
            rendered_in_relations_ui: true,
            checked_at: "2026-04-17T00:00:00.000Z",
          },
        ],
      ])
    );

    expect(result.errors).toEqual([
      "Waiver paper-1 is invalid: paper is write-visible in relations UI",
    ]);
  });

  it("reports multiplicity counts deterministically", () => {
    const summary = buildMultiplicitySummary(
      [manualRow()],
      [
        manualRow({ id: "agg::peer-1::cites" }),
        manualRow({
          id: "agg::peer-1::extends",
          relationType: "extends",
          description: "Extends the method",
        }),
      ]
    );

    expect(summary.peerCountBefore).toBe(1);
    expect(summary.peerCountAfter).toBe(1);
    expect(summary.rowCountBefore).toBe(1);
    expect(summary.rowCountAfter).toBe(2);
  });
});
