import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { resolveModelConfig } from "@/lib/llm/auto-process";
import { generateLLMResponse, truncateText } from "@/lib/llm/provider";
import {
  PAPER_INTERACTIVE_LLM_OPERATIONS,
  withPaperLlmContext,
} from "@/lib/llm/paper-llm-context";
import { buildDistillPrompt, cleanJsonResponse } from "@/lib/llm/prompts";
import { paperAccessErrorToResponse, requirePaperAccess } from "@/lib/paper-auth";

// POST /api/papers/[id]/distill - On-demand distill insights from a paper
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id: paperId } = await params;
    const access = await requirePaperAccess(paperId, {
      mode: "mutate",
      select: { id: true, fullText: true, abstract: true },
    });
    if (!access) {
      return NextResponse.json({ error: "Paper not found" }, { status: 404 });
    }
    const paper = access.paper;

    const text = paper.fullText || paper.abstract;
    if (!text) {
      return NextResponse.json({ error: "No text available to distill" }, { status: 400 });
    }

    let body: Record<string, string> = {};
    try {
      body = await req.json();
    } catch {
      // no body is fine
    }

    const { provider, modelId, proxyConfig } = await resolveModelConfig(body);
    const truncated = truncateText(text, modelId, proxyConfig);

    const existingRooms = await prisma.mindPalaceRoom.findMany({
      select: { name: true },
    });
    const roomNames = existingRooms.map((room) => room.name);

    const { system, prompt } = buildDistillPrompt(truncated, roomNames);
    const result = await withPaperLlmContext(
      {
        operation: PAPER_INTERACTIVE_LLM_OPERATIONS.DISTILL,
        paperId,
        userId: access.userId,
        runtime: "interactive",
        source: "papers.distill",
      },
      () =>
        generateLLMResponse({
          provider,
          modelId,
          system,
          prompt,
          maxTokens: 4000,
          proxyConfig,
        }),
    );

    await prisma.promptResult.create({
      data: {
        paperId,
        promptType: "distill",
        prompt: "Distill insights from paper",
        result,
        provider,
        model: modelId,
      },
    });

    const cleaned = cleanJsonResponse(result);
    const parsed = JSON.parse(cleaned) as {
      insights: Array<{
        learning: string;
        significance: string;
        applications?: string;
        roomSuggestion: string;
      }>;
    };

    if (!Array.isArray(parsed.insights)) {
      return NextResponse.json({ error: "Invalid response format" }, { status: 500 });
    }

    let created = 0;
    for (const insight of parsed.insights.slice(0, 10)) {
      if (!insight.learning || !insight.significance) continue;

      const roomName = insight.roomSuggestion || "General";
      let room = await prisma.mindPalaceRoom.findUnique({
        where: { name: roomName },
      });
      if (!room) {
        room = await prisma.mindPalaceRoom.create({
          data: {
            name: roomName,
            isAutoGenerated: true,
          },
        });
      }

      await prisma.insight.create({
        data: {
          roomId: room.id,
          paperId,
          learning: insight.learning,
          significance: insight.significance,
          applications: insight.applications || null,
          isAutoGenerated: true,
        },
      });
      created += 1;
    }

    return NextResponse.json({ created, total: parsed.insights.length });
  } catch (error) {
    const response = paperAccessErrorToResponse(error);
    if (response) return response;
    console.error("Distill error:", error);
    const result = error instanceof Error ? error.message : "Failed to distill";
    return NextResponse.json(
      { error: "Failed to parse LLM response", raw: result.slice(0, 500) },
      { status: 500 },
    );
  }
}
