-- CreateTable
CREATE TABLE "PaperRelation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourcePaperId" TEXT NOT NULL,
    "targetPaperId" TEXT NOT NULL,
    "relationType" TEXT NOT NULL,
    "description" TEXT,
    "confidence" REAL NOT NULL DEFAULT 0.0,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PaperRelation_sourcePaperId_fkey" FOREIGN KEY ("sourcePaperId") REFERENCES "Paper" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PaperRelation_targetPaperId_fkey" FOREIGN KEY ("targetPaperId") REFERENCES "Paper" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "PaperRelation_sourcePaperId_targetPaperId_key" ON "PaperRelation"("sourcePaperId", "targetPaperId");
