import { prisma } from "@/lib/prisma";
import { findMatchingTag } from "./normalize";

const TAG_COLORS = [
  "#EF4444", "#F59E0B", "#10B981", "#3B82F6",
  "#8B5CF6", "#EC4899", "#06B6D4",
];

/**
 * Resolve LLM-generated tag names against existing tags using fuzzy matching.
 * Creates new tags only when no similar existing tag is found.
 * Returns the tag IDs to associate with the paper.
 */
export async function resolveAndAssignTags(
  paperId: string,
  tagNames: string[]
): Promise<void> {
  const existingTags = await prisma.tag.findMany({
    select: { id: true, name: true },
  });

  for (const name of tagNames.slice(0, 3)) {
    // Try to find an existing tag that's similar enough
    const match = findMatchingTag(name, existingTags);

    let tagId: string;
    if (match) {
      tagId = match.id;
    } else {
      // Create new tag
      const tag = await prisma.tag.upsert({
        where: { name },
        create: {
          name,
          color: TAG_COLORS[Math.floor(Math.random() * TAG_COLORS.length)],
          isAutoGenerated: true,
        },
        update: {},
      });
      tagId = tag.id;
      // Add to local list so subsequent tags in same batch can match against it
      existingTags.push({ id: tag.id, name });
    }

    await prisma.paperTag
      .create({ data: { paperId, tagId } })
      .catch(() => {}); // Ignore duplicate
  }

  if (tagNames.length > 0) {
    await prisma.paper.update({
      where: { id: paperId },
      data: { categories: JSON.stringify(tagNames) },
    });
  }
}

/**
 * Get existing tag names for use in the categorize prompt.
 */
export async function getExistingTagNames(): Promise<string[]> {
  const tags = await prisma.tag.findMany({
    select: { name: true },
    orderBy: { name: "asc" },
  });
  return tags.map((t) => t.name);
}

/**
 * Get tag names split into good (reusable) and overused (to avoid),
 * based on score. Tags with score 0 and high paper counts are overused.
 */
export async function getScoredTagHints(): Promise<{
  goodTags: string[];
  overusedTags: string[];
}> {
  const tags = await prisma.tag.findMany({
    include: { _count: { select: { papers: true } } },
    orderBy: { score: "desc" },
  });

  const totalPapers = await prisma.paper.count();
  const goodTags: string[] = [];
  const overusedTags: string[] = [];

  for (const t of tags) {
    const pct = totalPapers > 0 ? t._count.papers / totalPapers : 0;
    if (pct > 0.5) {
      overusedTags.push(t.name);
    } else if (t.score > 0.3) {
      goodTags.push(t.name);
    }
  }

  return { goodTags, overusedTags };
}
