"use client";

import { Suspense, useEffect, useState, useCallback, useRef } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ModelSelector } from "@/components/llm/model-selector";
import { RemoteHostsManager } from "@/components/research/remote-hosts-manager";
import { InsightCard, type InsightData } from "@/components/mind-palace/insight-card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import {
  Save, Loader2, Zap, CheckCircle2, XCircle, Sun, Moon, Monitor,
  Plus, Trash2, Merge, Check, Tags, Sparkles, Grid3X3, Settings2,
  BrainCircuit, Server, Bot, Pencil, Power, PowerOff,
  Download, Upload, Lightbulb, Brain, ChevronRight,
} from "lucide-react";
import { toast } from "sonner";
import { useTheme } from "next-themes";

// ── Types ──────────────────────────────────────────────────────────

interface TagItem {
  id: string;
  name: string;
  color: string;
  isAutoGenerated: boolean;
  _count: { papers: number };
}

interface DuplicateTag {
  id: string;
  name: string;
  paperCount: number;
}

type DuplicateGroup = DuplicateTag[];

type PaperDuplicateState = "active" | "hidden" | "archived" | "collapsed";

interface DuplicatePaperSummary {
  id: string;
  title: string;
  authors: string | null;
  year: number | null;
  venue: string | null;
  doi: string | null;
  arxivId: string | null;
  duplicateState: PaperDuplicateState;
  collapsedIntoPaperId?: string | null;
}

interface PaperDuplicateCandidate {
  id: string;
  duplicateClass: "EXACT_IDENTIFIER" | "FUZZY";
  score: number;
  reviewStatus: "PENDING" | "ACCEPTED" | "DISMISSED" | "APPLIED";
  chosenAction: "HIDE" | "ARCHIVE" | "COLLAPSE" | null;
  autoSafeCollapse: boolean;
  winnerPaper: DuplicatePaperSummary;
  loserPaper: DuplicatePaperSummary;
  evidence: {
    reasons: string[];
    normalizedDoi?: string | null;
    normalizedArxivId?: string | null;
    normalizedTitle?: string | null;
    authorOverlap?: number;
    yearDelta?: number | null;
    safeAutoCollapse: boolean;
  };
}

interface PaperDuplicateDashboard {
  reviewCounts: Partial<Record<PaperDuplicateCandidate["reviewStatus"], number>>;
  paperCounts: {
    active: number;
    hidden: number;
    archived: number;
    collapsed: number;
  };
}

const TAG_COLORS = [
  "#EF4444", "#F59E0B", "#10B981", "#3B82F6",
  "#8B5CF6", "#EC4899", "#06B6D4", "#F97316",
];

type ProxyVendor = "openrouter" | "litellm" | "azure" | "custom" | "gateway";

const VENDOR_PRESETS: Record<ProxyVendor, { label: string; baseUrl: string; headerName: string; prefix: string }> = {
  openrouter: { label: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1", headerName: "Authorization", prefix: "Bearer " },
  litellm: { label: "LiteLLM", baseUrl: "http://localhost:4000/v1", headerName: "Authorization", prefix: "Bearer " },
  azure: { label: "Azure OpenAI", baseUrl: "https://<resource>.openai.azure.com/openai/deployments/<deployment>/v1", headerName: "api-key", prefix: "" },
  custom: { label: "Custom", baseUrl: "", headerName: "Authorization", prefix: "Bearer " },
  gateway: { label: "Gateway (multi-provider)", baseUrl: "", headerName: "X-LLM-Proxy-Calling-Service", prefix: "" },
};

type Section = "general" | "papers" | "llm" | "tags" | "remote" | "agent" | "insights";

const SECTIONS: { id: Section; label: string; icon: typeof Settings2 }[] = [
  { id: "general", label: "General", icon: Settings2 },
  { id: "papers", label: "Papers", icon: Merge },
  { id: "llm", label: "LLM", icon: BrainCircuit },
  { id: "agent", label: "Agent", icon: Bot },
  { id: "tags", label: "Tags", icon: Tags },
  { id: "insights", label: "Insights", icon: Lightbulb },
  { id: "remote", label: "Remote", icon: Server },
];

// ── Main ───────────────────────────────────────────────────────────

export default function SettingsPage() {
  return (
    <Suspense>
      <SettingsContent />
    </Suspense>
  );
}

function SettingsContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialSection = (searchParams.get("tab") as Section) || "general";
  const [section, setSection] = useState<Section>(initialSection);

  const handleSectionChange = (s: Section) => {
    setSection(s);
    router.replace(`/settings?tab=${s}`, { scroll: false });
  };

  return (
    <div className="flex gap-8 max-w-4xl mx-auto">
      {/* Left nav */}
      <nav className="w-40 shrink-0 pt-1">
        <h2 className="text-lg font-semibold mb-4">Settings</h2>
        <div className="space-y-0.5">
          {SECTIONS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => handleSectionChange(id)}
              className={`w-full flex items-center gap-2 rounded-md px-2.5 py-1.5 text-sm transition-colors ${
                section === id
                  ? "bg-accent text-foreground font-medium"
                  : "text-muted-foreground hover:text-foreground hover:bg-accent/50"
              }`}
            >
              <Icon className="h-3.5 w-3.5" />
              {label}
            </button>
          ))}
        </div>
      </nav>

      {/* Content */}
      <div className="flex-1 min-w-0 space-y-6 pb-12">
        {section === "general" && <GeneralSection />}
        {section === "papers" && <PaperDuplicatesSection />}
        {section === "llm" && <LLMSection />}
        {section === "agent" && <AgentCapabilitiesSection />}
        {section === "tags" && <TagsSection />}
        {section === "insights" && <InsightsSection />}
        {section === "remote" && <RemoteSection />}
      </div>
    </div>
  );
}

// ── Section header ─────────────────────────────────────────────────

function SectionHeader({ title, description }: { title: string; description?: string }) {
  return (
    <div className="pb-2 border-b border-border">
      <h3 className="text-base font-semibold">{title}</h3>
      {description && <p className="text-sm text-muted-foreground mt-0.5">{description}</p>}
    </div>
  );
}

// ── General ────────────────────────────────────────────────────────

function GeneralSection() {
  const { theme, setTheme } = useTheme();
  const [outputFolder, setOutputFolder] = useState("./output");
  const [outputFolderLoaded, setOutputFolderLoaded] = useState(false);
  const [outputFolderSaving, setOutputFolderSaving] = useState(false);

  useEffect(() => {
    fetch("/api/settings/output-folder")
      .then((r) => r.json())
      .then((data) => { if (data.folder) setOutputFolder(data.folder); setOutputFolderLoaded(true); })
      .catch(() => setOutputFolderLoaded(true));
  }, []);

  const handleOutputFolderSave = async () => {
    setOutputFolderSaving(true);
    try {
      const res = await fetch("/api/settings/output-folder", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ folder: outputFolder }),
      });
      if (res.ok) toast.success("Output folder saved");
      else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setOutputFolderSaving(false); }
  };

  return (
    <>
      <SectionHeader title="General" />

      {/* Theme */}
      <div className="flex items-center justify-between">
        <Label className="text-sm font-medium">Theme</Label>
        <div className="flex items-center gap-1.5">
          {([
            { value: "light", label: "Light", icon: Sun },
            { value: "dark", label: "Dark", icon: Moon },
            { value: "system", label: "System", icon: Monitor },
          ] as const).map(({ value, label, icon: Icon }) => (
            <Button
              key={value}
              variant={theme === value ? "default" : "outline"}
              size="sm"
              onClick={() => setTheme(value)}
              className="gap-1.5"
            >
              <Icon className="h-4 w-4" />
              {label}
            </Button>
          ))}
        </div>
      </div>

      {/* Output Folder */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium">Output Folder</Label>
            <p className="text-xs text-muted-foreground">Where the agent writes generated code, exports, etc.</p>
          </div>
        </div>
        {outputFolderLoaded && (
          <div className="flex items-center gap-2">
            <Input
              value={outputFolder}
              onChange={(e) => setOutputFolder(e.target.value)}
              placeholder="./output"
              className="font-mono text-sm flex-1"
            />
            <Button size="sm" onClick={handleOutputFolderSave} disabled={outputFolderSaving || !outputFolder.trim()}>
              {outputFolderSaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
              Save
            </Button>
          </div>
        )}
      </div>

      {/* Database Import/Export */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div>
          <Label className="text-sm font-medium">Database</Label>
          <p className="text-xs text-muted-foreground">Export the entire database as JSON or import from another machine.</p>
        </div>
        <DatabaseImportExport />
      </div>

      {/* About */}
      <div className="space-y-1.5 pt-4 border-t border-border">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium">Arcana</span>
          <Badge variant="secondary">v1.0.0</Badge>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed">
          Your personal research engine. Collect papers, let AI extract key insights,
          form hypotheses, run experiments, and iterate — all in one place.
          Arcana turns scattered reading into structured knowledge.
        </p>
      </div>
    </>
  );
}

function DatabaseImportExport() {
  const [exporting, setExporting] = useState(false);
  const [importing, setImporting] = useState(false);
  const [importStats, setImportStats] = useState<Record<string, number> | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExport = async () => {
    setExporting(true);
    try {
      const res = await fetch("/api/admin/db");
      if (!res.ok) throw new Error("Export failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `arcana-db-${new Date().toISOString().slice(0, 10)}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success("Database exported");
    } catch {
      toast.error("Failed to export database");
    }
    setExporting(false);
  };

  const handleImport = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const confirmed = window.confirm(
      "This will REPLACE your entire database with the imported data. All current data will be lost. Are you sure?"
    );
    if (!confirmed) {
      if (fileInputRef.current) fileInputRef.current.value = "";
      return;
    }

    setImporting(true);
    setImportStats(null);
    try {
      const text = await file.text();
      const data = JSON.parse(text);

      if (!data.version || !data.tables) {
        toast.error("Invalid export file format");
        setImporting(false);
        return;
      }

      const res = await fetch("/api/admin/db", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: text,
      });
      const result = await res.json();
      if (res.ok) {
        setImportStats(result.stats);
        const totalRows = Object.values(result.stats as Record<string, number>).reduce((a: number, b: number) => a + b, 0);
        toast.success(`Imported ${totalRows} rows across ${Object.keys(result.stats).length} tables`);
      } else {
        toast.error(result.error || "Import failed");
      }
    } catch (err) {
      toast.error("Failed to parse import file: " + (err instanceof Error ? err.message : "unknown error"));
    }
    setImporting(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" onClick={handleExport} disabled={exporting} className="gap-1.5">
          {exporting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          Export
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => fileInputRef.current?.click()}
          disabled={importing}
          className="gap-1.5"
        >
          {importing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />}
          Import
        </Button>
        <input
          ref={fileInputRef}
          type="file"
          accept=".json"
          onChange={handleImport}
          className="hidden"
        />
      </div>
      {importing && (
        <p className="text-xs text-muted-foreground">Importing... This may take a moment for large databases.</p>
      )}
      {importStats && (
        <div className="text-xs text-muted-foreground space-y-0.5">
          <p className="font-medium text-foreground">Import complete:</p>
          {Object.entries(importStats)
            .filter(([, count]) => count > 0)
            .map(([table, count]) => (
              <p key={table}>{table}: {count} rows</p>
            ))}
        </div>
      )}
    </div>
  );
}

/** Model pill input — type a model name, press Enter/comma to add as pill */
function ModelPills({ models, onChange }: { models: string[]; onChange: (models: string[]) => void }) {
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const addModel = (name: string) => {
    const trimmed = name.trim();
    if (trimmed && !models.includes(trimmed)) {
      onChange([...models, trimmed]);
    }
    setInput("");
  };

  return (
    <div
      className="flex flex-wrap gap-1 min-h-[28px] px-2 py-1 rounded-md border border-border/40 bg-background cursor-text"
      onClick={() => inputRef.current?.focus()}
    >
      {models.map(m => (
        <span key={m} className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-muted text-xs font-mono">
          {m}
          <button onClick={(e) => { e.stopPropagation(); onChange(models.filter(x => x !== m)); }}
            className="text-muted-foreground/40 hover:text-destructive">×</button>
        </span>
      ))}
      <input
        ref={inputRef}
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if ((e.key === "Enter" || e.key === ",") && input.trim()) { e.preventDefault(); addModel(input); }
          if (e.key === "Backspace" && !input && models.length > 0) { onChange(models.slice(0, -1)); }
        }}
        onBlur={() => { if (input.trim()) addModel(input); }}
        placeholder={models.length === 0 ? "Type model name, press Enter" : ""}
        className="flex-1 min-w-[100px] bg-transparent text-xs font-mono outline-none placeholder:text-muted-foreground/30"
      />
    </div>
  );
}

// ── LLM ────────────────────────────────────────────────────────────

interface KeyStatus {
  set: boolean;
  source: "db" | "env" | null;
  masked: string;
}

function LLMSection() {
  const [provider, setProvider] = useState<"openai" | "anthropic" | "proxy">("openai");
  const [modelId, setModelId] = useState("gpt-4o-mini");
  const [saving, setSaving] = useState(false);
  const [loaded, setLoaded] = useState(false);

  // API keys
  const [keyStatus, setKeyStatus] = useState<{ openai: KeyStatus; anthropic: KeyStatus; s2: KeyStatus } | null>(null);
  const [openaiKey, setOpenaiKey] = useState("");
  const [anthropicKey, setAnthropicKey] = useState("");
  const [s2Key, setS2Key] = useState("");
  const [keysSaving, setKeysSaving] = useState(false);

  // Proxy
  const [proxyEnabled, setProxyEnabled] = useState(false);
  const [proxyVendor, setProxyVendor] = useState<ProxyVendor>("openrouter");
  const [proxyBaseUrl, setProxyBaseUrl] = useState("");
  const [proxyAnthropicBaseUrl, setProxyAnthropicBaseUrl] = useState("");
  const [proxyRoutes, setProxyRoutes] = useState<Array<{ provider: string; path: string; targetUrl: string; models: string }>>([
    { provider: "openai", path: "openai/v1", targetUrl: "", models: "" },
    { provider: "anthropic", path: "anthropic/v1", targetUrl: "https://api.anthropic.com", models: "" },
  ]);
  const [routeTestResults, setRouteTestResults] = useState<Record<number, { ok: boolean; message: string } | null>>({});
  const [routeTesting, setRouteTesting] = useState<number | null>(null);
  const [proxyApiKey, setProxyApiKey] = useState("");
  const [proxyHeaderName, setProxyHeaderName] = useState("Authorization");
  const [proxyHeaderValue, setProxyHeaderValue] = useState("");
  const [proxyModels, setProxyModels] = useState("");
  const [proxyContextWindow, setProxyContextWindow] = useState("128000");
  const [proxyMaxTokens, setProxyMaxTokens] = useState("4096");
  const [proxySaving, setProxySaving] = useState(false);
  const [proxyTesting, setProxyTesting] = useState(false);
  const [proxyTestResult, setProxyTestResult] = useState<{ ok: boolean; message: string } | null>(null);
  const [proxyLoaded, setProxyLoaded] = useState(false);
  const [proxyHasExistingKey, setProxyHasExistingKey] = useState(false);

  useEffect(() => {
    fetch("/api/settings/default-model")
      .then((r) => r.json())
      .then((data) => { if (data.provider) setProvider(data.provider); if (data.modelId) setModelId(data.modelId); setLoaded(true); })
      .catch(() => setLoaded(true));
  }, []);

  useEffect(() => {
    fetch("/api/settings/api-keys")
      .then((r) => r.json())
      .then((data) => setKeyStatus(data))
      .catch(() => {});
  }, []);

  useEffect(() => {
    fetch("/api/settings/proxy")
      .then((r) => r.json())
      .then((data) => {
        setProxyEnabled(data.enabled);
        setProxyVendor(data.vendor || "openrouter");
        setProxyBaseUrl(data.baseUrl || "");
        setProxyAnthropicBaseUrl(data.anthropicBaseUrl || "");
        setProxyHeaderName(data.headerName || "Authorization");
        setProxyHeaderValue(data.headerValue || "");
        setProxyModels(data.modelId || "");
        setProxyContextWindow(String(data.contextWindow || 128000));
        setProxyMaxTokens(String(data.maxTokens || 4096));
        setProxyHasExistingKey(!!data.apiKey);
        if (data.routes && Array.isArray(data.routes) && data.routes.length > 0) {
          setProxyRoutes(data.routes.map((r: { provider: string; path: string; targetUrl?: string; models?: string[] }) => ({
            provider: r.provider,
            path: r.path || "",
            targetUrl: r.targetUrl || "",
            models: Array.isArray(r.models) ? r.models.join(", ") : "",
          })));
        }
        setProxyLoaded(true);
      })
      .catch(() => setProxyLoaded(true));
  }, []);

  const handleModelSave = async () => {
    setSaving(true);
    try {
      const res = await fetch("/api/settings/default-model", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ provider, modelId }),
      });
      if (res.ok) toast.success("Default model saved");
      else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setSaving(false); }
  };

  const handleKeysSave = async () => {
    setKeysSaving(true);
    try {
      const body: Record<string, string> = {};
      if (openaiKey) body.openai = openaiKey;
      if (anthropicKey) body.anthropic = anthropicKey;
      if (s2Key) body.s2 = s2Key;
      const res = await fetch("/api/settings/api-keys", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (res.ok) {
        toast.success("API keys saved");
        setOpenaiKey("");
        setAnthropicKey("");
        // Refresh status
        const statusRes = await fetch("/api/settings/api-keys");
        if (statusRes.ok) setKeyStatus(await statusRes.json());
      } else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setKeysSaving(false); }
  };

  const handleVendorChange = useCallback((vendor: ProxyVendor) => {
    setProxyVendor(vendor);
    const preset = VENDOR_PRESETS[vendor];
    if (vendor !== "custom") {
      setProxyBaseUrl(preset.baseUrl);
      setProxyHeaderName(preset.headerName);
    }
    setProxyTestResult(null);
  }, []);

  const buildHeaderValue = useCallback(() => {
    if (proxyVendor === "custom" || proxyVendor === "gateway") return proxyHeaderValue;
    const preset = VENDOR_PRESETS[proxyVendor];
    return preset.prefix + proxyApiKey;
  }, [proxyVendor, proxyApiKey, proxyHeaderValue]);

  const handleProxySave = async () => {
    setProxySaving(true);
    try {
      const res = await fetch("/api/settings/proxy", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          vendor: proxyVendor, baseUrl: proxyBaseUrl,
          anthropicBaseUrl: proxyAnthropicBaseUrl, apiKey: proxyApiKey || null,
          headerName: proxyHeaderName,
          headerValue: (proxyVendor === "custom" || proxyVendor === "gateway") ? proxyHeaderValue : "",
          modelId: proxyVendor === "gateway"
            ? proxyRoutes.flatMap(r => r.models.split(",").map(m => m.trim())).filter(Boolean).join(", ")
            : proxyModels,
          contextWindow: proxyContextWindow, maxTokens: proxyMaxTokens,
          routes: proxyVendor === "gateway"
            ? proxyRoutes.filter(r => r.path.trim()).map(r => ({
                provider: r.provider,
                path: r.path.trim(),
                targetUrl: r.targetUrl.trim() || undefined,
                models: r.models.split(",").map(m => m.trim()).filter(Boolean),
              }))
            : undefined,
        }),
      });
      if (res.ok) {
        toast.success("Proxy settings saved");
        if (proxyApiKey) { setProxyHasExistingKey(true); setProxyApiKey(""); }
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || "Failed to save proxy settings");
      }
    } catch { toast.error("Failed to save proxy settings"); }
    finally { setProxySaving(false); }
  };

  const handleProxyTest = async () => {
    setProxyTesting(true);
    setProxyTestResult(null);
    try {
      const headerValue = buildHeaderValue();
      // Get first model: from routes in gateway mode, from models field otherwise
      const allModels = proxyVendor === "gateway"
        ? proxyRoutes.flatMap(r => r.models.split(",").map(m => m.trim())).filter(Boolean)
        : proxyModels.split(",").map(s => s.trim()).filter(Boolean);
      const firstModel = allModels[0] || "gpt-3.5-turbo";
      const routes = proxyVendor === "gateway"
        ? proxyRoutes.filter(r => r.path.trim()).map(r => ({
            provider: r.provider, path: r.path.trim(),
            targetUrl: r.targetUrl.trim() || undefined,
            models: r.models.split(",").map(m => m.trim()).filter(Boolean),
          }))
        : undefined;
      const res = await fetch("/api/settings/proxy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ baseUrl: proxyBaseUrl, anthropicBaseUrl: proxyAnthropicBaseUrl, headerName: proxyHeaderName, headerValue, modelId: firstModel, vendor: proxyVendor, routes }),
      });
      const data = await res.json();
      if (data.ok) setProxyTestResult({ ok: true, message: `Connected! Model: ${firstModel}` });
      else setProxyTestResult({ ok: false, message: data.error || "Connection failed" });
    } catch (e) {
      setProxyTestResult({ ok: false, message: e instanceof Error ? e.message : "Connection failed" });
    } finally { setProxyTesting(false); }
  };

  return (
    <>
      <SectionHeader title="LLM" description="Choose a model, enter your API keys, or connect through a proxy." />

      {/* Model selection */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="text-sm font-medium">Model</Label>
        </div>
        {loaded && (
          <div className="flex items-end gap-3">
            <ModelSelector provider={provider} modelId={modelId} onProviderChange={setProvider} onModelChange={setModelId} />
            <Button size="sm" onClick={handleModelSave} disabled={saving}>
              {saving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
              Save
            </Button>
          </div>
        )}
        <p className="text-xs text-muted-foreground">
          Used for summaries, tagging, chat, and general AI features.
        </p>
      </div>

      {/* Research agent model tiers */}
      <ResearchModelTiers />

      {/* API Keys */}
      <div className="space-y-3 pt-4 border-t border-border">
        <Label className="text-sm font-medium">API Keys</Label>
        <div className="grid gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Label className="text-xs">OpenAI</Label>
              {keyStatus?.openai.set && (
                <span className="text-[10px] text-emerald-600 dark:text-emerald-400">
                  {keyStatus.openai.masked}
                  {keyStatus.openai.source === "env" && " (from .env)"}
                </span>
              )}
            </div>
            <Input
              type="password"
              value={openaiKey}
              onChange={(e) => setOpenaiKey(e.target.value)}
              placeholder={keyStatus?.openai.set ? "Enter new key to replace" : "sk-..."}
              className="font-mono text-sm"
            />
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Label className="text-xs">Anthropic</Label>
              {keyStatus?.anthropic.set && (
                <span className="text-[10px] text-emerald-600 dark:text-emerald-400">
                  {keyStatus.anthropic.masked}
                  {keyStatus.anthropic.source === "env" && " (from .env)"}
                </span>
              )}
            </div>
            <Input
              type="password"
              value={anthropicKey}
              onChange={(e) => setAnthropicKey(e.target.value)}
              placeholder={keyStatus?.anthropic.set ? "Enter new key to replace" : "sk-ant-..."}
              className="font-mono text-sm"
            />
          </div>
        </div>
        <Button size="sm" onClick={handleKeysSave} disabled={keysSaving || (!openaiKey && !anthropicKey && !s2Key)}>
          {keysSaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
          Save Keys
        </Button>
      </div>

      {/* Proxy */}
      <div className="space-y-3 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Zap className="h-3.5 w-3.5" /> Proxy</Label>
            <p className="text-xs text-muted-foreground mt-0.5">Route requests through OpenRouter, LiteLLM, or a custom endpoint.</p>
          </div>
          <Button variant={proxyEnabled ? "default" : "outline"} size="sm" onClick={() => setProxyEnabled(!proxyEnabled)}>
            {proxyEnabled ? "Enabled" : "Disabled"}
          </Button>
        </div>

        {proxyLoaded && proxyEnabled && (
          <div className="space-y-3 rounded-md border border-border p-4">
            <div className="space-y-1">
              <Label className="text-xs">Vendor</Label>
              <Select value={proxyVendor} onValueChange={(v) => handleVendorChange(v as ProxyVendor)}>
                <SelectTrigger className="w-[200px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="openrouter">OpenRouter</SelectItem>
                  <SelectItem value="litellm">LiteLLM</SelectItem>
                  <SelectItem value="azure">Azure OpenAI</SelectItem>
                  <SelectItem value="custom">Custom</SelectItem>
                  <SelectItem value="gateway">Gateway (multi-provider)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label className="text-xs">{proxyVendor === "gateway" ? "Gateway Base URL" : "Base URL"}</Label>
              <Input value={proxyBaseUrl} onChange={(e) => setProxyBaseUrl(e.target.value)} placeholder={proxyVendor === "gateway" ? "https://proxy.corp.com/api" : "https://openrouter.ai/api/v1"} className="font-mono text-sm" />
              {proxyVendor === "gateway" && <p className="text-[11px] text-muted-foreground/50">The gateway base — provider paths are appended from routes below.</p>}
            </div>

            {/* Auth — always shown for gateway and custom, hidden for presets (they use API key) */}
            {(proxyVendor === "custom" || proxyVendor === "gateway") && (
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <Label className="text-xs">Auth Header Name</Label>
                  <Input value={proxyHeaderName} onChange={(e) => setProxyHeaderName(e.target.value)} placeholder="Authorization" className="font-mono text-sm" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Auth Header Value</Label>
                  <Input type="password" value={proxyHeaderValue} onChange={(e) => setProxyHeaderValue(e.target.value)} placeholder="Bearer sk-..." className="font-mono text-sm" />
                </div>
              </div>
            )}

            {/* API Key — for simple vendors */}
            {proxyVendor !== "gateway" && proxyVendor !== "custom" && (
              <div className="space-y-1">
                <Label className="text-xs">API Key</Label>
                <Input type="password" value={proxyApiKey} onChange={(e) => setProxyApiKey(e.target.value)} placeholder={proxyHasExistingKey ? "Saved — leave blank to keep" : "sk-or-..."} className="font-mono text-sm" />
              </div>
            )}

            {/* Gateway: provider routes */}
            {proxyVendor === "gateway" && (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-xs">Provider Routes</Label>
                    <p className="text-[11px] text-muted-foreground/50">Each provider gets its own path. The SDK appends its own suffix.</p>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => {
                    setProxyRoutes([...proxyRoutes, { provider: "", path: "", targetUrl: "", models: "" }]);
                  }}>+ Add Route</Button>
                </div>
                <div className="space-y-3">
                  {proxyRoutes.map((route, i) => (
                    <div key={i} className="rounded-md border border-border/40 p-3 space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <select value={route.provider} onChange={(e) => {
                            const updated = [...proxyRoutes];
                            updated[i] = { ...updated[i], provider: e.target.value };
                            setProxyRoutes(updated);
                          }} className="font-mono text-xs w-36 h-7 rounded-md border border-input bg-background px-2">
                            <option value="">Select...</option>
                            <option value="openai">openai</option>
                            <option value="anthropic">anthropic</option>
                            <option value="google">google</option>
                            <option value="openai-responses">openai-responses</option>
                          </select>
                          <span className="text-[10px] text-muted-foreground">provider</span>
                        </div>
                        <div className="flex items-center gap-1">
                          <Button variant="ghost" size="sm" className="h-7 px-2 text-[11px]"
                            disabled={routeTesting === i || !route.models.trim() || !route.path.trim()}
                            onClick={async () => {
                              setRouteTesting(i);
                              setRouteTestResults(prev => ({ ...prev, [i]: null }));
                              try {
                                const headerValue = buildHeaderValue();
                                const models = route.models.split(",").map(m => m.trim()).filter(Boolean);
                                if (models.length === 0) { setRouteTestResults(prev => ({ ...prev, [i]: { ok: false, message: "No models" } })); setRouteTesting(null); return; }
                                // Test ALL models sequentially
                                const results: string[] = [];
                                let allOk = true;
                                for (const modelId of models) {
                                  setRouteTestResults(prev => ({ ...prev, [i]: { ok: true, message: `Testing ${modelId}...` } }));
                                  try {
                                    const res = await fetch("/api/settings/proxy", {
                                      method: "POST", headers: { "Content-Type": "application/json" },
                                      body: JSON.stringify({
                                        baseUrl: proxyBaseUrl, headerName: proxyHeaderName, headerValue,
                                        modelId, vendor: "gateway",
                                        routes: [{ provider: route.provider, path: route.path.trim(), targetUrl: route.targetUrl.trim() || undefined, models }],
                                      }),
                                    });
                                    const data = await res.json();
                                    if (data.ok) { results.push(`${modelId} ✓`); }
                                    else { results.push(`${modelId} ✗`); allOk = false; }
                                  } catch { results.push(`${modelId} ✗`); allOk = false; }
                                }
                                setRouteTestResults(prev => ({ ...prev, [i]: { ok: allOk, message: results.join("  ") } }));
                              } catch (e) {
                                setRouteTestResults(prev => ({ ...prev, [i]: { ok: false, message: e instanceof Error ? e.message : "Failed" } }));
                              }
                              setRouteTesting(null);
                            }}>
                            {routeTesting === i ? <Loader2 className="h-3 w-3 animate-spin" /> : <Zap className="h-3 w-3" />}
                            <span className="ml-1">Test</span>
                          </Button>
                          <Button variant="ghost" size="sm" className="h-7 w-7 px-0 text-muted-foreground/40 hover:text-destructive"
                            onClick={() => {
                              setProxyRoutes(proxyRoutes.filter((_, j) => j !== i));
                              setRouteTestResults(prev => { const next = { ...prev }; delete next[i]; return next; });
                            }}>
                            <XCircle className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>
                      <div className="grid grid-cols-3 gap-2">
                        <div>
                          <Label className="text-[10px] text-muted-foreground">Path</Label>
                          <Input value={route.path} onChange={(e) => {
                            const updated = [...proxyRoutes];
                            updated[i] = { ...updated[i], path: e.target.value };
                            setProxyRoutes(updated);
                          }} placeholder="openai/v1" className="font-mono text-xs h-7" />
                        </div>
                        <div>
                          <Label className="text-[10px] text-muted-foreground">Target URL <span className="text-muted-foreground/30">(optional)</span></Label>
                          <Input value={route.targetUrl} onChange={(e) => {
                            const updated = [...proxyRoutes];
                            updated[i] = { ...updated[i], targetUrl: e.target.value };
                            setProxyRoutes(updated);
                          }} placeholder="" className="font-mono text-xs h-7" />
                        </div>
                        <div>
                          <Label className="text-[10px] text-muted-foreground">Models</Label>
                          <ModelPills
                            models={route.models.split(",").map(m => m.trim()).filter(Boolean)}
                            onChange={(models) => {
                              const updated = [...proxyRoutes];
                              updated[i] = { ...updated[i], models: models.join(", ") };
                              setProxyRoutes(updated);
                            }}
                          />
                        </div>
                      </div>
                      {routeTestResults[i] && (
                        <p className={`text-[11px] ${routeTestResults[i]!.ok ? "text-emerald-600" : "text-red-500"}`}>
                          {routeTestResults[i]!.message}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Anthropic URL — only for non-gateway single-URL modes */}
            {proxyVendor !== "gateway" && (
              <div className="space-y-1">
                <Label className="text-xs">Anthropic Endpoint URL</Label>
                <Input value={proxyAnthropicBaseUrl} onChange={(e) => setProxyAnthropicBaseUrl(e.target.value)} placeholder="Auto-derived if blank" className="font-mono text-sm" />
                <p className="text-[11px] text-muted-foreground/50">For Anthropic models. Leave blank to auto-derive from Base URL.</p>
              </div>
            )}

            {/* Models — for non-gateway modes */}
            {proxyVendor !== "gateway" && (
              <div className="space-y-1">
                <Label className="text-xs">Models</Label>
                <Input value={proxyModels} onChange={(e) => setProxyModels(e.target.value)} placeholder="gpt-4o, claude-sonnet-4-6" className="font-mono text-sm" />
                <p className="text-[11px] text-muted-foreground">Comma-separated model IDs. These appear in the model picker above.</p>
              </div>
            )}

            <div className="flex gap-3">
              <div className="space-y-1 flex-1">
                <Label className="text-xs">Context Window</Label>
                <Input type="number" value={proxyContextWindow} onChange={(e) => setProxyContextWindow(e.target.value)} placeholder="128000" />
              </div>
              <div className="space-y-1 flex-1">
                <Label className="text-xs">Max Output Tokens</Label>
                <Input type="number" value={proxyMaxTokens} onChange={(e) => setProxyMaxTokens(e.target.value)} placeholder="4096" />
              </div>
            </div>

            {proxyTestResult && (
              <div className={`flex items-start gap-2 rounded-md p-2.5 text-xs ${
                proxyTestResult.ok
                  ? "bg-green-50 text-green-800 dark:bg-green-950 dark:text-green-200"
                  : "bg-red-50 text-red-800 dark:bg-red-950 dark:text-red-200"
              }`}>
                {proxyTestResult.ok ? <CheckCircle2 className="h-3.5 w-3.5 mt-0.5 shrink-0" /> : <XCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" />}
                <span className="break-all">{proxyTestResult.message}</span>
              </div>
            )}

            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleProxyTest} disabled={proxyTesting || !proxyBaseUrl || (proxyVendor !== "gateway" && !proxyModels) || (proxyVendor === "gateway" && !proxyRoutes.some(r => r.models.trim()))}>
                {proxyTesting ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Zap className="mr-1.5 h-3.5 w-3.5" />}
                Test
              </Button>
              <Button size="sm" onClick={handleProxySave} disabled={proxySaving}>
                {proxySaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
                Save Proxy
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* External services */}
      <div className="space-y-3 pt-4 border-t border-border">
        <div>
          <Label className="text-sm font-medium">External Services</Label>
          <p className="text-xs text-muted-foreground mt-0.5">Optional keys for third-party services used by the import pipeline.</p>
        </div>
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Label className="text-xs">Semantic Scholar</Label>
            {keyStatus?.s2.set && (
              <span className="text-[10px] text-emerald-600 dark:text-emerald-400">
                {keyStatus.s2.masked}
                {keyStatus.s2.source === "env" && " (from .env)"}
              </span>
            )}
          </div>
          <Input
            type="password"
            value={s2Key}
            onChange={(e) => setS2Key(e.target.value)}
            placeholder={keyStatus?.s2.set ? "Enter new key to replace" : "Optional — higher rate limits for paper search"}
            className="font-mono text-sm"
          />
          <p className="text-[10px] text-muted-foreground">
            Without a key, paper search uses public rate limits (1 req/s). Get one at <a href="https://www.semanticscholar.org/product/api#api-key-form" target="_blank" rel="noopener noreferrer" className="underline">semanticscholar.org</a>.
          </p>
        </div>
        {s2Key && (
          <Button size="sm" onClick={handleKeysSave} disabled={keysSaving}>
            {keysSaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
            Save
          </Button>
        )}
      </div>
    </>
  );
}

// ── Research Model Tiers ────────────────────────────────────────────

const ROLE_TIERS: { role: string; tier: "reasoning" | "standard" }[] = [
  { role: "Lead agent", tier: "reasoning" },
  { role: "Reviewer", tier: "reasoning" },
  { role: "Reproducer", tier: "reasoning" },
  { role: "Synthesizer", tier: "reasoning" },
  { role: "Architect", tier: "reasoning" },
  { role: "Scout", tier: "standard" },
  { role: "Analyst", tier: "standard" },
  { role: "Experimenter", tier: "standard" },
];

function ResearchModelTiers() {
  const [reasoning, setReasoning] = useState("");
  const [standard, setStandard] = useState("");
  const [loaded, setLoaded] = useState(false);
  const [saving, setSaving] = useState(false);
  const [proxyModels, setProxyModels] = useState<string[]>([]);

  useEffect(() => {
    fetch("/api/settings/model-tiers")
      .then((r) => r.json())
      .then((data) => {
        if (data.reasoning) setReasoning(data.reasoning);
        if (data.standard) setStandard(data.standard);
        setLoaded(true);
      })
      .catch(() => setLoaded(true));

    // Load proxy models for dropdown options
    fetch("/api/settings/proxy-status")
      .then((r) => r.json())
      .then((data) => {
        if (Array.isArray(data.models) && data.models.length > 0) {
          setProxyModels(data.models.map((m: string | { id: string }) => typeof m === "string" ? m : m.id));
        }
      })
      .catch(() => {});
  }, []);

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await fetch("/api/settings/model-tiers", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reasoning, standard }),
      });
      if (res.ok) toast.success("Tier models saved");
      else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setSaving(false); }
  };

  if (!loaded) return null;

  const baseOptions = proxyModels.length > 0 ? proxyModels : [
    "claude-opus-4-6", "claude-sonnet-4-6", "claude-haiku-4-5-20251001",
    "gpt-4o", "gpt-4o-mini",
  ];
  // Ensure current values are always in the list
  const modelOptions = Array.from(new Set([...baseOptions, reasoning, standard].filter(Boolean)));

  return (
    <div className="space-y-3 pt-4 border-t border-border">
      <div>
        <Label className="text-sm font-medium">Research Agent Models</Label>
        <p className="text-xs text-muted-foreground mt-0.5">
          Different agent roles use different model tiers. Only applies when using a proxy provider.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Reasoning tier</Label>
          <Select value={reasoning} onValueChange={setReasoning}>
            <SelectTrigger className="h-8 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {modelOptions.map((m) => (
                <SelectItem key={m} value={m} className="text-xs">{m}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <p className="text-[10px] text-muted-foreground/60">
            {ROLE_TIERS.filter((r) => r.tier === "reasoning").map((r) => r.role).join(", ")}
          </p>
        </div>

        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Standard tier</Label>
          <Select value={standard} onValueChange={setStandard}>
            <SelectTrigger className="h-8 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {modelOptions.map((m) => (
                <SelectItem key={m} value={m} className="text-xs">{m}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <p className="text-[10px] text-muted-foreground/60">
            {ROLE_TIERS.filter((r) => r.tier === "standard").map((r) => r.role).join(", ")}
          </p>
        </div>
      </div>

      <Button size="sm" onClick={handleSave} disabled={saving}>
        {saving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
        Save
      </Button>
    </div>
  );
}

// ── Papers ─────────────────────────────────────────────────────────

function formatDuplicateReason(reason: string): string {
  switch (reason) {
    case "exact_doi":
      return "Exact DOI match";
    case "exact_arxiv":
      return "Exact arXiv match";
    case "title_author_match":
      return "Title + author match";
    default:
      return reason.replace(/_/g, " ");
  }
}

function PaperDuplicatesSection() {
  const [dashboard, setDashboard] = useState<PaperDuplicateDashboard | null>(null);
  const [candidates, setCandidates] = useState<PaperDuplicateCandidate[]>([]);
  const [loading, setLoading] = useState(true);
  const [scanning, setScanning] = useState(false);
  const [applying, setApplying] = useState(false);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [actionById, setActionById] = useState<Record<string, "HIDE" | "ARCHIVE" | "COLLAPSE">>({});

  const loadDuplicates = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/papers/duplicates");
      if (!res.ok) throw new Error("Failed to load duplicates");
      const data = await res.json();
      setDashboard(data.dashboard);
      setCandidates(data.candidates);
      setActionById(
        Object.fromEntries(
          (data.candidates as PaperDuplicateCandidate[]).map((candidate) => [
            candidate.id,
            candidate.chosenAction ?? (candidate.duplicateClass === "EXACT_IDENTIFIER" ? "COLLAPSE" : "HIDE"),
          ]),
        ),
      );
    } catch {
      toast.error("Failed to load paper duplicates");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadDuplicates();
  }, [loadDuplicates]);

  const scanDuplicates = async () => {
    setScanning(true);
    try {
      const res = await fetch("/api/papers/duplicates", { method: "POST" });
      if (!res.ok) throw new Error();
      const summary = await res.json();
      toast.success(
        `Scan complete: ${summary.persistedCandidateCount} candidates, ${summary.safeAutoCollapseCount} safe auto-collapse`,
      );
      await loadDuplicates();
    } catch {
      toast.error("Failed to scan paper duplicates");
    } finally {
      setScanning(false);
    }
  };

  const applyAccepted = async () => {
    setApplying(true);
    try {
      const res = await fetch("/api/papers/duplicates/apply", { method: "POST" });
      if (!res.ok) throw new Error();
      const result = await res.json();
      toast.success(`Applied ${result.applied} duplicate decisions`);
      await loadDuplicates();
    } catch {
      toast.error("Failed to apply duplicate decisions");
    } finally {
      setApplying(false);
    }
  };

  const reviewCandidate = async (
    candidate: PaperDuplicateCandidate,
    reviewStatus: "ACCEPTED" | "DISMISSED",
  ) => {
    setSavingId(candidate.id);
    try {
      const res = await fetch("/api/papers/duplicates", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          candidateId: candidate.id,
          reviewStatus,
          chosenAction: reviewStatus === "ACCEPTED" ? actionById[candidate.id] : null,
        }),
      });
      if (!res.ok) throw new Error();
      toast.success(reviewStatus === "ACCEPTED" ? "Decision saved" : "Candidate dismissed");
      await loadDuplicates();
    } catch {
      toast.error("Failed to update duplicate candidate");
    } finally {
      setSavingId(null);
    }
  };

  const pendingCandidates = candidates.filter((candidate) => candidate.reviewStatus === "PENDING");
  const acceptedCandidates = candidates.filter((candidate) => candidate.reviewStatus === "ACCEPTED");

  return (
    <>
      <SectionHeader
        title="Paper Duplicates"
        description="Scan for duplicate papers, review non-safe candidates, and apply hide/archive/collapse without destructive merge semantics."
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Card><CardContent className="pt-4"><p className="text-xs text-muted-foreground">Active</p><p className="text-2xl font-semibold">{dashboard?.paperCounts.active ?? 0}</p></CardContent></Card>
        <Card><CardContent className="pt-4"><p className="text-xs text-muted-foreground">Hidden</p><p className="text-2xl font-semibold">{dashboard?.paperCounts.hidden ?? 0}</p></CardContent></Card>
        <Card><CardContent className="pt-4"><p className="text-xs text-muted-foreground">Archived</p><p className="text-2xl font-semibold">{dashboard?.paperCounts.archived ?? 0}</p></CardContent></Card>
        <Card><CardContent className="pt-4"><p className="text-xs text-muted-foreground">Collapsed</p><p className="text-2xl font-semibold">{dashboard?.paperCounts.collapsed ?? 0}</p></CardContent></Card>
      </div>

      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" onClick={scanDuplicates} disabled={scanning}>
          {scanning ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Merge className="mr-1.5 h-3.5 w-3.5" />}
          Scan library
        </Button>
        <Button size="sm" onClick={applyAccepted} disabled={applying || acceptedCandidates.length === 0}>
          {applying ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Check className="mr-1.5 h-3.5 w-3.5" />}
          Apply accepted
        </Button>
        <p className="text-xs text-muted-foreground">
          Pending: {dashboard?.reviewCounts.PENDING ?? 0} · Accepted: {dashboard?.reviewCounts.ACCEPTED ?? 0} · Applied: {dashboard?.reviewCounts.APPLIED ?? 0}
        </p>
      </div>

      {loading ? (
        <div className="space-y-2">
          <Skeleton className="h-24 w-full" />
          <Skeleton className="h-24 w-full" />
        </div>
      ) : pendingCandidates.length === 0 && acceptedCandidates.length === 0 ? (
        <div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">
          No paper duplicate candidates yet. Run a scan to populate this review queue.
        </div>
      ) : (
        <div className="space-y-3">
          {[...pendingCandidates, ...acceptedCandidates].map((candidate) => (
            <div key={candidate.id} className="rounded-lg border p-4 space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant={candidate.duplicateClass === "EXACT_IDENTIFIER" ? "default" : "secondary"}>
                  {candidate.duplicateClass === "EXACT_IDENTIFIER" ? "Exact ID" : "Fuzzy"}
                </Badge>
                {candidate.autoSafeCollapse && <Badge variant="outline">Safe auto-collapse</Badge>}
                <Badge variant="outline">{candidate.reviewStatus.toLowerCase()}</Badge>
                <span className="text-xs text-muted-foreground">score {candidate.score.toFixed(2)}</span>
              </div>

              <div className="grid gap-3 md:grid-cols-2">
                <div className="rounded-md bg-emerald-50/70 p-3 dark:bg-emerald-950/20">
                  <p className="text-xs font-medium text-emerald-700 dark:text-emerald-300">Winner</p>
                  <p className="text-sm font-medium">{candidate.winnerPaper.title}</p>
                  <p className="text-xs text-muted-foreground">{candidate.winnerPaper.year ?? "Unknown year"}</p>
                </div>
                <div className="rounded-md bg-amber-50/70 p-3 dark:bg-amber-950/20">
                  <p className="text-xs font-medium text-amber-700 dark:text-amber-300">Loser</p>
                  <p className="text-sm font-medium">{candidate.loserPaper.title}</p>
                  <p className="text-xs text-muted-foreground">{candidate.loserPaper.year ?? "Unknown year"}</p>
                </div>
              </div>

              <div className="flex flex-wrap gap-2 text-xs text-muted-foreground">
                {candidate.evidence.reasons.map((reason) => (
                  <Badge key={reason} variant="outline">{formatDuplicateReason(reason)}</Badge>
                ))}
                {candidate.evidence.authorOverlap != null && (
                  <span>author overlap {(candidate.evidence.authorOverlap * 100).toFixed(0)}%</span>
                )}
                {candidate.evidence.yearDelta != null && (
                  <span>year delta {candidate.evidence.yearDelta}</span>
                )}
              </div>

              <div className="flex flex-wrap items-center gap-2">
                <Select
                  value={actionById[candidate.id] ?? "HIDE"}
                  onValueChange={(value) =>
                    setActionById((prev) => ({
                      ...prev,
                      [candidate.id]: value as "HIDE" | "ARCHIVE" | "COLLAPSE",
                    }))
                  }
                >
                  <SelectTrigger className="h-8 w-[180px] text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="HIDE" className="text-xs">Hide loser</SelectItem>
                    <SelectItem value="ARCHIVE" className="text-xs">Archive loser</SelectItem>
                    <SelectItem value="COLLAPSE" className="text-xs">Collapse into winner</SelectItem>
                  </SelectContent>
                </Select>

                <Button
                  size="sm"
                  variant="outline"
                  disabled={savingId === candidate.id}
                  onClick={() => reviewCandidate(candidate, "DISMISSED")}
                >
                  {savingId === candidate.id ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : null}
                  Dismiss
                </Button>
                <Button
                  size="sm"
                  disabled={savingId === candidate.id}
                  onClick={() => reviewCandidate(candidate, "ACCEPTED")}
                >
                  {savingId === candidate.id ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : null}
                  Accept
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </>
  );
}

// ── Tags ───────────────────────────────────────────────────────────

function TagsSection() {
  const [tags, setTags] = useState<TagItem[]>([]);
  const [newTagName, setNewTagName] = useState("");
  const [newTagColor, setNewTagColor] = useState(TAG_COLORS[0]);
  const [duplicates, setDuplicates] = useState<DuplicateGroup[]>([]);
  const [dupsLoading, setDupsLoading] = useState(false);
  const [dupsScanned, setDupsScanned] = useState(false);
  const [mergingGroup, setMergingGroup] = useState<number | null>(null);
  const [selectedTargets, setSelectedTargets] = useState<Record<number, string>>({});
  const [cleanupRunning, setCleanupRunning] = useState(false);
  const [cleanupResult, setCleanupResult] = useState<{
    orphansDeleted: string[];
    singletonsMerged: { from: string; into: string }[];
    singletonsKept: string[];
    scoresUpdated: number;
    tagsBefore: number;
    tagsAfter: number;
  } | null>(null);
  const [clusterRunning, setClusterRunning] = useState(false);
  const [clusterResult, setClusterResult] = useState<{
    clusters: { name: string; description: string; tagCount: number }[];
    unassigned: string[];
  } | null>(null);

  const fetchTags = useCallback(async () => {
    const res = await fetch("/api/tags");
    if (res.ok) setTags(await res.json());
  }, []);

  useEffect(() => { fetchTags(); }, [fetchTags]);

  const createTag = async () => {
    if (!newTagName.trim()) return;
    const res = await fetch("/api/tags", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newTagName.trim(), color: newTagColor }),
    });
    if (res.ok) { toast.success("Tag created"); setNewTagName(""); fetchTags(); }
    else toast.error("Failed to create tag");
  };

  const deleteTag = async (id: string) => {
    if (!confirm("Delete this tag?")) return;
    await fetch(`/api/tags/${id}`, { method: "DELETE" });
    toast.success("Tag deleted");
    fetchTags();
  };

  const findDuplicates = async () => {
    setDupsLoading(true);
    try {
      const res = await fetch("/api/tags/duplicates");
      const groups: DuplicateGroup[] = await res.json();
      setDuplicates(groups);
      setDupsScanned(true);
      const targets: Record<number, string> = {};
      groups.forEach((group, i) => {
        const best = group.reduce((a, b) => (b.paperCount > a.paperCount ? b : a));
        targets[i] = best.id;
      });
      setSelectedTargets(targets);
      if (groups.length === 0) toast.success("No duplicate tags found");
    } catch { toast.error("Failed to scan for duplicates"); }
    setDupsLoading(false);
  };

  const mergeGroup = async (groupIndex: number) => {
    const group = duplicates[groupIndex];
    const targetId = selectedTargets[groupIndex];
    if (!targetId) return;
    const sourceIds = group.filter((t) => t.id !== targetId).map((t) => t.id);
    if (sourceIds.length === 0) return;
    setMergingGroup(groupIndex);
    try {
      const res = await fetch("/api/tags/merge", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId, sourceIds }),
      });
      if (res.ok) { toast.success("Tags merged"); setDuplicates((prev) => prev.filter((_, i) => i !== groupIndex)); fetchTags(); }
      else toast.error("Failed to merge tags");
    } catch { toast.error("Failed to merge tags"); }
    setMergingGroup(null);
  };

  const mergeAll = async () => {
    for (let i = 0; i < duplicates.length; i++) await mergeGroup(i);
  };

  const runSmartCleanup = async () => {
    setCleanupRunning(true);
    setCleanupResult(null);
    try {
      const res = await fetch("/api/tags/cleanup", { method: "POST" });
      if (res.ok) {
        const result = await res.json();
        setCleanupResult(result);
        toast.success(`Cleanup done: ${result.tagsBefore} → ${result.tagsAfter} tags`);
        fetchTags();
      } else toast.error("Cleanup failed");
    } catch { toast.error("Cleanup failed"); }
    setCleanupRunning(false);
  };

  const runGenerateClusters = async () => {
    setClusterRunning(true);
    setClusterResult(null);
    try {
      const res = await fetch("/api/tags/clusters", { method: "POST" });
      if (res.ok) {
        const result = await res.json();
        setClusterResult(result);
        toast.success(`Generated ${result.clusters.length} clusters`);
        fetchTags();
      } else toast.error("Cluster generation failed");
    } catch { toast.error("Cluster generation failed"); }
    setClusterRunning(false);
  };

  return (
    <>
      <SectionHeader title="Tags" description="Create, deduplicate, and organize tags." />

      {/* Create tag */}
      <div className="space-y-2">
        <Label className="text-sm font-medium">Create Tag</Label>
        <div className="flex gap-3">
          <Input
            placeholder="Tag name..."
            value={newTagName}
            onChange={(e) => setNewTagName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && createTag()}
            className="flex-1"
          />
          <div className="flex gap-1 items-center">
            {TAG_COLORS.map((c) => (
              <button
                key={c}
                onClick={() => setNewTagColor(c)}
                className={`h-5 w-5 rounded-full border-2 transition-transform ${
                  newTagColor === c ? "scale-110 border-foreground" : "border-transparent"
                }`}
                style={{ backgroundColor: c }}
              />
            ))}
          </div>
          <Button size="sm" onClick={createTag} disabled={!newTagName.trim()}>
            <Plus className="mr-1 h-3.5 w-3.5" />
            Create
          </Button>
        </div>
      </div>

      {/* Deduplicate */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <Label className="text-sm font-medium">Deduplicate</Label>
          <Button variant="outline" size="sm" onClick={findDuplicates} disabled={dupsLoading}>
            {dupsLoading ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Merge className="mr-1.5 h-3.5 w-3.5" />}
            {dupsScanned ? "Rescan" : "Find Duplicates"}
          </Button>
        </div>
        {dupsScanned && duplicates.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <p className="text-xs text-muted-foreground">{duplicates.length} group{duplicates.length !== 1 ? "s" : ""} found</p>
              <Button size="sm" variant="outline" onClick={mergeAll}>Merge All</Button>
            </div>
            {duplicates.map((group, i) => (
              <div key={i} className="rounded-md border p-2 space-y-2">
                <div className="flex flex-wrap gap-1.5">
                  {group.map((tag) => {
                    const isTarget = selectedTargets[i] === tag.id;
                    return (
                      <button
                        key={tag.id}
                        onClick={() => setSelectedTargets((prev) => ({ ...prev, [i]: tag.id }))}
                        className={`flex items-center gap-1 rounded-md border px-2 py-1 text-xs transition-colors ${
                          isTarget ? "border-primary bg-primary/5 font-medium" : "border-transparent hover:bg-accent"
                        }`}
                      >
                        {isTarget && <Check className="h-3 w-3 text-primary" />}
                        {tag.name} ({tag.paperCount})
                      </button>
                    );
                  })}
                </div>
                <div className="flex justify-end">
                  <Button size="sm" variant="outline" onClick={() => mergeGroup(i)} disabled={mergingGroup === i}>
                    {mergingGroup === i ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : <Merge className="mr-1 h-3 w-3" />}
                    Merge
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Smart cleanup */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5" /> Smart Cleanup</Label>
            <p className="text-xs text-muted-foreground mt-0.5">Deletes orphans, merges similar singletons, recomputes scores.</p>
          </div>
          <Button variant="outline" size="sm" onClick={runSmartCleanup} disabled={cleanupRunning}>
            {cleanupRunning ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1.5 h-3.5 w-3.5" />}
            Run
          </Button>
        </div>
        {cleanupResult && (
          <div className="rounded-md border p-3 space-y-1 text-xs">
            <p><strong>{cleanupResult.tagsBefore}</strong> → <strong>{cleanupResult.tagsAfter}</strong> tags</p>
            {cleanupResult.orphansDeleted.length > 0 && (
              <p className="text-muted-foreground">Deleted: {cleanupResult.orphansDeleted.join(", ")}</p>
            )}
            {cleanupResult.singletonsMerged.length > 0 && (
              <p className="text-muted-foreground">Merged: {cleanupResult.singletonsMerged.map((m) => `${m.from} → ${m.into}`).join(", ")}</p>
            )}
            <p className="text-muted-foreground">{cleanupResult.scoresUpdated} scores updated</p>
          </div>
        )}
      </div>

      {/* Clusters */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Grid3X3 className="h-3.5 w-3.5" /> Tag Clusters</Label>
            <p className="text-xs text-muted-foreground mt-0.5">AI-generated thematic groupings for navigation.</p>
          </div>
          <Button variant="outline" size="sm" onClick={runGenerateClusters} disabled={clusterRunning}>
            {clusterRunning ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Grid3X3 className="mr-1.5 h-3.5 w-3.5" />}
            Generate
          </Button>
        </div>
        {clusterResult && (
          <div className="rounded-md border p-3 space-y-1 text-xs">
            {clusterResult.clusters.map((c) => (
              <div key={c.name} className="flex items-center gap-2">
                <Badge variant="secondary" className="text-[10px]">{c.tagCount}</Badge>
                <span className="font-medium">{c.name}</span>
                <span className="text-muted-foreground">{c.description}</span>
              </div>
            ))}
            {clusterResult.unassigned.length > 0 && (
              <p className="text-muted-foreground">Unassigned: {clusterResult.unassigned.join(", ")}</p>
            )}
          </div>
        )}
      </div>

      {/* All tags */}
      {tags.length > 0 && (
        <div className="space-y-2 pt-4 border-t border-border">
          <Label className="text-sm font-medium">All Tags ({tags.length})</Label>
          <div className="space-y-1 max-h-[300px] overflow-auto">
            {tags.map((tag) => (
              <div key={tag.id} className="flex items-center justify-between rounded-md border px-3 py-1.5">
                <div className="flex items-center gap-2">
                  <Badge style={{ backgroundColor: tag.color + "20", color: tag.color }}>{tag.name}</Badge>
                  <span className="text-xs text-muted-foreground">{tag._count.papers} paper{tag._count.papers !== 1 ? "s" : ""}</span>
                  {tag.isAutoGenerated && <Badge variant="outline" className="text-[10px]">Auto</Badge>}
                </div>
                <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => deleteTag(tag.id)}>
                  <Trash2 className="h-3 w-3" />
                </Button>
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  );
}

// ── Agent Capabilities ─────────────────────────────────────────────

interface Capability {
  id: string;
  name: string;
  description: string;
  instructions: string;
  enabled: boolean;
}

const CAPABILITY_EXAMPLES = [
  {
    name: "Weights & Biases",
    description: "Experiment tracking and visualization platform",
    instructions: "Use `wandb` for experiment tracking. It's already installed and configured.\n\nIn experiment code, add:\n```python\nimport wandb\nwandb.init(project=\"research-agent\")\nwandb.log({\"metric\": value})\n```\n\nThe API key is set in the environment as WANDB_API_KEY.",
  },
  {
    name: "LLM Data Generation",
    description: "Generate synthetic datasets using LLMs via a local API",
    instructions: "To generate synthetic data, write a Python script that calls:\n```python\nimport requests\nres = requests.post(\"http://localhost:3000/api/generate\", json={\n  \"prompt\": \"your prompt here\",\n  \"n\": 100,  # number of samples\n  \"model\": \"gpt-4o-mini\"\n})\ndata = res.json()[\"samples\"]\n```\n\nUse this when you need labeled data for experiments but no suitable public dataset exists.",
  },
  {
    name: "HuggingFace Hub",
    description: "Access to HuggingFace models and datasets",
    instructions: "HuggingFace token is set in the environment as HF_TOKEN.\n\nUse `huggingface_hub` and `datasets` libraries freely:\n```python\nfrom datasets import load_dataset\nfrom transformers import AutoModel, AutoTokenizer\n```\n\nPrefer loading datasets with streaming=True for large datasets.",
  },
];

function AgentCapabilitiesSection() {
  const [capabilities, setCapabilities] = useState<Capability[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", instructions: "" });
  const [saving, setSaving] = useState(false);

  const fetchCapabilities = useCallback(async () => {
    try {
      const res = await fetch("/api/settings/agent-capabilities");
      if (res.ok) setCapabilities(await res.json());
    } catch { /* ignore */ }
    setLoading(false);
  }, []);

  useEffect(() => { fetchCapabilities(); }, [fetchCapabilities]);

  const handleSave = async () => {
    if (!form.name.trim() || !form.instructions.trim()) return;
    setSaving(true);
    try {
      if (editingId) {
        const res = await fetch("/api/settings/agent-capabilities", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: editingId, ...form }),
        });
        if (res.ok) {
          toast.success("Capability updated");
          setEditingId(null);
        }
      } else {
        const res = await fetch("/api/settings/agent-capabilities", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(form),
        });
        if (res.ok) {
          toast.success("Capability added");
          setShowNew(false);
        }
      }
      setForm({ name: "", description: "", instructions: "" });
      await fetchCapabilities();
    } catch {
      toast.error("Failed to save");
    }
    setSaving(false);
  };

  const handleDelete = async (id: string) => {
    try {
      await fetch("/api/settings/agent-capabilities", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      toast.success("Removed");
      await fetchCapabilities();
    } catch {
      toast.error("Failed to delete");
    }
  };

  const handleToggle = async (cap: Capability) => {
    try {
      await fetch("/api/settings/agent-capabilities", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: cap.id, enabled: !cap.enabled }),
      });
      await fetchCapabilities();
    } catch {
      toast.error("Failed to update");
    }
  };

  const startEdit = (cap: Capability) => {
    setEditingId(cap.id);
    setForm({ name: cap.name, description: cap.description, instructions: cap.instructions });
    setShowNew(false);
  };

  const startNew = (example?: typeof CAPABILITY_EXAMPLES[0]) => {
    setEditingId(null);
    setForm(example || { name: "", description: "", instructions: "" });
    setShowNew(true);
  };

  return (
    <>
      <SectionHeader
        title="Agent Capabilities"
        description="Define tools, APIs, and resources the research agent can use. These are injected into the agent's context so it knows what's available."
      />

      {loading ? (
        <div className="flex items-center gap-2 py-8 justify-center text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" /> Loading...
        </div>
      ) : (
        <div className="space-y-3">
          {/* Existing capabilities */}
          {capabilities.map((cap) => (
            <div
              key={cap.id}
              className={`rounded-lg border px-4 py-3 transition-colors ${
                cap.enabled ? "border-border bg-card" : "border-border/50 bg-muted/30 opacity-60"
              }`}
            >
              {editingId === cap.id ? (
                <CapabilityForm
                  form={form}
                  setForm={setForm}
                  onSave={handleSave}
                  onCancel={() => { setEditingId(null); setForm({ name: "", description: "", instructions: "" }); }}
                  saving={saving}
                  isEdit
                />
              ) : (
                <div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-sm">{cap.name}</span>
                      {!cap.enabled && (
                        <span className="text-[10px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded">disabled</span>
                      )}
                    </div>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleToggle(cap)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
                        title={cap.enabled ? "Disable" : "Enable"}
                      >
                        {cap.enabled ? <Power className="h-3.5 w-3.5" /> : <PowerOff className="h-3.5 w-3.5" />}
                      </button>
                      <button
                        onClick={() => startEdit(cap)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
                        title="Edit"
                      >
                        <Pencil className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => handleDelete(cap.id)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-destructive/10 hover:text-destructive transition-colors"
                        title="Delete"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                  {cap.description && (
                    <p className="text-xs text-muted-foreground mt-1">{cap.description}</p>
                  )}
                  <pre className="mt-2 text-[11px] text-muted-foreground bg-muted/50 rounded p-2 whitespace-pre-wrap max-h-32 overflow-auto font-mono">
                    {cap.instructions}
                  </pre>
                </div>
              )}
            </div>
          ))}

          {/* New capability form */}
          {showNew && (
            <div className="rounded-lg border border-blue-500/30 bg-blue-500/5 px-4 py-3">
              <CapabilityForm
                form={form}
                setForm={setForm}
                onSave={handleSave}
                onCancel={() => { setShowNew(false); setForm({ name: "", description: "", instructions: "" }); }}
                saving={saving}
              />
            </div>
          )}

          {/* Add button + examples */}
          {!showNew && !editingId && (
            <div className="space-y-3">
              <Button variant="outline" size="sm" onClick={() => startNew()} className="gap-1.5">
                <Plus className="h-3.5 w-3.5" /> Add Capability
              </Button>

              {capabilities.length === 0 && (
                <div className="space-y-2">
                  <p className="text-xs text-muted-foreground">Quick-start with an example:</p>
                  <div className="flex flex-wrap gap-2">
                    {CAPABILITY_EXAMPLES.map((ex) => (
                      <button
                        key={ex.name}
                        onClick={() => startNew(ex)}
                        className="rounded-md border border-dashed border-border px-3 py-1.5 text-xs text-muted-foreground hover:border-foreground/30 hover:text-foreground transition-colors"
                      >
                        {ex.name}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </>
  );
}

function CapabilityForm({
  form,
  setForm,
  onSave,
  onCancel,
  saving,
  isEdit,
}: {
  form: { name: string; description: string; instructions: string };
  setForm: (f: { name: string; description: string; instructions: string }) => void;
  onSave: () => void;
  onCancel: () => void;
  saving: boolean;
  isEdit?: boolean;
}) {
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label className="text-xs">Name</Label>
          <Input
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
            placeholder="e.g., Weights & Biases"
            className="mt-1 text-sm h-8"
          />
        </div>
        <div>
          <Label className="text-xs">Description (optional)</Label>
          <Input
            value={form.description}
            onChange={(e) => setForm({ ...form, description: e.target.value })}
            placeholder="e.g., Experiment tracking platform"
            className="mt-1 text-sm h-8"
          />
        </div>
      </div>
      <div>
        <Label className="text-xs">Instructions for the agent</Label>
        <textarea
          value={form.instructions}
          onChange={(e) => setForm({ ...form, instructions: e.target.value })}
          placeholder="Tell the agent how to use this capability. Include code snippets, API endpoints, environment variables, etc."
          rows={6}
          className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm font-mono focus:outline-none focus:ring-1 focus:ring-ring resize-y"
        />
      </div>
      <div className="flex items-center gap-2">
        <Button size="sm" onClick={onSave} disabled={saving || !form.name.trim() || !form.instructions.trim()}>
          {saving ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <Save className="h-3.5 w-3.5 mr-1.5" />}
          {isEdit ? "Update" : "Add"}
        </Button>
        <Button size="sm" variant="ghost" onClick={onCancel}>
          Cancel
        </Button>
      </div>
    </div>
  );
}

// ── Insights ──────────────────────────────────────────────────────

interface InsightRoom {
  id: string;
  name: string;
  description: string | null;
  color: string;
  icon: string;
  _count: { insights: number };
}

interface InsightStats {
  totalInsights: number;
  totalRooms: number;
}

function InsightsSection() {
  const [rooms, setRooms] = useState<InsightRoom[]>([]);
  const [stats, setStats] = useState<InsightStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [deletingRoom, setDeletingRoom] = useState<string | null>(null);
  const [expandedRoom, setExpandedRoom] = useState<string | null>(null);
  const [roomInsights, setRoomInsights] = useState<InsightData[]>([]);
  const [loadingInsights, setLoadingInsights] = useState(false);
  const [editingInsight, setEditingInsight] = useState<InsightData | null>(null);
  const [editForm, setEditForm] = useState({ learning: "", significance: "", applications: "" });
  const [editSaving, setEditSaving] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [roomsRes, statsRes] = await Promise.all([
        fetch("/api/mind-palace/rooms"),
        fetch("/api/mind-palace/stats"),
      ]);
      setRooms(await roomsRes.json());
      setStats(await statsRes.json());
    } catch {
      toast.error("Failed to load insights data");
    }
    setLoading(false);
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  const fetchRoomInsights = async (roomId: string) => {
    setLoadingInsights(true);
    try {
      const res = await fetch(`/api/mind-palace/rooms/${roomId}`);
      if (res.ok) {
        const data = await res.json();
        setRoomInsights(data.insights || []);
      }
    } catch {
      toast.error("Failed to load insights");
    }
    setLoadingInsights(false);
  };

  const toggleRoom = async (roomId: string) => {
    if (expandedRoom === roomId) {
      setExpandedRoom(null);
      setRoomInsights([]);
      return;
    }
    setExpandedRoom(roomId);
    fetchRoomInsights(roomId);
  };

  const deleteRoom = async (roomId: string) => {
    if (!confirm("Delete this room and all its insights?")) return;
    setDeletingRoom(roomId);
    const res = await fetch(`/api/mind-palace/rooms/${roomId}`, { method: "DELETE" });
    if (res.ok) {
      toast.success("Room deleted");
      if (expandedRoom === roomId) {
        setExpandedRoom(null);
        setRoomInsights([]);
      }
      fetchData();
    } else {
      toast.error("Failed to delete room");
    }
    setDeletingRoom(null);
  };

  const handleEdit = (insight: InsightData) => {
    setEditingInsight(insight);
    setEditForm({
      learning: insight.learning,
      significance: insight.significance,
      applications: insight.applications || "",
    });
  };

  const saveEdit = async () => {
    if (!editingInsight) return;
    setEditSaving(true);
    const res = await fetch(`/api/mind-palace/insights/${editingInsight.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        learning: editForm.learning,
        significance: editForm.significance,
        applications: editForm.applications || null,
      }),
    });
    if (res.ok) {
      toast.success("Insight updated");
      setEditingInsight(null);
      if (expandedRoom) fetchRoomInsights(expandedRoom);
    } else {
      toast.error("Failed to update insight");
    }
    setEditSaving(false);
  };

  const handleDelete = (insightId: string) => {
    setRoomInsights((prev) => prev.filter((i) => i.id !== insightId));
    fetchData();
  };

  return (
    <>
      <SectionHeader title="Insights" description="Knowledge distilled from your papers. Strength grows as the Research agent references them." />

      {loading ? (
        <div className="text-sm text-muted-foreground">Loading...</div>
      ) : (
        <>
          {/* Stats */}
          {stats && (
            <div className="grid grid-cols-2 gap-3">
              <div className="rounded-md border p-3">
                <div className="flex items-center gap-2">
                  <Lightbulb className="h-4 w-4 text-amber-500" />
                  <span className="text-2xl font-bold">{stats.totalInsights}</span>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">Total insights</p>
              </div>
              <div className="rounded-md border p-3">
                <div className="flex items-center gap-2">
                  <Brain className="h-4 w-4 text-indigo-500" />
                  <span className="text-2xl font-bold">{stats.totalRooms}</span>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">Rooms</p>
              </div>
            </div>
          )}

          {/* Rooms */}
          <div className="space-y-1 pt-4 border-t border-border">
            <Label className="text-sm font-medium mb-2 block">Rooms ({rooms.length})</Label>
            {rooms.length === 0 ? (
              <p className="text-sm text-muted-foreground">No rooms yet. Distill insights from papers to auto-create rooms.</p>
            ) : (
              rooms.map((room) => {
                const isOpen = expandedRoom === room.id;
                return (
                  <div key={room.id}>
                    {/* Room row */}
                    <div className={`flex items-center gap-2 rounded-md px-3 py-2 cursor-pointer transition-colors ${
                      isOpen ? "bg-accent/50" : "hover:bg-accent/30"
                    }`}>
                      <button
                        className="flex items-center gap-2 flex-1 text-left"
                        onClick={() => toggleRoom(room.id)}
                      >
                        <ChevronRight className={`h-3 w-3 text-muted-foreground transition-transform duration-150 ${isOpen ? "rotate-90" : ""}`} />
                        <span className="h-2.5 w-2.5 rounded-full shrink-0" style={{ backgroundColor: room.color }} />
                        <span className="text-sm font-medium">{room.name}</span>
                        <span className="text-xs text-muted-foreground tabular-nums">
                          {room._count.insights}
                        </span>
                      </button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6 opacity-0 group-hover:opacity-100 hover:!opacity-100"
                        style={{ opacity: isOpen ? 1 : undefined }}
                        disabled={deletingRoom === room.id}
                        onClick={(e) => { e.stopPropagation(); deleteRoom(room.id); }}
                      >
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    </div>

                    {/* Expanded: full InsightCards */}
                    {isOpen && (
                      <div className="pl-5 pr-1 pt-1 pb-3 space-y-2">
                        {loadingInsights ? (
                          <p className="text-xs text-muted-foreground py-3 pl-3">Loading...</p>
                        ) : roomInsights.length === 0 ? (
                          <p className="text-xs text-muted-foreground py-3 pl-3">No insights in this room.</p>
                        ) : (
                          roomInsights.map((insight) => (
                            <InsightCard
                              key={insight.id}
                              insight={insight}
                              compact
                              onEdit={handleEdit}
                              onDelete={handleDelete}
                              onUpdate={() => { if (expandedRoom) fetchRoomInsights(expandedRoom); }}
                            />
                          ))
                        )}
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </>
      )}

      {/* Edit dialog */}
      <Dialog open={!!editingInsight} onOpenChange={(open) => { if (!open) setEditingInsight(null); }}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Edit Insight</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/60">What I learned</Label>
              <Textarea
                value={editForm.learning}
                onChange={(e) => setEditForm({ ...editForm, learning: e.target.value })}
                rows={3}
                className="mt-1 text-sm"
              />
            </div>
            <div>
              <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/60">Why it matters</Label>
              <Textarea
                value={editForm.significance}
                onChange={(e) => setEditForm({ ...editForm, significance: e.target.value })}
                rows={2}
                className="mt-1 text-sm"
              />
            </div>
            <div>
              <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/60">How to apply</Label>
              <Textarea
                value={editForm.applications}
                onChange={(e) => setEditForm({ ...editForm, applications: e.target.value })}
                rows={2}
                className="mt-1 text-sm"
                placeholder="Optional"
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="ghost" size="sm" onClick={() => setEditingInsight(null)}>Cancel</Button>
              <Button size="sm" onClick={saveEdit} disabled={editSaving || !editForm.learning.trim()}>
                {editSaving ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <Save className="h-3.5 w-3.5 mr-1.5" />}
                Save
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

// ── Remote ─────────────────────────────────────────────────────────

function RemoteSection() {
  return (
    <>
      <SectionHeader title="Remote Execution" description="Configure GPU hosts for running experiments remotely." />
      <RemoteHostsManager />
    </>
  );
}
