"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ModelSelector } from "@/components/llm/model-selector";
import { RemoteHostsManager } from "@/components/research/remote-hosts-manager";
import {
  Save, Loader2, Zap, CheckCircle2, XCircle, Sun, Moon, Monitor,
  Plus, Trash2, Merge, Check, Tags, Sparkles, Grid3X3, Settings2,
  BrainCircuit, Server, Bot, Pencil, Power, PowerOff,
  Download, Upload,
} from "lucide-react";
import { toast } from "sonner";
import { useTheme } from "next-themes";

// ── Types ──────────────────────────────────────────────────────────

interface TagItem {
  id: string;
  name: string;
  color: string;
  isAutoGenerated: boolean;
  _count: { papers: number };
}

interface DuplicateTag {
  id: string;
  name: string;
  paperCount: number;
}

type DuplicateGroup = DuplicateTag[];

const TAG_COLORS = [
  "#EF4444", "#F59E0B", "#10B981", "#3B82F6",
  "#8B5CF6", "#EC4899", "#06B6D4", "#F97316",
];

type ProxyVendor = "openrouter" | "litellm" | "azure" | "custom";

const VENDOR_PRESETS: Record<ProxyVendor, { label: string; baseUrl: string; headerName: string; prefix: string }> = {
  openrouter: { label: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1", headerName: "Authorization", prefix: "Bearer " },
  litellm: { label: "LiteLLM", baseUrl: "http://localhost:4000/v1", headerName: "Authorization", prefix: "Bearer " },
  azure: { label: "Azure OpenAI", baseUrl: "https://<resource>.openai.azure.com/openai/deployments/<deployment>/v1", headerName: "api-key", prefix: "" },
  custom: { label: "Custom", baseUrl: "", headerName: "Authorization", prefix: "Bearer " },
};

type Section = "general" | "llm" | "tags" | "remote" | "agent";

const SECTIONS: { id: Section; label: string; icon: typeof Settings2 }[] = [
  { id: "general", label: "General", icon: Settings2 },
  { id: "llm", label: "LLM", icon: BrainCircuit },
  { id: "agent", label: "Agent", icon: Bot },
  { id: "tags", label: "Tags", icon: Tags },
  { id: "remote", label: "Remote", icon: Server },
];

// ── Main ───────────────────────────────────────────────────────────

export default function SettingsPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialSection = (searchParams.get("tab") as Section) || "general";
  const [section, setSection] = useState<Section>(initialSection);

  const handleSectionChange = (s: Section) => {
    setSection(s);
    router.replace(`/settings?tab=${s}`, { scroll: false });
  };

  return (
    <div className="flex gap-8 max-w-4xl mx-auto">
      {/* Left nav */}
      <nav className="w-40 shrink-0 pt-1">
        <h2 className="text-lg font-semibold mb-4">Settings</h2>
        <div className="space-y-0.5">
          {SECTIONS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => handleSectionChange(id)}
              className={`w-full flex items-center gap-2 rounded-md px-2.5 py-1.5 text-sm transition-colors ${
                section === id
                  ? "bg-accent text-foreground font-medium"
                  : "text-muted-foreground hover:text-foreground hover:bg-accent/50"
              }`}
            >
              <Icon className="h-3.5 w-3.5" />
              {label}
            </button>
          ))}
        </div>
      </nav>

      {/* Content */}
      <div className="flex-1 min-w-0 space-y-6 pb-12">
        {section === "general" && <GeneralSection />}
        {section === "llm" && <LLMSection />}
        {section === "agent" && <AgentCapabilitiesSection />}
        {section === "tags" && <TagsSection />}
        {section === "remote" && <RemoteSection />}
      </div>
    </div>
  );
}

// ── Section header ─────────────────────────────────────────────────

function SectionHeader({ title, description }: { title: string; description?: string }) {
  return (
    <div className="pb-2 border-b border-border">
      <h3 className="text-base font-semibold">{title}</h3>
      {description && <p className="text-sm text-muted-foreground mt-0.5">{description}</p>}
    </div>
  );
}

// ── General ────────────────────────────────────────────────────────

function GeneralSection() {
  const { theme, setTheme } = useTheme();
  const [outputFolder, setOutputFolder] = useState("./output");
  const [outputFolderLoaded, setOutputFolderLoaded] = useState(false);
  const [outputFolderSaving, setOutputFolderSaving] = useState(false);

  useEffect(() => {
    fetch("/api/settings/output-folder")
      .then((r) => r.json())
      .then((data) => { if (data.folder) setOutputFolder(data.folder); setOutputFolderLoaded(true); })
      .catch(() => setOutputFolderLoaded(true));
  }, []);

  const handleOutputFolderSave = async () => {
    setOutputFolderSaving(true);
    try {
      const res = await fetch("/api/settings/output-folder", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ folder: outputFolder }),
      });
      if (res.ok) toast.success("Output folder saved");
      else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setOutputFolderSaving(false); }
  };

  return (
    <>
      <SectionHeader title="General" />

      {/* Theme */}
      <div className="flex items-center justify-between">
        <Label className="text-sm font-medium">Theme</Label>
        <div className="flex items-center gap-1.5">
          {([
            { value: "light", label: "Light", icon: Sun },
            { value: "dark", label: "Dark", icon: Moon },
            { value: "system", label: "System", icon: Monitor },
          ] as const).map(({ value, label, icon: Icon }) => (
            <Button
              key={value}
              variant={theme === value ? "default" : "outline"}
              size="sm"
              onClick={() => setTheme(value)}
              className="gap-1.5"
            >
              <Icon className="h-4 w-4" />
              {label}
            </Button>
          ))}
        </div>
      </div>

      {/* Output Folder */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium">Output Folder</Label>
            <p className="text-xs text-muted-foreground">Where the agent writes generated code, exports, etc.</p>
          </div>
        </div>
        {outputFolderLoaded && (
          <div className="flex items-center gap-2">
            <Input
              value={outputFolder}
              onChange={(e) => setOutputFolder(e.target.value)}
              placeholder="./output"
              className="font-mono text-sm flex-1"
            />
            <Button size="sm" onClick={handleOutputFolderSave} disabled={outputFolderSaving || !outputFolder.trim()}>
              {outputFolderSaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
              Save
            </Button>
          </div>
        )}
      </div>

      {/* Database Import/Export */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div>
          <Label className="text-sm font-medium">Database</Label>
          <p className="text-xs text-muted-foreground">Export the entire database as JSON or import from another machine.</p>
        </div>
        <DatabaseImportExport />
      </div>

      {/* About */}
      <div className="space-y-1.5 pt-4 border-t border-border">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium">Arcana</span>
          <Badge variant="secondary">v1.0.0</Badge>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed">
          Your personal research engine. Collect papers, let AI extract key insights,
          form hypotheses, run experiments, and iterate — all in one place.
          Arcana turns scattered reading into structured knowledge.
        </p>
      </div>
    </>
  );
}

function DatabaseImportExport() {
  const [exporting, setExporting] = useState(false);
  const [importing, setImporting] = useState(false);
  const [importStats, setImportStats] = useState<Record<string, number> | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExport = async () => {
    setExporting(true);
    try {
      const res = await fetch("/api/admin/db");
      if (!res.ok) throw new Error("Export failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `arcana-db-${new Date().toISOString().slice(0, 10)}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success("Database exported");
    } catch {
      toast.error("Failed to export database");
    }
    setExporting(false);
  };

  const handleImport = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const confirmed = window.confirm(
      "This will REPLACE your entire database with the imported data. All current data will be lost. Are you sure?"
    );
    if (!confirmed) {
      if (fileInputRef.current) fileInputRef.current.value = "";
      return;
    }

    setImporting(true);
    setImportStats(null);
    try {
      const text = await file.text();
      const data = JSON.parse(text);

      if (!data.version || !data.tables) {
        toast.error("Invalid export file format");
        setImporting(false);
        return;
      }

      const res = await fetch("/api/admin/db", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: text,
      });
      const result = await res.json();
      if (res.ok) {
        setImportStats(result.stats);
        const totalRows = Object.values(result.stats as Record<string, number>).reduce((a: number, b: number) => a + b, 0);
        toast.success(`Imported ${totalRows} rows across ${Object.keys(result.stats).length} tables`);
      } else {
        toast.error(result.error || "Import failed");
      }
    } catch (err) {
      toast.error("Failed to parse import file: " + (err instanceof Error ? err.message : "unknown error"));
    }
    setImporting(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" onClick={handleExport} disabled={exporting} className="gap-1.5">
          {exporting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          Export
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => fileInputRef.current?.click()}
          disabled={importing}
          className="gap-1.5"
        >
          {importing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />}
          Import
        </Button>
        <input
          ref={fileInputRef}
          type="file"
          accept=".json"
          onChange={handleImport}
          className="hidden"
        />
      </div>
      {importing && (
        <p className="text-xs text-muted-foreground">Importing... This may take a moment for large databases.</p>
      )}
      {importStats && (
        <div className="text-xs text-muted-foreground space-y-0.5">
          <p className="font-medium text-foreground">Import complete:</p>
          {Object.entries(importStats)
            .filter(([, count]) => count > 0)
            .map(([table, count]) => (
              <p key={table}>{table}: {count} rows</p>
            ))}
        </div>
      )}
    </div>
  );
}

// ── LLM ────────────────────────────────────────────────────────────

interface KeyStatus {
  set: boolean;
  source: "db" | "env" | null;
  masked: string;
}

function LLMSection() {
  const [provider, setProvider] = useState<"openai" | "anthropic" | "proxy">("openai");
  const [modelId, setModelId] = useState("gpt-4o-mini");
  const [saving, setSaving] = useState(false);
  const [loaded, setLoaded] = useState(false);

  // API keys
  const [keyStatus, setKeyStatus] = useState<{ openai: KeyStatus; anthropic: KeyStatus } | null>(null);
  const [openaiKey, setOpenaiKey] = useState("");
  const [anthropicKey, setAnthropicKey] = useState("");
  const [keysSaving, setKeysSaving] = useState(false);

  // Proxy
  const [proxyEnabled, setProxyEnabled] = useState(false);
  const [proxyVendor, setProxyVendor] = useState<ProxyVendor>("openrouter");
  const [proxyBaseUrl, setProxyBaseUrl] = useState("");
  const [proxyAnthropicBaseUrl, setProxyAnthropicBaseUrl] = useState("");
  const [proxyApiKey, setProxyApiKey] = useState("");
  const [proxyHeaderName, setProxyHeaderName] = useState("Authorization");
  const [proxyHeaderValue, setProxyHeaderValue] = useState("");
  const [proxyModels, setProxyModels] = useState("");
  const [proxyContextWindow, setProxyContextWindow] = useState("128000");
  const [proxyMaxTokens, setProxyMaxTokens] = useState("4096");
  const [proxySaving, setProxySaving] = useState(false);
  const [proxyTesting, setProxyTesting] = useState(false);
  const [proxyTestResult, setProxyTestResult] = useState<{ ok: boolean; message: string } | null>(null);
  const [proxyLoaded, setProxyLoaded] = useState(false);
  const [proxyHasExistingKey, setProxyHasExistingKey] = useState(false);

  useEffect(() => {
    fetch("/api/settings/default-model")
      .then((r) => r.json())
      .then((data) => { if (data.provider) setProvider(data.provider); if (data.modelId) setModelId(data.modelId); setLoaded(true); })
      .catch(() => setLoaded(true));
  }, []);

  useEffect(() => {
    fetch("/api/settings/api-keys")
      .then((r) => r.json())
      .then((data) => setKeyStatus(data))
      .catch(() => {});
  }, []);

  useEffect(() => {
    fetch("/api/settings/proxy")
      .then((r) => r.json())
      .then((data) => {
        setProxyEnabled(data.enabled);
        setProxyVendor(data.vendor || "openrouter");
        setProxyBaseUrl(data.baseUrl || "");
        setProxyAnthropicBaseUrl(data.anthropicBaseUrl || "");
        setProxyHeaderName(data.headerName || "Authorization");
        setProxyHeaderValue(data.headerValue || "");
        setProxyModels(data.modelId || "");
        setProxyContextWindow(String(data.contextWindow || 128000));
        setProxyMaxTokens(String(data.maxTokens || 4096));
        setProxyHasExistingKey(!!data.apiKey);
        setProxyLoaded(true);
      })
      .catch(() => setProxyLoaded(true));
  }, []);

  const handleModelSave = async () => {
    setSaving(true);
    try {
      const res = await fetch("/api/settings/default-model", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ provider, modelId }),
      });
      if (res.ok) toast.success("Default model saved");
      else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setSaving(false); }
  };

  const handleKeysSave = async () => {
    setKeysSaving(true);
    try {
      const body: Record<string, string> = {};
      if (openaiKey) body.openai = openaiKey;
      if (anthropicKey) body.anthropic = anthropicKey;
      const res = await fetch("/api/settings/api-keys", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (res.ok) {
        toast.success("API keys saved");
        setOpenaiKey("");
        setAnthropicKey("");
        // Refresh status
        const statusRes = await fetch("/api/settings/api-keys");
        if (statusRes.ok) setKeyStatus(await statusRes.json());
      } else toast.error("Failed to save");
    } catch { toast.error("Failed to save"); }
    finally { setKeysSaving(false); }
  };

  const handleVendorChange = useCallback((vendor: ProxyVendor) => {
    setProxyVendor(vendor);
    const preset = VENDOR_PRESETS[vendor];
    if (vendor !== "custom") {
      setProxyBaseUrl(preset.baseUrl);
      setProxyHeaderName(preset.headerName);
    }
    setProxyTestResult(null);
  }, []);

  const buildHeaderValue = useCallback(() => {
    if (proxyVendor === "custom") return proxyHeaderValue;
    const preset = VENDOR_PRESETS[proxyVendor];
    return preset.prefix + proxyApiKey;
  }, [proxyVendor, proxyApiKey, proxyHeaderValue]);

  const handleProxySave = async () => {
    setProxySaving(true);
    try {
      const res = await fetch("/api/settings/proxy", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          enabled: proxyEnabled, vendor: proxyVendor, baseUrl: proxyBaseUrl,
          anthropicBaseUrl: proxyAnthropicBaseUrl, apiKey: proxyApiKey || null,
          headerName: proxyHeaderName, headerValue: proxyVendor === "custom" ? proxyHeaderValue : "",
          modelId: proxyModels, contextWindow: proxyContextWindow, maxTokens: proxyMaxTokens,
        }),
      });
      if (res.ok) {
        toast.success("Proxy settings saved");
        if (proxyApiKey) { setProxyHasExistingKey(true); setProxyApiKey(""); }
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || "Failed to save proxy settings");
      }
    } catch { toast.error("Failed to save proxy settings"); }
    finally { setProxySaving(false); }
  };

  const handleProxyTest = async () => {
    setProxyTesting(true);
    setProxyTestResult(null);
    try {
      const headerValue = buildHeaderValue();
      const firstModel = proxyModels.split(",").map(s => s.trim()).filter(Boolean)[0] || "gpt-3.5-turbo";
      const res = await fetch("/api/settings/proxy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ baseUrl: proxyBaseUrl, anthropicBaseUrl: proxyAnthropicBaseUrl, headerName: proxyHeaderName, headerValue, modelId: firstModel }),
      });
      const data = await res.json();
      if (data.ok) setProxyTestResult({ ok: true, message: `Connected! Model: ${firstModel}` });
      else setProxyTestResult({ ok: false, message: data.error || "Connection failed" });
    } catch (e) {
      setProxyTestResult({ ok: false, message: e instanceof Error ? e.message : "Connection failed" });
    } finally { setProxyTesting(false); }
  };

  return (
    <>
      <SectionHeader title="LLM" description="Choose a model, enter your API keys, or connect through a proxy." />

      {/* Model selection */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="text-sm font-medium">Model</Label>
        </div>
        {loaded && (
          <div className="flex items-end gap-3">
            <ModelSelector provider={provider} modelId={modelId} onProviderChange={setProvider} onModelChange={setModelId} />
            <Button size="sm" onClick={handleModelSave} disabled={saving}>
              {saving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
              Save
            </Button>
          </div>
        )}
        <p className="text-xs text-muted-foreground">
          Used for summaries, tagging, chat, research steps, and all other AI features.
        </p>
      </div>

      {/* API Keys */}
      <div className="space-y-3 pt-4 border-t border-border">
        <Label className="text-sm font-medium">API Keys</Label>
        <div className="grid gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Label className="text-xs">OpenAI</Label>
              {keyStatus?.openai.set && (
                <span className="text-[10px] text-emerald-600 dark:text-emerald-400">
                  {keyStatus.openai.masked}
                  {keyStatus.openai.source === "env" && " (from .env)"}
                </span>
              )}
            </div>
            <Input
              type="password"
              value={openaiKey}
              onChange={(e) => setOpenaiKey(e.target.value)}
              placeholder={keyStatus?.openai.set ? "Enter new key to replace" : "sk-..."}
              className="font-mono text-sm"
            />
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Label className="text-xs">Anthropic</Label>
              {keyStatus?.anthropic.set && (
                <span className="text-[10px] text-emerald-600 dark:text-emerald-400">
                  {keyStatus.anthropic.masked}
                  {keyStatus.anthropic.source === "env" && " (from .env)"}
                </span>
              )}
            </div>
            <Input
              type="password"
              value={anthropicKey}
              onChange={(e) => setAnthropicKey(e.target.value)}
              placeholder={keyStatus?.anthropic.set ? "Enter new key to replace" : "sk-ant-..."}
              className="font-mono text-sm"
            />
          </div>
        </div>
        <Button size="sm" onClick={handleKeysSave} disabled={keysSaving || (!openaiKey && !anthropicKey)}>
          {keysSaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
          Save Keys
        </Button>
      </div>

      {/* Proxy */}
      <div className="space-y-3 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Zap className="h-3.5 w-3.5" /> Proxy</Label>
            <p className="text-xs text-muted-foreground mt-0.5">Route requests through OpenRouter, LiteLLM, or a custom endpoint.</p>
          </div>
          <Button variant={proxyEnabled ? "default" : "outline"} size="sm" onClick={() => setProxyEnabled(!proxyEnabled)}>
            {proxyEnabled ? "Enabled" : "Disabled"}
          </Button>
        </div>

        {proxyLoaded && proxyEnabled && (
          <div className="space-y-3 rounded-md border border-border p-4">
            <div className="space-y-1">
              <Label className="text-xs">Vendor</Label>
              <Select value={proxyVendor} onValueChange={(v) => handleVendorChange(v as ProxyVendor)}>
                <SelectTrigger className="w-[200px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="openrouter">OpenRouter</SelectItem>
                  <SelectItem value="litellm">LiteLLM</SelectItem>
                  <SelectItem value="azure">Azure OpenAI</SelectItem>
                  <SelectItem value="custom">Custom</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label className="text-xs">Base URL</Label>
              <Input value={proxyBaseUrl} onChange={(e) => setProxyBaseUrl(e.target.value)} placeholder="https://openrouter.ai/api/v1" className="font-mono text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">Anthropic Base URL</Label>
              <Input value={proxyAnthropicBaseUrl} onChange={(e) => setProxyAnthropicBaseUrl(e.target.value)} placeholder="Auto-derived if blank" className="font-mono text-sm" />
            </div>

            <div className="space-y-1">
              <Label className="text-xs">API Key</Label>
              <Input type="password" value={proxyApiKey} onChange={(e) => setProxyApiKey(e.target.value)} placeholder={proxyHasExistingKey ? "Saved — leave blank to keep" : "sk-or-..."} className="font-mono text-sm" />
            </div>

            {proxyVendor === "custom" && (
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <Label className="text-xs">Auth Header Name</Label>
                  <Input value={proxyHeaderName} onChange={(e) => setProxyHeaderName(e.target.value)} placeholder="Authorization" className="font-mono text-sm" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Auth Header Value</Label>
                  <Input type="password" value={proxyHeaderValue} onChange={(e) => setProxyHeaderValue(e.target.value)} placeholder="Bearer sk-..." className="font-mono text-sm" />
                </div>
              </div>
            )}

            <div className="space-y-1">
              <Label className="text-xs">Models</Label>
              <Input value={proxyModels} onChange={(e) => setProxyModels(e.target.value)} placeholder="gpt-4o, claude-sonnet-4-6" className="font-mono text-sm" />
              <p className="text-[11px] text-muted-foreground">Comma-separated model IDs. These appear in the model picker above.</p>
            </div>

            <div className="flex gap-3">
              <div className="space-y-1 flex-1">
                <Label className="text-xs">Context Window</Label>
                <Input type="number" value={proxyContextWindow} onChange={(e) => setProxyContextWindow(e.target.value)} placeholder="128000" />
              </div>
              <div className="space-y-1 flex-1">
                <Label className="text-xs">Max Output Tokens</Label>
                <Input type="number" value={proxyMaxTokens} onChange={(e) => setProxyMaxTokens(e.target.value)} placeholder="4096" />
              </div>
            </div>

            {proxyTestResult && (
              <div className={`flex items-start gap-2 rounded-md p-2.5 text-xs ${
                proxyTestResult.ok
                  ? "bg-green-50 text-green-800 dark:bg-green-950 dark:text-green-200"
                  : "bg-red-50 text-red-800 dark:bg-red-950 dark:text-red-200"
              }`}>
                {proxyTestResult.ok ? <CheckCircle2 className="h-3.5 w-3.5 mt-0.5 shrink-0" /> : <XCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" />}
                <span className="break-all">{proxyTestResult.message}</span>
              </div>
            )}

            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleProxyTest} disabled={proxyTesting || !proxyBaseUrl || !proxyModels}>
                {proxyTesting ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Zap className="mr-1.5 h-3.5 w-3.5" />}
                Test
              </Button>
              <Button size="sm" onClick={handleProxySave} disabled={proxySaving}>
                {proxySaving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Save className="mr-1.5 h-3.5 w-3.5" />}
                Save Proxy
              </Button>
            </div>
          </div>
        )}
      </div>
    </>
  );
}

// ── Tags ───────────────────────────────────────────────────────────

function TagsSection() {
  const [tags, setTags] = useState<TagItem[]>([]);
  const [newTagName, setNewTagName] = useState("");
  const [newTagColor, setNewTagColor] = useState(TAG_COLORS[0]);
  const [duplicates, setDuplicates] = useState<DuplicateGroup[]>([]);
  const [dupsLoading, setDupsLoading] = useState(false);
  const [dupsScanned, setDupsScanned] = useState(false);
  const [mergingGroup, setMergingGroup] = useState<number | null>(null);
  const [selectedTargets, setSelectedTargets] = useState<Record<number, string>>({});
  const [cleanupRunning, setCleanupRunning] = useState(false);
  const [cleanupResult, setCleanupResult] = useState<{
    orphansDeleted: string[];
    singletonsMerged: { from: string; into: string }[];
    singletonsKept: string[];
    scoresUpdated: number;
    tagsBefore: number;
    tagsAfter: number;
  } | null>(null);
  const [clusterRunning, setClusterRunning] = useState(false);
  const [clusterResult, setClusterResult] = useState<{
    clusters: { name: string; description: string; tagCount: number }[];
    unassigned: string[];
  } | null>(null);

  const fetchTags = useCallback(async () => {
    const res = await fetch("/api/tags");
    if (res.ok) setTags(await res.json());
  }, []);

  useEffect(() => { fetchTags(); }, [fetchTags]);

  const createTag = async () => {
    if (!newTagName.trim()) return;
    const res = await fetch("/api/tags", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newTagName.trim(), color: newTagColor }),
    });
    if (res.ok) { toast.success("Tag created"); setNewTagName(""); fetchTags(); }
    else toast.error("Failed to create tag");
  };

  const deleteTag = async (id: string) => {
    if (!confirm("Delete this tag?")) return;
    await fetch(`/api/tags/${id}`, { method: "DELETE" });
    toast.success("Tag deleted");
    fetchTags();
  };

  const findDuplicates = async () => {
    setDupsLoading(true);
    try {
      const res = await fetch("/api/tags/duplicates");
      const groups: DuplicateGroup[] = await res.json();
      setDuplicates(groups);
      setDupsScanned(true);
      const targets: Record<number, string> = {};
      groups.forEach((group, i) => {
        const best = group.reduce((a, b) => (b.paperCount > a.paperCount ? b : a));
        targets[i] = best.id;
      });
      setSelectedTargets(targets);
      if (groups.length === 0) toast.success("No duplicate tags found");
    } catch { toast.error("Failed to scan for duplicates"); }
    setDupsLoading(false);
  };

  const mergeGroup = async (groupIndex: number) => {
    const group = duplicates[groupIndex];
    const targetId = selectedTargets[groupIndex];
    if (!targetId) return;
    const sourceIds = group.filter((t) => t.id !== targetId).map((t) => t.id);
    if (sourceIds.length === 0) return;
    setMergingGroup(groupIndex);
    try {
      const res = await fetch("/api/tags/merge", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId, sourceIds }),
      });
      if (res.ok) { toast.success("Tags merged"); setDuplicates((prev) => prev.filter((_, i) => i !== groupIndex)); fetchTags(); }
      else toast.error("Failed to merge tags");
    } catch { toast.error("Failed to merge tags"); }
    setMergingGroup(null);
  };

  const mergeAll = async () => {
    for (let i = 0; i < duplicates.length; i++) await mergeGroup(i);
  };

  const runSmartCleanup = async () => {
    setCleanupRunning(true);
    setCleanupResult(null);
    try {
      const res = await fetch("/api/tags/cleanup", { method: "POST" });
      if (res.ok) {
        const result = await res.json();
        setCleanupResult(result);
        toast.success(`Cleanup done: ${result.tagsBefore} → ${result.tagsAfter} tags`);
        fetchTags();
      } else toast.error("Cleanup failed");
    } catch { toast.error("Cleanup failed"); }
    setCleanupRunning(false);
  };

  const runGenerateClusters = async () => {
    setClusterRunning(true);
    setClusterResult(null);
    try {
      const res = await fetch("/api/tags/clusters", { method: "POST" });
      if (res.ok) {
        const result = await res.json();
        setClusterResult(result);
        toast.success(`Generated ${result.clusters.length} clusters`);
        fetchTags();
      } else toast.error("Cluster generation failed");
    } catch { toast.error("Cluster generation failed"); }
    setClusterRunning(false);
  };

  return (
    <>
      <SectionHeader title="Tags" description="Create, deduplicate, and organize tags." />

      {/* Create tag */}
      <div className="space-y-2">
        <Label className="text-sm font-medium">Create Tag</Label>
        <div className="flex gap-3">
          <Input
            placeholder="Tag name..."
            value={newTagName}
            onChange={(e) => setNewTagName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && createTag()}
            className="flex-1"
          />
          <div className="flex gap-1 items-center">
            {TAG_COLORS.map((c) => (
              <button
                key={c}
                onClick={() => setNewTagColor(c)}
                className={`h-5 w-5 rounded-full border-2 transition-transform ${
                  newTagColor === c ? "scale-110 border-foreground" : "border-transparent"
                }`}
                style={{ backgroundColor: c }}
              />
            ))}
          </div>
          <Button size="sm" onClick={createTag} disabled={!newTagName.trim()}>
            <Plus className="mr-1 h-3.5 w-3.5" />
            Create
          </Button>
        </div>
      </div>

      {/* Deduplicate */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <Label className="text-sm font-medium">Deduplicate</Label>
          <Button variant="outline" size="sm" onClick={findDuplicates} disabled={dupsLoading}>
            {dupsLoading ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Merge className="mr-1.5 h-3.5 w-3.5" />}
            {dupsScanned ? "Rescan" : "Find Duplicates"}
          </Button>
        </div>
        {dupsScanned && duplicates.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <p className="text-xs text-muted-foreground">{duplicates.length} group{duplicates.length !== 1 ? "s" : ""} found</p>
              <Button size="sm" variant="outline" onClick={mergeAll}>Merge All</Button>
            </div>
            {duplicates.map((group, i) => (
              <div key={i} className="rounded-md border p-2 space-y-2">
                <div className="flex flex-wrap gap-1.5">
                  {group.map((tag) => {
                    const isTarget = selectedTargets[i] === tag.id;
                    return (
                      <button
                        key={tag.id}
                        onClick={() => setSelectedTargets((prev) => ({ ...prev, [i]: tag.id }))}
                        className={`flex items-center gap-1 rounded-md border px-2 py-1 text-xs transition-colors ${
                          isTarget ? "border-primary bg-primary/5 font-medium" : "border-transparent hover:bg-accent"
                        }`}
                      >
                        {isTarget && <Check className="h-3 w-3 text-primary" />}
                        {tag.name} ({tag.paperCount})
                      </button>
                    );
                  })}
                </div>
                <div className="flex justify-end">
                  <Button size="sm" variant="outline" onClick={() => mergeGroup(i)} disabled={mergingGroup === i}>
                    {mergingGroup === i ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : <Merge className="mr-1 h-3 w-3" />}
                    Merge
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Smart cleanup */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5" /> Smart Cleanup</Label>
            <p className="text-xs text-muted-foreground mt-0.5">Deletes orphans, merges similar singletons, recomputes scores.</p>
          </div>
          <Button variant="outline" size="sm" onClick={runSmartCleanup} disabled={cleanupRunning}>
            {cleanupRunning ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1.5 h-3.5 w-3.5" />}
            Run
          </Button>
        </div>
        {cleanupResult && (
          <div className="rounded-md border p-3 space-y-1 text-xs">
            <p><strong>{cleanupResult.tagsBefore}</strong> → <strong>{cleanupResult.tagsAfter}</strong> tags</p>
            {cleanupResult.orphansDeleted.length > 0 && (
              <p className="text-muted-foreground">Deleted: {cleanupResult.orphansDeleted.join(", ")}</p>
            )}
            {cleanupResult.singletonsMerged.length > 0 && (
              <p className="text-muted-foreground">Merged: {cleanupResult.singletonsMerged.map((m) => `${m.from} → ${m.into}`).join(", ")}</p>
            )}
            <p className="text-muted-foreground">{cleanupResult.scoresUpdated} scores updated</p>
          </div>
        )}
      </div>

      {/* Clusters */}
      <div className="space-y-2 pt-4 border-t border-border">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-sm font-medium flex items-center gap-1.5"><Grid3X3 className="h-3.5 w-3.5" /> Tag Clusters</Label>
            <p className="text-xs text-muted-foreground mt-0.5">AI-generated thematic groupings for navigation.</p>
          </div>
          <Button variant="outline" size="sm" onClick={runGenerateClusters} disabled={clusterRunning}>
            {clusterRunning ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Grid3X3 className="mr-1.5 h-3.5 w-3.5" />}
            Generate
          </Button>
        </div>
        {clusterResult && (
          <div className="rounded-md border p-3 space-y-1 text-xs">
            {clusterResult.clusters.map((c) => (
              <div key={c.name} className="flex items-center gap-2">
                <Badge variant="secondary" className="text-[10px]">{c.tagCount}</Badge>
                <span className="font-medium">{c.name}</span>
                <span className="text-muted-foreground">{c.description}</span>
              </div>
            ))}
            {clusterResult.unassigned.length > 0 && (
              <p className="text-muted-foreground">Unassigned: {clusterResult.unassigned.join(", ")}</p>
            )}
          </div>
        )}
      </div>

      {/* All tags */}
      {tags.length > 0 && (
        <div className="space-y-2 pt-4 border-t border-border">
          <Label className="text-sm font-medium">All Tags ({tags.length})</Label>
          <div className="space-y-1 max-h-[300px] overflow-auto">
            {tags.map((tag) => (
              <div key={tag.id} className="flex items-center justify-between rounded-md border px-3 py-1.5">
                <div className="flex items-center gap-2">
                  <Badge style={{ backgroundColor: tag.color + "20", color: tag.color }}>{tag.name}</Badge>
                  <span className="text-xs text-muted-foreground">{tag._count.papers} paper{tag._count.papers !== 1 ? "s" : ""}</span>
                  {tag.isAutoGenerated && <Badge variant="outline" className="text-[10px]">Auto</Badge>}
                </div>
                <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => deleteTag(tag.id)}>
                  <Trash2 className="h-3 w-3" />
                </Button>
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  );
}

// ── Agent Capabilities ─────────────────────────────────────────────

interface Capability {
  id: string;
  name: string;
  description: string;
  instructions: string;
  enabled: boolean;
}

const CAPABILITY_EXAMPLES = [
  {
    name: "Weights & Biases",
    description: "Experiment tracking and visualization platform",
    instructions: "Use `wandb` for experiment tracking. It's already installed and configured.\n\nIn experiment code, add:\n```python\nimport wandb\nwandb.init(project=\"research-agent\")\nwandb.log({\"metric\": value})\n```\n\nThe API key is set in the environment as WANDB_API_KEY.",
  },
  {
    name: "LLM Data Generation",
    description: "Generate synthetic datasets using LLMs via a local API",
    instructions: "To generate synthetic data, write a Python script that calls:\n```python\nimport requests\nres = requests.post(\"http://localhost:3000/api/generate\", json={\n  \"prompt\": \"your prompt here\",\n  \"n\": 100,  # number of samples\n  \"model\": \"gpt-4o-mini\"\n})\ndata = res.json()[\"samples\"]\n```\n\nUse this when you need labeled data for experiments but no suitable public dataset exists.",
  },
  {
    name: "HuggingFace Hub",
    description: "Access to HuggingFace models and datasets",
    instructions: "HuggingFace token is set in the environment as HF_TOKEN.\n\nUse `huggingface_hub` and `datasets` libraries freely:\n```python\nfrom datasets import load_dataset\nfrom transformers import AutoModel, AutoTokenizer\n```\n\nPrefer loading datasets with streaming=True for large datasets.",
  },
];

function AgentCapabilitiesSection() {
  const [capabilities, setCapabilities] = useState<Capability[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", instructions: "" });
  const [saving, setSaving] = useState(false);

  const fetchCapabilities = useCallback(async () => {
    try {
      const res = await fetch("/api/settings/agent-capabilities");
      if (res.ok) setCapabilities(await res.json());
    } catch { /* ignore */ }
    setLoading(false);
  }, []);

  useEffect(() => { fetchCapabilities(); }, [fetchCapabilities]);

  const handleSave = async () => {
    if (!form.name.trim() || !form.instructions.trim()) return;
    setSaving(true);
    try {
      if (editingId) {
        const res = await fetch("/api/settings/agent-capabilities", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: editingId, ...form }),
        });
        if (res.ok) {
          toast.success("Capability updated");
          setEditingId(null);
        }
      } else {
        const res = await fetch("/api/settings/agent-capabilities", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(form),
        });
        if (res.ok) {
          toast.success("Capability added");
          setShowNew(false);
        }
      }
      setForm({ name: "", description: "", instructions: "" });
      await fetchCapabilities();
    } catch {
      toast.error("Failed to save");
    }
    setSaving(false);
  };

  const handleDelete = async (id: string) => {
    try {
      await fetch("/api/settings/agent-capabilities", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      toast.success("Removed");
      await fetchCapabilities();
    } catch {
      toast.error("Failed to delete");
    }
  };

  const handleToggle = async (cap: Capability) => {
    try {
      await fetch("/api/settings/agent-capabilities", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: cap.id, enabled: !cap.enabled }),
      });
      await fetchCapabilities();
    } catch {
      toast.error("Failed to update");
    }
  };

  const startEdit = (cap: Capability) => {
    setEditingId(cap.id);
    setForm({ name: cap.name, description: cap.description, instructions: cap.instructions });
    setShowNew(false);
  };

  const startNew = (example?: typeof CAPABILITY_EXAMPLES[0]) => {
    setEditingId(null);
    setForm(example || { name: "", description: "", instructions: "" });
    setShowNew(true);
  };

  return (
    <>
      <SectionHeader
        title="Agent Capabilities"
        description="Define tools, APIs, and resources the research agent can use. These are injected into the agent's context so it knows what's available."
      />

      {loading ? (
        <div className="flex items-center gap-2 py-8 justify-center text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" /> Loading...
        </div>
      ) : (
        <div className="space-y-3">
          {/* Existing capabilities */}
          {capabilities.map((cap) => (
            <div
              key={cap.id}
              className={`rounded-lg border px-4 py-3 transition-colors ${
                cap.enabled ? "border-border bg-card" : "border-border/50 bg-muted/30 opacity-60"
              }`}
            >
              {editingId === cap.id ? (
                <CapabilityForm
                  form={form}
                  setForm={setForm}
                  onSave={handleSave}
                  onCancel={() => { setEditingId(null); setForm({ name: "", description: "", instructions: "" }); }}
                  saving={saving}
                  isEdit
                />
              ) : (
                <div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-sm">{cap.name}</span>
                      {!cap.enabled && (
                        <span className="text-[10px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded">disabled</span>
                      )}
                    </div>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleToggle(cap)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
                        title={cap.enabled ? "Disable" : "Enable"}
                      >
                        {cap.enabled ? <Power className="h-3.5 w-3.5" /> : <PowerOff className="h-3.5 w-3.5" />}
                      </button>
                      <button
                        onClick={() => startEdit(cap)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
                        title="Edit"
                      >
                        <Pencil className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => handleDelete(cap.id)}
                        className="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-destructive/10 hover:text-destructive transition-colors"
                        title="Delete"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                  {cap.description && (
                    <p className="text-xs text-muted-foreground mt-1">{cap.description}</p>
                  )}
                  <pre className="mt-2 text-[11px] text-muted-foreground bg-muted/50 rounded p-2 whitespace-pre-wrap max-h-32 overflow-auto font-mono">
                    {cap.instructions}
                  </pre>
                </div>
              )}
            </div>
          ))}

          {/* New capability form */}
          {showNew && (
            <div className="rounded-lg border border-blue-500/30 bg-blue-500/5 px-4 py-3">
              <CapabilityForm
                form={form}
                setForm={setForm}
                onSave={handleSave}
                onCancel={() => { setShowNew(false); setForm({ name: "", description: "", instructions: "" }); }}
                saving={saving}
              />
            </div>
          )}

          {/* Add button + examples */}
          {!showNew && !editingId && (
            <div className="space-y-3">
              <Button variant="outline" size="sm" onClick={() => startNew()} className="gap-1.5">
                <Plus className="h-3.5 w-3.5" /> Add Capability
              </Button>

              {capabilities.length === 0 && (
                <div className="space-y-2">
                  <p className="text-xs text-muted-foreground">Quick-start with an example:</p>
                  <div className="flex flex-wrap gap-2">
                    {CAPABILITY_EXAMPLES.map((ex) => (
                      <button
                        key={ex.name}
                        onClick={() => startNew(ex)}
                        className="rounded-md border border-dashed border-border px-3 py-1.5 text-xs text-muted-foreground hover:border-foreground/30 hover:text-foreground transition-colors"
                      >
                        {ex.name}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </>
  );
}

function CapabilityForm({
  form,
  setForm,
  onSave,
  onCancel,
  saving,
  isEdit,
}: {
  form: { name: string; description: string; instructions: string };
  setForm: (f: { name: string; description: string; instructions: string }) => void;
  onSave: () => void;
  onCancel: () => void;
  saving: boolean;
  isEdit?: boolean;
}) {
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label className="text-xs">Name</Label>
          <Input
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
            placeholder="e.g., Weights & Biases"
            className="mt-1 text-sm h-8"
          />
        </div>
        <div>
          <Label className="text-xs">Description (optional)</Label>
          <Input
            value={form.description}
            onChange={(e) => setForm({ ...form, description: e.target.value })}
            placeholder="e.g., Experiment tracking platform"
            className="mt-1 text-sm h-8"
          />
        </div>
      </div>
      <div>
        <Label className="text-xs">Instructions for the agent</Label>
        <textarea
          value={form.instructions}
          onChange={(e) => setForm({ ...form, instructions: e.target.value })}
          placeholder="Tell the agent how to use this capability. Include code snippets, API endpoints, environment variables, etc."
          rows={6}
          className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm font-mono focus:outline-none focus:ring-1 focus:ring-ring resize-y"
        />
      </div>
      <div className="flex items-center gap-2">
        <Button size="sm" onClick={onSave} disabled={saving || !form.name.trim() || !form.instructions.trim()}>
          {saving ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <Save className="h-3.5 w-3.5 mr-1.5" />}
          {isEdit ? "Update" : "Add"}
        </Button>
        <Button size="sm" variant="ghost" onClick={onCancel}>
          Cancel
        </Button>
      </div>
    </div>
  );
}

// ── Remote ─────────────────────────────────────────────────────────

function RemoteSection() {
  return (
    <>
      <SectionHeader title="Remote Execution" description="Configure GPU hosts for running experiments remotely." />
      <RemoteHostsManager />
    </>
  );
}
